"use client";

import Link from "next/link";
import { useState, type FormEvent } from "react";
import { ShieldCheck, UserPlus } from "lucide-react";

export default function JoinPage(){
  const [form,setForm]=useState({code:"",name:"",email:"",password:""});const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[done,setDone]=useState<string|null>(null);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError(null);try{const r=await fetch("/api/join",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const b=await r.json();if(!r.ok)throw new Error(b.error||"가입 실패");setDone(`${b.firmName||"로펌"} 직원계정 가입이 완료되었습니다.`)}catch(e){setError(e instanceof Error?e.message:"가입 실패")}finally{setBusy(false)}}
  return <main className="grid min-h-screen place-items-center bg-[#f6f8fb] p-4"><div className="w-full max-w-md rounded-2xl border bg-white p-7 shadow-sm"><div className="mb-6 flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-blue-600 text-white"><UserPlus size={21}/></div><div><h1 className="text-xl font-black">로펌 직원 가입</h1><p className="text-xs text-slate-500">24시간 · 1회용 초대코드 전용</p></div></div>{done?<div><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-700">{done}</div><Link href="/login" className="mt-4 flex h-11 items-center justify-center rounded-lg bg-blue-600 text-sm font-bold text-white">로그인하기</Link></div>:<form onSubmit={submit} className="space-y-3">{[["초대코드","code","LP-XXXXXXXXXX"],["이름","name","홍길동"],["이메일","email","name@example.com"],["비밀번호","password","8자 이상"]].map(([label,key,ph])=><label key={key} className="block"><span className="mb-1 block text-xs font-bold text-slate-600">{label}</span><input required type={key==="password"?"password":key==="email"?"email":"text"} value={(form as any)[key]} onChange={e=>setForm(v=>({...v,[key]:e.target.value}))} placeholder={ph} className="h-11 w-full rounded-lg border px-3 text-sm"/></label>)}{error&&<div className="rounded-lg bg-red-50 px-3 py-2 text-xs font-bold text-red-700">{error}</div>}<button disabled={busy} className="h-11 w-full rounded-lg bg-blue-600 text-sm font-bold text-white disabled:opacity-50">{busy?"가입 처리 중...":"직원계정 가입"}</button><Link href="/login" className="block text-center text-xs font-semibold text-slate-500 hover:text-blue-600">이미 계정이 있으면 로그인</Link></form>}</div></main>
}
