"use client";

import { Fragment, useEffect, useState } from "react";
import {
  LayoutDashboard, Inbox, Users, Columns3, CalendarDays, FileSignature, FolderCheck, Landmark, CreditCard,
  BarChart3, History, Menu, X, RotateCcw, Plus, Search, CheckCircle2, AlertTriangle, FileText,
  Save, Download, Bell, MessageSquareText, Calculator, Settings, Printer, ChevronRight, ChevronDown, ChevronUp, ArrowRight, UserPlus,
  Trash2, WalletCards
} from "lucide-react";
import {
  AssetItem, BoardPost, CaseProgress, Client, ConsultationLog, DebtItem, DemoDB, DocStatus, Matter,
  MatterStatus, MatterType, Payment, PaymentMethod, PaymentStatus, assetTypes, consultationGuides,
  debtTypes, defaultChecklist, matterStatuses, matterTypes, occupationTypes, paymentMethods, seedDemoDB
} from "@/lib/demo-data";

const STORAGE_KEY = "maeil-admin-demo-v4-2";
const LEGACY_STORAGE_KEYS = ["rehab-bankruptcy-admin-demo-v2", "maeil-admin-demo-v4"];

type Section = "dashboard"|"leads"|"clients"|"pipeline"|"schedule"|"contracts"|"payments"|"documents"|"cases"|"analytics"|"calculator"|"settings"|"history"|"board";
const sections: {id:Section;label:string;icon:React.ComponentType<{size?:number}>}[] = [
  {id:"dashboard",label:"대시보드",icon:LayoutDashboard},
  {id:"leads",label:"신규 상담 DB",icon:Inbox},
  {id:"clients",label:"상담 / 고객 관리",icon:Users},
  {id:"pipeline",label:"파이프라인",icon:Columns3},
  {id:"schedule",label:"오늘의 일정",icon:CalendarDays},
  {id:"contracts",label:"계약 관리",icon:FileSignature},
  {id:"payments",label:"입금 / 분납",icon:CreditCard},
  {id:"documents",label:"서류 수합",icon:FolderCheck},
  {id:"cases",label:"사건 진행",icon:Landmark},
  {id:"analytics",label:"데이터 집계",icon:BarChart3},
  {id:"calculator",label:"회생 예상계산기",icon:Calculator},
  {id:"settings",label:"기준표 / 설정",icon:Settings},
  {id:"history",label:"변동내역",icon:History},
  {id:"board",label:"내부 게시판",icon:MessageSquareText},
];

const today = () => new Date().toISOString().slice(0,10);
const id = (prefix:string) => `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;
const money = (v:number) => `${Math.round(v||0).toLocaleString("ko-KR")}원`;
const dateLabel = (v:string) => v ? new Date(v.length===10?`${v}T00:00:00`:v).toLocaleDateString("ko-KR") : "-";
const terminalStatuses: MatterStatus[] = ["종결(성공)","거절","부적합","종결(중단)","외부이관"];
const statusTone = (s:string) => s.includes("종결")||s==="수임"?"green":s.includes("거절")||s==="부적합"?"red":s.includes("계약")||s==="진행중"?"purple":s.includes("재통화")||s==="부재중"?"amber":"blue";
const isClientRegistered = (m:Matter) => m.clientRegistered === true || (m.clientRegistered == null && !["신규접수","상담예정","부재중"].includes(m.status));

type Tone = "gray"|"blue"|"green"|"red"|"amber"|"purple";
function Badge({children,tone="gray"}:{children:React.ReactNode;tone?:Tone}){ return <span className={`badge badge-${tone}`}>{children}</span> }
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){ return <label className={`field ${wide?"field-wide":""}`}><span>{label}</span>{children}</label> }
function Modal({title,onClose,children,wide=false,extra}:{title:string;onClose:()=>void;children:React.ReactNode;wide?:boolean;extra?:React.ReactNode}){ return <div className="modal-backdrop" onMouseDown={onClose}><div className={`modal-card ${wide?"modal-wide":""}`} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">DEMO WORKSPACE</span><h2>{title}</h2></div><div className="modal-head-actions">{extra}<button className="icon-btn" onClick={onClose}><X size={18}/></button></div></div><div className="modal-body">{children}</div></div></div> }
function Empty({text}:{text:string}){ return <div className="empty"><FileText size={34}/><b>{text}</b><span>데모 데이터를 추가하거나 필터 조건을 변경해보세요.</span></div> }
function Progress({value}:{value:number}){ return <div className="progress"><div style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div> }
function PageHead({title,desc,action}:{title:string;desc:string;action?:React.ReactNode}){ return <div className="page-title"><div><h1>{title}</h1><p>{desc}</p></div>{action}</div> }
function ModalActions({onCancel,onSave,disabled=false}:{onCancel:()=>void;onSave:()=>void;disabled?:boolean}){ return <div className="modal-actions"><button className="secondary" onClick={onCancel}>취소</button><button className="primary" disabled={disabled} onClick={onSave}><Save size={16}/>저장</button></div> }

function calcMatter(db:DemoDB,m: Matter){
  const totalIncome = (m.monthlyIncome||0)+(m.sideIncome||0)+(m.pensionIncome||0);
  const livingCosts = db.settings?.livingCostByHousehold ?? {};
  const living = livingCosts[String(m.householdSize)] ?? livingCosts["6"] ?? 0;
  const disposable = Math.max(0,totalIncome-living-(m.extraDeduction||0));
  const assets = db.assets.filter(x=>x.matterId===m.id);
  const totalAssets = assets.reduce((a,b)=>a+b.value,0);
  const securedOnAssets = assets.reduce((a,b)=>a+b.securedAmount,0);
  const liquidation = Math.max(0,totalAssets-securedOnAssets);
  const debts = db.debts.filter(x=>x.matterId===m.id);
  const taxHealth = debts.filter(x=>x.type==="세금체납"||x.type==="건강보험체납").reduce((a,b)=>a+b.amount,0);
  const securedDebt = debts.filter(x=>x.type.startsWith("담보채무")).reduce((a,b)=>a+b.amount,0);
  const unsecured = debts.filter(x=>["신용채무","개인채무","기타"].includes(x.type)).reduce((a,b)=>a+b.amount,0);
  const incomePlan = disposable*Math.max(1,m.repaymentMonths||36);
  const rawFinalTotal = Math.max(incomePlan,liquidation);
  const finalTotal = unsecured>0 ? Math.min(unsecured,rawFinalTotal) : rawFinalTotal;
  const finalMonthly = finalTotal/Math.max(1,m.repaymentMonths||36);
  const relief = Math.max(0,unsecured-finalTotal);
  const reliefRate = unsecured ? relief/unsecured*100 : 0;
  let recommendation = "정보부족";
  if(unsecured>0 && totalIncome>0){
    if(liquidation>unsecured || disposable<=0) recommendation="비추천";
    else if(reliefRate>=30) recommendation="적극추천";
    else recommendation="조건부가능";
  }
  return {totalIncome,living,disposable,totalAssets,securedOnAssets,liquidation,taxHealth,taxPriorityLimit:taxHealth*.5,securedDebt,unsecured,incomePlan,finalTotal,finalMonthly,relief,reliefRate,recommendation,liquidationSatisfied:incomePlan>=liquidation};
}

function docCompletion(db:DemoDB,matterId:string){
  const ds=db.documents.filter(x=>x.matterId===matterId); if(!ds.length)return 0;
  const done=ds.filter(x=>x.status==="수령"||x.status==="해당없음").length; return Math.round(done/ds.length*100);
}

export default function DemoAdmin(){
  const [db,setDb] = useState<DemoDB|null>(null);
  const [section,setSection] = useState<Section>("dashboard");
  const [menuOpen,setMenuOpen] = useState(false);
  const [detailMatterId,setDetailMatterId] = useState<string|null>(null);
  const [printMatterId,setPrintMatterId] = useState<string|null>(null);

  useEffect(()=>{
    const timer = window.setTimeout(()=>{
      const fresh = seedDemoDB();
      try{
        const raw = localStorage.getItem(STORAGE_KEY);
        if(!raw){ setDb(fresh); return; }
        const parsed = JSON.parse(raw) as Partial<DemoDB>;
        const settings = parsed.settings && typeof parsed.settings === "object" ? parsed.settings : undefined;
        const compatible: DemoDB = {
          ...fresh,
          ...parsed,
          clients: Array.isArray(parsed.clients) ? parsed.clients : fresh.clients,
          matters: Array.isArray(parsed.matters) ? parsed.matters : fresh.matters,
          assets: Array.isArray(parsed.assets) ? parsed.assets : fresh.assets,
          debts: Array.isArray(parsed.debts) ? parsed.debts : fresh.debts,
          logs: Array.isArray(parsed.logs) ? parsed.logs : fresh.logs,
          contracts: Array.isArray(parsed.contracts) ? parsed.contracts : fresh.contracts,
          payments: Array.isArray(parsed.payments) ? parsed.payments : fresh.payments,
          documents: Array.isArray(parsed.documents) ? parsed.documents : fresh.documents,
          cases: Array.isArray(parsed.cases) ? parsed.cases : fresh.cases,
          history: Array.isArray(parsed.history) ? parsed.history : fresh.history,
          board: Array.isArray(parsed.board) ? parsed.board : fresh.board,
          settings: {
            ...fresh.settings,
            ...(settings ?? {}),
            livingCostByHousehold: settings?.livingCostByHousehold && typeof settings.livingCostByHousehold === "object"
              ? settings.livingCostByHousehold : fresh.settings.livingCostByHousehold,
            pipelineStatuses: Array.isArray(settings?.pipelineStatuses) ? settings.pipelineStatuses : fresh.settings.pipelineStatuses,
            staffOptions: Array.isArray(settings?.staffOptions) ? settings.staffOptions : fresh.settings.staffOptions,
            leasePriorityByRegion: settings?.leasePriorityByRegion && typeof settings.leasePriorityByRegion === "object"
              ? settings.leasePriorityByRegion : fresh.settings.leasePriorityByRegion,
          }
        };
        setDb(compatible);
      }
      catch{ setDb(fresh); }
    },0);
    return ()=>window.clearTimeout(timer);
  },[]);
  useEffect(()=>{ if(db)localStorage.setItem(STORAGE_KEY,JSON.stringify(db)); },[db]);

  if(!db) return <div className="loading">DEMO Admin 불러오는 중…</div>;
  const update=(fn:(x:DemoDB)=>DemoDB)=>setDb(prev=>prev?fn(prev):prev);
  const addHistory=(category:string,action:string,target:string,detail:string)=>({id:id("h"),createdAt:new Date().toISOString(),category,action,target,detail});
  const reset=()=>{if(confirm("모든 데모 데이터를 초기 상태로 되돌릴까요?")){[STORAGE_KEY,...LEGACY_STORAGE_KEYS].forEach(k=>localStorage.removeItem(k));setDb(seedDemoDB());setSection("dashboard")}};
  const exportJson=()=>{const blob=new Blob([JSON.stringify(db,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`rehab-bankruptcy-demo-${today()}.json`;a.click();URL.revokeObjectURL(a.href)};
  const navigate=(s:Section)=>{setSection(s);setMenuOpen(false)};
  const triggerPrint=(matterId:string)=>{setPrintMatterId(matterId);setTimeout(()=>window.print(),60)};
  const openDetail=(matterId:string)=>setDetailMatterId(matterId);
  const currentDetail=detailMatterId?db.matters.find(x=>x.id===detailMatterId):undefined;

  return <>
    <div className="app-shell">
      {menuOpen&&<div className="mobile-overlay" onClick={()=>setMenuOpen(false)}/>} 
      <aside className={`sidebar ${menuOpen?"open":""}`}>
        <div className="brand"><div className="brand-mark">RB</div><div><b>회생 · 파산 Admin</b><span>FUNCTIONAL DEMO</span></div><button className="mobile-close" onClick={()=>setMenuOpen(false)}><X/></button></div>
        <div className="demo-label"><span>DEMO MODE</span><small>실서버 · 실고객 · 실API 미연동</small></div>
        <nav>{sections.map(s=>{const Icon=s.icon;return <button key={s.id} className={section===s.id?"active":""} onClick={()=>navigate(s.id)}><Icon size={17}/>{s.label}{s.id==="schedule"&&<em>{db.matters.filter(m=>m.nextActionAt===today()).length}</em>}</button>})}</nav>
        <div className="sidebar-bottom"><button onClick={exportJson}><Download size={16}/>JSON 내보내기</button><button className="danger-soft" onClick={reset}><RotateCcw size={16}/>데모 데이터 초기화</button></div>
      </aside>
      <main className="main">
        <header className="topbar"><div className="topbar-left"><button className="menu-btn" onClick={()=>setMenuOpen(true)}><Menu size={20}/></button><div><strong>개인회생 · 개인파산 상담 통합 Admin</strong><span>기존 상담시트 업무흐름을 웹 Admin으로 재구성한 기능 데모</span></div></div><div className="topbar-right"><button className="notification" onClick={()=>navigate("schedule")}><Bell size={18}/>{db.matters.filter(m=>m.nextActionAt===today()).length>0&&<i>{db.matters.filter(m=>m.nextActionAt===today()).length}</i>}</button><div className="user-chip"><span>DEMO</span><b>관리자</b></div></div></header>
        <div className="page-wrap">
          {section==="dashboard"&&<Dashboard db={db} navigate={navigate} openDetail={openDetail}/>} 
          {section==="leads"&&<Leads db={db} update={update} addHistory={addHistory} openDetail={openDetail}/>} 
          {section==="clients"&&<Clients db={db} update={update} addHistory={addHistory} openDetail={openDetail}/>} 
          {section==="pipeline"&&<Pipeline db={db} update={update} addHistory={addHistory} openDetail={openDetail}/>} 
          {section==="schedule"&&<Schedule db={db} update={update} addHistory={addHistory} openDetail={openDetail}/>} 
          {section==="contracts"&&<Contracts db={db} update={update} addHistory={addHistory}/>} 
          {section==="payments"&&<Payments db={db} update={update} addHistory={addHistory}/>} 
          {section==="documents"&&<Documents db={db} update={update} addHistory={addHistory}/>} 
          {section==="cases"&&<Cases db={db} update={update} addHistory={addHistory}/>} 
          {section==="analytics"&&<Analytics db={db}/>} 
          {section==="calculator"&&<CalculatorPage db={db} update={update} addHistory={addHistory} openDetail={openDetail}/>} 
          {section==="settings"&&<SettingsPage db={db} update={update} addHistory={addHistory}/>} 
          {section==="history"&&<HistoryPage db={db}/>} 
          {section==="board"&&<Board db={db} update={update} addHistory={addHistory}/>} 
        </div>
      </main>
    </div>
    {currentDetail&&<ClientDetail db={db} matter={currentDetail} update={update} addHistory={addHistory} onClose={()=>setDetailMatterId(null)} onPrint={()=>triggerPrint(currentDetail.id)}/>} 
    {printMatterId&&<PrintSheet db={db} matterId={printMatterId}/>} 
  </>;
}

type UpdateFn=(fn:(d:DemoDB)=>DemoDB)=>void;
type HistoryFn=(category:string,action:string,target:string,detail:string)=>{id:string;createdAt:string;category:string;action:string;target:string;detail:string};

function Dashboard({db,navigate,openDetail}:{db:DemoDB;navigate:(s:Section)=>void;openDetail:(id:string)=>void}){
  const active=db.matters.filter(m=>!terminalStatuses.includes(m.status));
  const signed=db.matters.filter(m=>["수임","진행중","종결(성공)"].includes(m.status));
  const todayActions=db.matters.filter(m=>m.nextActionAt===today());
  const overdueActions=db.matters.filter(m=>m.nextActionAt&&m.nextActionAt<today()&&!terminalStatuses.includes(m.status));
  const paid=db.payments.filter(p=>p.status==="완료").reduce((a,b)=>a+b.paidAmount,0);
  const contracts=db.contracts.reduce((a,b)=>a+b.contractAmount,0);
  const groups=[
    ["신규/예정",["신규접수","상담예정"]],["상담/재통화",["상담완료","재통화필요","부재중"]],["검토",["고려중","검토중","서류검토중","방문예정","대면예약완료"]],
    ["계약",["계약진행중"]],["수임",["수임"]],["진행",["진행중"]],["종결",["종결(성공)","거절","부적합","종결(중단)","외부이관"]]
  ] as const;
  return <>
    <PageHead title="대시보드" desc="전체 상담현황, 파이프라인, 오늘 할 일, 계약·수금·서류 현황을 한 번에 확인합니다."/>
    <div className="kpi-grid">
      <Kpi icon={<Inbox size={19}/>} label="전체 상담건" value={`${db.matters.length}건`} sub={`활성 ${active.length}건`} onClick={()=>navigate("leads")}/>
      <Kpi icon={<FileSignature size={19}/>} label="수임/진행" value={`${signed.length}건`} sub="수임 이상 단계" onClick={()=>navigate("pipeline")}/>
      <Kpi icon={<CalendarDays size={19}/>} label="오늘 액션" value={`${todayActions.length}건`} sub={`기한경과 ${overdueActions.length}건`} onClick={()=>navigate("schedule")}/>
      <Kpi icon={<WalletCards size={19}/>} label="실입금" value={money(paid)} sub={`계약총액 ${money(contracts)}`} onClick={()=>navigate("payments")}/>
    </div>
    <div className="dashboard-grid">
      <section className="panel"><div className="panel-head"><div><h3>상담 파이프라인</h3><p>구글시트의 상태 관리 흐름을 웹 파이프라인으로 재구성</p></div><button className="text-btn" onClick={()=>navigate("pipeline")}>전체보기 <ChevronRight size={14}/></button></div><div className="pipeline-row">{groups.map(([g,sts])=><div className="pipeline-item" key={g}><span>{g}</span><b>{db.matters.filter(m=>(sts as readonly string[]).includes(m.status)).length}</b></div>)}</div></section>
      <section className="panel"><div className="panel-head"><div><h3>오늘의 업무</h3><p>다음액션일 기준</p></div><button className="text-btn" onClick={()=>navigate("schedule")}>일정관리 <ChevronRight size={14}/></button></div><div className="list-rows">{todayActions.length?todayActions.slice(0,6).map(m=>{const c=db.clients.find(x=>x.id===m.clientId);return <button className="list-row" key={m.id} onClick={()=>openDetail(m.id)}><div><b>{c?.name} · {m.nextActionType||"후속 확인"}</b><span>{m.caseType} · {m.status} · {m.assignedTo}</span></div><Badge tone={statusTone(m.status) as Tone}>{m.status}</Badge></button>}):<div className="muted">오늘 지정된 액션이 없습니다.</div>}</div></section>
      <section className="panel"><div className="panel-head"><div><h3>서류 수합</h3><p>수임 이상 사건 중 체크리스트 진행률</p></div><button className="text-btn" onClick={()=>navigate("documents")}>서류관리 <ChevronRight size={14}/></button></div><div className="list-rows">{db.matters.filter(m=>db.documents.some(d=>d.matterId===m.id)).slice(0,6).map(m=>{const c=db.clients.find(x=>x.id===m.clientId);const pct=docCompletion(db,m.id);return <button className="list-row doc-row" key={m.id} onClick={()=>openDetail(m.id)}><div><b>{c?.name}</b><span>{m.caseType} · {pct}% 완료</span><Progress value={pct}/></div><strong>{pct}%</strong></button>})}</div></section>
      <section className="panel"><div className="panel-head"><div><h3>예상 변제 스냅샷</h3><p>상담용 자동계산 결과 · 법적 최종 확정치 아님</p></div><button className="text-btn" onClick={()=>navigate("calculator")}>계산기 <ChevronRight size={14}/></button></div><div className="list-rows">{db.matters.filter(m=>m.caseType==="개인회생").slice(0,5).map(m=>{const c=db.clients.find(x=>x.id===m.clientId);const x=calcMatter(db,m);return <button className="list-row" key={m.id} onClick={()=>openDetail(m.id)}><div><b>{c?.name}</b><span>월 {money(x.finalMonthly)} · 예상 탕감률 {x.reliefRate.toFixed(1)}%</span></div><Badge tone={x.recommendation==="적극추천"?"green":x.recommendation==="비추천"?"red":"amber"}>{x.recommendation}</Badge></button>})}</div></section>
    </div>
  </>
}
function Kpi({icon,label,value,sub,onClick}:{icon:React.ReactNode;label:string;value:string;sub:string;onClick:()=>void}){return <button className="kpi-card" onClick={onClick}><div className="kpi-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div></button>}

function Leads({db,update,addHistory,openDetail}:{db:DemoDB;update:UpdateFn;addHistory:HistoryFn;openDetail:(id:string)=>void}){
  const [q,setQ]=useState("");const [status,setStatus]=useState("전체");const [modal,setModal]=useState(false);
  const blank={name:"",phone:"",caseType:"개인회생" as MatterType,status:"신규접수" as MatterStatus,assignedTo:db.settings.staffOptions[0]||"상담1",source:"DEMO 유입",nextActionAt:today(),nextActionType:"문자인사"};
  const [form,setForm]=useState(blank);
  const rows=db.matters.filter(m=>{const c=db.clients.find(x=>x.id===m.clientId);return (!q||`${c?.name} ${c?.phone} ${m.memo}`.toLowerCase().includes(q.toLowerCase()))&&(status==="전체"||m.status===status)}).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  const duplicate=db.clients.find(c=>form.phone&&c.phone.replace(/\D/g,"")===form.phone.replace(/\D/g,""))||db.clients.find(c=>form.name&&c.name===form.name);
  const save=()=>{
    if(!form.name.trim())return alert("이름을 입력하세요.");
    let clientId=duplicate?.id;
    if(duplicate&&!confirm(`${duplicate.name} 고객이 이미 존재합니다. 기존 고객에 새 상담건으로 추가할까요?\n취소를 누르면 신규 고객으로 별도 등록됩니다.`)) clientId=undefined;
    const newClient:Client|undefined=clientId?undefined:{id:id("c"),createdAt:new Date().toISOString(),name:form.name.trim(),phone:form.phone,birthDate:"",gender:"미입력",address:"",spouse:"",children:"",dependents:1,healthIssue:"",memo:""};
    if(newClient)clientId=newClient.id;
    const m:Matter={id:id("m"),clientId:clientId!,createdAt:new Date().toISOString(),caseType:form.caseType,status:form.status,source:form.source,assignedTo:form.assignedTo,consultDate:"",nextActionAt:form.nextActionAt,nextActionType:form.nextActionType,occupationType:"미입력",companyName:"",employmentInfo:"",monthlyIncome:0,sideIncome:0,pensionIncome:0,extraDeduction:0,repaymentMonths:36,householdSize:1,court:"미지정",specialIssue:"",memo:"",firstContactDone:false,contactAttempts:0,intakeTimeBand:"평오전",clientRegistered:false};
    update(d=>({...d,clients:newClient?[newClient,...d.clients]:d.clients,matters:[m,...d.matters],history:[addHistory("신규상담","등록",form.name,"신규 상담 DB 등록"),...d.history]}));
    setModal(false);setForm(blank);
  };
  const patch=(m:Matter,pp:Partial<Matter>)=>{const c=db.clients.find(x=>x.id===m.clientId);update(d=>({...d,matters:d.matters.map(x=>x.id===m.id?{...x,...pp}:x),history:[addHistory("신규상담","수정",c?.name||"고객",pp.status?`상태 → ${pp.status}`:"상담정보 수정"),...d.history]}))};
  const registerClient=(m:Matter)=>{const c=db.clients.find(x=>x.id===m.clientId);update(d=>({...d,matters:d.matters.map(x=>x.id===m.id?{...x,clientRegistered:true,clientRegisteredAt:new Date().toISOString()}:x),history:[addHistory("신규상담","이관",c?.name||"고객","상담/고객 관리로 고객 등록"),...d.history]}))};
  return <>
    <PageHead title="신규 상담 DB" desc="신규 유입을 확인한 뒤 한 번의 고객등록으로 상담/고객 관리에 연결합니다." action={<button className="primary" onClick={()=>setModal(true)}><Plus size={17}/>신규 상담 등록</button>}/>
    <div className="handoff-flow" aria-label="신규 상담 DB 고객등록 흐름">
      <span><b>1</b> 신규 DB 접수</span><ArrowRight size={16}/><span><b>2</b> 상담정보 확인</span><ArrowRight size={16}/><span className="accent"><b>3</b> 고객등록</span><ArrowRight size={16}/><span><b>4</b> 상담/고객 관리</span>
      <small>고객등록 버튼을 누르면 같은 의뢰인 정보와 상담건이 고객관리에서 바로 이어집니다.</small>
    </div>
    <div className="toolbar"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="이름 · 전화번호 · 메모 검색"/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option>전체</option>{matterStatuses.map(x=><option key={x}>{x}</option>)}</select><span className="count">{rows.length}건</span></div>
    <div className="table-card"><div className="table-scroll"><table className="wide-table lead-board"><thead><tr><th>접수일</th><th>의뢰인</th><th>사건유형</th><th>상태</th><th>다음액션</th><th>담당자</th><th>연락처</th><th>월소득</th><th>예상 월변제금</th><th>고객관리 이관</th><th>상세</th></tr></thead><tbody>{rows.map(m=>{const c=db.clients.find(x=>x.id===m.clientId);const x=calcMatter(db,m);const registered=isClientRegistered(m);return <tr key={m.id}><td>{dateLabel(m.createdAt)}</td><td><b>{c?.name}</b>{db.matters.filter(mm=>mm.clientId===m.clientId).length>1&&<small>상담 {db.matters.filter(mm=>mm.clientId===m.clientId).length}건</small>}</td><td>{m.caseType}</td><td><select className="mini-select" value={m.status} onChange={e=>patch(m,{status:e.target.value as MatterStatus})}>{matterStatuses.map(s=><option key={s}>{s}</option>)}</select></td><td><b>{m.nextActionAt||"-"}</b><small>{m.nextActionType||"-"}</small></td><td>{m.assignedTo}</td><td>{c?.phone||"-"}</td><td>{money(x.totalIncome)}</td><td>{m.caseType==="개인회생"?money(x.finalMonthly):"-"}</td><td>{registered?<div className="handoff-done"><Badge tone="green">등록완료</Badge><button className="text-btn" onClick={()=>openDetail(m.id)}>고객정보 열기</button></div>:<button className="small-btn handoff-btn" onClick={()=>registerClient(m)}><UserPlus size={14}/>고객등록 <ArrowRight size={13}/></button>}</td><td><button className="small-btn" onClick={()=>openDetail(m.id)}>상담열기</button></td></tr>})}</tbody></table></div></div>
    {modal&&<Modal title="신규 상담 등록" onClose={()=>setModal(false)}><div className="form-grid"><Field label="이름"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="연락처"><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="010-0000-0000"/></Field>{duplicate&&<div className="duplicate-warning field-wide"><AlertTriangle size={18}/><div><b>중복 가능 고객</b><span>{duplicate.name} · {duplicate.phone||"전화번호 없음"} · 기존 상담 {db.matters.filter(m=>m.clientId===duplicate.id).length}건</span></div></div>}<Field label="사건유형"><select value={form.caseType} onChange={e=>setForm({...form,caseType:e.target.value as MatterType})}>{matterTypes.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="상태"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value as MatterStatus})}>{matterStatuses.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="담당자"><select value={form.assignedTo} onChange={e=>setForm({...form,assignedTo:e.target.value})}>{db.settings.staffOptions.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="유입경로"><input value={form.source} onChange={e=>setForm({...form,source:e.target.value})}/></Field><Field label="다음액션일"><input type="date" value={form.nextActionAt} onChange={e=>setForm({...form,nextActionAt:e.target.value})}/></Field><Field label="다음액션"><input value={form.nextActionType} onChange={e=>setForm({...form,nextActionType:e.target.value})}/></Field></div><div className="modal-hint">저장하면 먼저 <b>신규 상담 DB</b>에 등록됩니다. 이후 목록의 <b>고객등록</b> 버튼으로 상담/고객 관리에 이관할 수 있습니다.</div><ModalActions onCancel={()=>setModal(false)} onSave={save}/></Modal>}
  </>
}

function Clients({db,update,addHistory,openDetail}:{db:DemoDB;update:UpdateFn;addHistory:HistoryFn;openDetail:(id:string)=>void}){
  const [q,setQ]=useState("");
  const registeredMatterIds=new Set(db.matters.filter(isClientRegistered).map(m=>m.clientId));
  const clients=db.clients.filter(c=>registeredMatterIds.has(c.id)&&(!q||`${c.name} ${c.phone} ${c.address}`.toLowerCase().includes(q.toLowerCase())));
  const deleteClient=(c:Client)=>{const ms=db.matters.filter(m=>m.clientId===c.id);if(ms.length>0)return alert("상담/사건 이력이 있는 고객은 데모에서도 고객 자체를 삭제할 수 없습니다. 해당 상담건 상태를 종결로 변경하세요.");if(confirm(`${c.name} 고객을 삭제할까요?`))update(d=>({...d,clients:d.clients.filter(x=>x.id!==c.id),history:[addHistory("고객관리","삭제",c.name,"고객 삭제"),...d.history]}))};
  return <><PageHead title="상담 / 고객 관리" desc="신규 상담 DB에서 '고객등록' 처리된 의뢰인만 이 목록에 표시됩니다."/><div className="board-notice"><UserPlus size={17}/><b>고객등록 완료 목록</b><span>신규 상담 DB → 고객등록 → 이 화면에서 상세 상담정보를 계속 관리합니다.</span></div><div className="toolbar"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="이름 · 연락처 · 주소 검색"/></div><span className="count">{clients.length}명</span></div><div className="table-card client-board"><div className="table-scroll"><table><thead><tr><th>의뢰인</th><th>연락처</th><th>거주지</th><th>연결 상담</th><th>최근유형</th><th>현재상태</th><th>담당자</th><th>다음액션</th><th>관리</th></tr></thead><tbody>{clients.map(c=>{const ms=db.matters.filter(m=>m.clientId===c.id&&isClientRegistered(m)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));const latest=ms[0];return <tr key={c.id}><td><b>{c.name}</b>{ms.length>1&&<small>연결 상담 {ms.length}건</small>}</td><td>{c.phone||"-"}</td><td className="address-cell">{c.address||"-"}</td><td><b>{ms.length}건</b></td><td>{latest?.caseType||"-"}</td><td>{latest?<Badge tone={statusTone(latest.status) as Tone}>{latest.status}</Badge>:<span className="muted">상담 없음</span>}</td><td>{latest?.assignedTo||"-"}</td><td><b>{latest?.nextActionAt||"-"}</b><small>{latest?.nextActionType||""}</small></td><td>{latest?<button className="small-btn" onClick={()=>openDetail(latest.id)}>상세보기</button>:<button className="text-btn danger-link" onClick={()=>deleteClient(c)}>삭제</button>}</td></tr>})}</tbody></table></div></div></>
}

const pipelineGroups:{label:string;statuses:MatterStatus[];dropStatus:MatterStatus}[]=[
  {label:"신규/예정",statuses:["신규접수","상담예정"],dropStatus:"상담예정"},
  {label:"상담/재통화",statuses:["상담완료","재통화필요","부재중"],dropStatus:"재통화필요"},
  {label:"검토",statuses:["고려중","검토중","서류검토중","방문예정","대면예약완료"],dropStatus:"검토중"},
  {label:"계약",statuses:["계약진행중"],dropStatus:"계약진행중"},{label:"수임",statuses:["수임"],dropStatus:"수임"},{label:"진행",statuses:["진행중"],dropStatus:"진행중"},
  {label:"종결",statuses:["종결(성공)","거절","부적합","종결(중단)","외부이관"],dropStatus:"종결(성공)"},
];
function Pipeline({db,update,addHistory,openDetail}:{db:DemoDB;update:UpdateFn;addHistory:HistoryFn;openDetail:(id:string)=>void}){
  const [group,setGroup]=useState("전체");
  const patchStatus=(m:Matter,status:MatterStatus)=>{const c=db.clients.find(x=>x.id===m.clientId);update(d=>({...d,matters:d.matters.map(x=>x.id===m.id?{...x,status}:x),history:[addHistory("파이프라인","수정",c?.name||"고객",`상태 → ${status}`),...d.history]}))};
  const groupLabel=(m:Matter)=>pipelineGroups.find(g=>g.statuses.includes(m.status))?.label||"기타";
  const rows=db.matters.filter(m=>group==="전체"||groupLabel(m)===group).sort((a,b)=>(a.nextActionAt||"9999").localeCompare(b.nextActionAt||"9999"));
  return <><PageHead title="파이프라인" desc="카드형 칸반 대신 게시판 목록에서 단계·상태·다음액션을 한 번에 확인하고 수정합니다."/><div className="toolbar"><select value={group} onChange={e=>setGroup(e.target.value)}><option>전체</option>{pipelineGroups.map(g=><option key={g.label}>{g.label}</option>)}</select><span className="count">{rows.length}건</span><div className="pipeline-counts">{pipelineGroups.map(g=><button key={g.label} className={group===g.label?"active":""} onClick={()=>setGroup(group===g.label?"전체":g.label)}>{g.label} <b>{db.matters.filter(m=>g.statuses.includes(m.status)).length}</b></button>)}</div></div><div className="table-card"><div className="table-scroll"><table className="pipeline-board"><thead><tr><th>단계</th><th>의뢰인</th><th>사건유형</th><th>현재상태</th><th>담당자</th><th>다음액션일</th><th>다음액션</th><th>고객등록</th><th>상세</th></tr></thead><tbody>{rows.map(m=>{const c=db.clients.find(x=>x.id===m.clientId);return <tr key={m.id}><td><b>{groupLabel(m)}</b></td><td><b>{c?.name}</b><small>{c?.phone||"-"}</small></td><td>{m.caseType}</td><td><select className="mini-select" value={m.status} onChange={e=>patchStatus(m,e.target.value as MatterStatus)}>{matterStatuses.map(s=><option key={s}>{s}</option>)}</select></td><td>{m.assignedTo}</td><td>{m.nextActionAt||"-"}</td><td>{m.nextActionType||"-"}</td><td>{isClientRegistered(m)?<Badge tone="green">완료</Badge>:<Badge tone="amber">미등록</Badge>}</td><td><button className="small-btn" onClick={()=>openDetail(m.id)}>열기</button></td></tr>})}</tbody></table></div></div></>
}

function Schedule({db,update,addHistory,openDetail}:{db:DemoDB;update:UpdateFn;addHistory:HistoryFn;openDetail:(id:string)=>void}){
  const [range,setRange]=useState("14");
  const end=new Date();end.setDate(end.getDate()+Number(range));const endStr=end.toISOString().slice(0,10);
  const matters=db.matters.filter(m=>m.nextActionAt&&m.nextActionAt<=endStr&&!terminalStatuses.includes(m.status)).sort((a,b)=>a.nextActionAt.localeCompare(b.nextActionAt));
  const payments=db.payments.filter(p=>p.status!=="완료"&&p.status!=="취소"&&p.dueDate<=endStr).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));
  const cases=db.cases.filter(c=>c.nextDueAt&&c.nextDueAt<=endStr).sort((a,b)=>(a.nextDueAt||"").localeCompare(b.nextDueAt||""));
  const patchMatter=(m:Matter,pp:Partial<Matter>)=>{const c=db.clients.find(x=>x.id===m.clientId);update(d=>({...d,matters:d.matters.map(x=>x.id===m.id?{...x,...pp}:x),history:[addHistory("일정","수정",c?.name||"고객","다음 액션 수정"),...d.history]}))};
  const items=[...matters.map(m=>({kind:"상담" as const,date:m.nextActionAt,id:m.id,matter:m})),...payments.map(p=>({kind:"입금" as const,date:p.dueDate,id:p.id,payment:p})),...cases.map(cs=>({kind:"사건" as const,date:cs.nextDueAt||"",id:cs.id,caseProgress:cs}))].sort((a,b)=>a.date.localeCompare(b.date));
  return <><PageHead title="오늘의 일정" desc="상담·입금·사건기한을 카드로 나누지 않고 하나의 일정 게시판에서 날짜순으로 확인합니다."/><div className="toolbar"><select value={range} onChange={e=>setRange(e.target.value)}><option value="0">오늘</option><option value="7">7일</option><option value="14">14일</option><option value="30">30일</option></select><span className="count">상담 {matters.length} · 입금 {payments.length} · 사건기한 {cases.length}</span></div><div className="table-card"><div className="table-scroll"><table className="schedule-board"><thead><tr><th>구분</th><th>일자</th><th>의뢰인</th><th>사건유형</th><th>내용</th><th>상태/금액</th><th>관리</th></tr></thead><tbody>{items.length?items.map(item=>{if(item.kind==="상담"){const m=item.matter;const c=db.clients.find(x=>x.id===m.clientId);return <tr key={`m-${m.id}`} className={m.nextActionAt<today()?"overdue-row":""}><td><Badge tone="blue">상담</Badge></td><td><input className="board-date" type="date" value={m.nextActionAt} onChange={e=>patchMatter(m,{nextActionAt:e.target.value})}/></td><td><b>{c?.name}</b></td><td>{m.caseType}</td><td><input className="board-input" value={m.nextActionType} onChange={e=>patchMatter(m,{nextActionType:e.target.value})}/></td><td><Badge tone={statusTone(m.status) as Tone}>{m.status}</Badge></td><td><button className="small-btn" onClick={()=>openDetail(m.id)}>열기</button></td></tr>}if(item.kind==="입금"){const p=item.payment;const m=db.matters.find(x=>x.id===p.matterId);const c=db.clients.find(x=>x.id===m?.clientId);return <tr key={`p-${p.id}`} className={p.dueDate<today()?"overdue-row":""}><td><Badge tone="amber">입금</Badge></td><td>{p.dueDate}</td><td><b>{c?.name}</b></td><td>{m?.caseType||"-"}</td><td>{p.memo||p.method}</td><td><b>{money(p.amount)}</b></td><td>-</td></tr>}const cs=item.caseProgress;const m=db.matters.find(x=>x.id===cs.matterId);const c=db.clients.find(x=>x.id===m?.clientId);return <tr key={`c-${cs.id}`} className={(cs.nextDueAt||"")<today()?"overdue-row":""}><td><Badge tone="purple">사건</Badge></td><td>{cs.nextDueAt||"-"}</td><td><b>{c?.name}</b></td><td>{m?.caseType||"-"}</td><td>{cs.currentStage} · {cs.court}</td><td>{cs.caseNumber||"사건번호 미등록"}</td><td>-</td></tr>}):<tr><td colSpan={7} className="empty-cell">선택 기간에 일정이 없습니다.</td></tr>}</tbody></table></div></div></>
}

function Contracts({db,update,addHistory}:{db:DemoDB;update:UpdateFn;addHistory:HistoryFn}){
  const [modal,setModal]=useState(false);const blank={matterId:"",contractDate:today(),contractAmount:0,paymentMethod:"단순분납" as PaymentMethod,upfrontAmount:0,installmentCount:1,eSignStatus:"미발송" as const,financeNoticeDone:false,memo:""};const [form,setForm]=useState(blank);
  const save=()=>{if(!form.matterId)return alert("상담건을 선택하세요.");const ct={...form,id:id("ct")};const m=db.matters.find(x=>x.id===form.matterId);const c=db.clients.find(x=>x.id===m?.clientId);update(d=>({...d,contracts:[ct,...d.contracts],matters:d.matters.map(x=>x.id===form.matterId?{...x,status:"계약진행중"}:x),history:[addHistory("계약","등록",c?.name||"고객",`${money(form.contractAmount)} 계약 등록`),...d.history]}));setModal(false);setForm(blank)};
  const patch=(ct:typeof db.contracts[number],pp:Partial<typeof ct>)=>{const m=db.matters.find(x=>x.id===ct.matterId);const c=db.clients.find(x=>x.id===m?.clientId);update(d=>({...d,contracts:d.contracts.map(x=>x.id===ct.id?{...x,...pp}:x),history:[addHistory("계약","수정",c?.name||"고객","계약정보 수정"),...d.history]}))};
  return <><PageHead title="계약 관리" desc="전자계약 상태, 수임료, 결제방식, 분납조건을 관리합니다." action={<button className="primary" onClick={()=>setModal(true)}><Plus size={17}/>계약 추가</button>}/><div className="table-card"><div className="table-scroll"><table><thead><tr><th>계약일</th><th>고객</th><th>사건유형</th><th>계약금액</th><th>선납금</th><th>결제방식</th><th>분납</th><th>전자계약</th><th>금융고지</th></tr></thead><tbody>{db.contracts.map(ct=>{const m=db.matters.find(x=>x.id===ct.matterId);const c=db.clients.find(x=>x.id===m?.clientId);return <tr key={ct.id}><td>{ct.contractDate}</td><td><b>{c?.name}</b></td><td>{m?.caseType}</td><td>{money(ct.contractAmount)}</td><td>{money(ct.upfrontAmount)}</td><td>{ct.paymentMethod}</td><td>{ct.installmentCount}회</td><td><select className="mini-select" value={ct.eSignStatus} onChange={e=>patch(ct,{eSignStatus:e.target.value as typeof ct.eSignStatus})}>{["미발송","서명대기","서명완료","취소"].map(x=><option key={x}>{x}</option>)}</select></td><td><button className={`toggle ${ct.financeNoticeDone?"on":""}`} onClick={()=>patch(ct,{financeNoticeDone:!ct.financeNoticeDone})}>{ct.financeNoticeDone?"완료":"미완료"}</button></td></tr>})}</tbody></table></div></div>{modal&&<Modal title="계약 추가" onClose={()=>setModal(false)}><div className="form-grid"><Field label="상담/고객" wide><select value={form.matterId} onChange={e=>setForm({...form,matterId:e.target.value})}><option value="">선택</option>{db.matters.map(m=><option key={m.id} value={m.id}>{db.clients.find(c=>c.id===m.clientId)?.name} · {m.caseType} · {m.status}</option>)}</select></Field><Field label="계약일"><input type="date" value={form.contractDate} onChange={e=>setForm({...form,contractDate:e.target.value})}/></Field><Field label="계약금액"><input type="number" value={form.contractAmount} onChange={e=>setForm({...form,contractAmount:+e.target.value})}/></Field><Field label="선납금"><input type="number" value={form.upfrontAmount} onChange={e=>setForm({...form,upfrontAmount:+e.target.value})}/></Field><Field label="결제방식"><select value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value as PaymentMethod})}>{paymentMethods.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="분납회차"><input type="number" min={1} value={form.installmentCount} onChange={e=>setForm({...form,installmentCount:+e.target.value})}/></Field><Field label="메모" wide><input value={form.memo} onChange={e=>setForm({...form,memo:e.target.value})}/></Field></div><ModalActions onCancel={()=>setModal(false)} onSave={save}/></Modal>}</>
}

function Payments({db,update,addHistory}:{db:DemoDB;update:UpdateFn;addHistory:HistoryFn}){
  const [modal,setModal]=useState(false);const blank={contractId:"",dueDate:today(),amount:0,method:"계좌이체" as PaymentMethod,memo:""};const [form,setForm]=useState(blank);
  const totalDue=db.payments.reduce((a,b)=>a+b.amount,0),totalPaid=db.payments.filter(x=>x.status==="완료").reduce((a,b)=>a+b.paidAmount,0);
  const patch=(p:Payment,pp:Partial<Payment>)=>{const m=db.matters.find(x=>x.id===p.matterId);const c=db.clients.find(x=>x.id===m?.clientId);update(d=>({...d,payments:d.payments.map(x=>x.id===p.id?{...x,...pp}:x),history:[addHistory("입금/분납","수정",c?.name||"고객","납부 일정 수정"),...d.history]}))};
  const save=()=>{const ct=db.contracts.find(x=>x.id===form.contractId);if(!ct)return alert("계약을 선택하세요.");const p:Payment={id:id("p"),matterId:ct.matterId,contractId:ct.id,dueDate:form.dueDate,amount:form.amount,paidAmount:0,status:"예정",method:form.method,memo:form.memo};const m=db.matters.find(x=>x.id===ct.matterId);const c=db.clients.find(x=>x.id===m?.clientId);update(d=>({...d,payments:[p,...d.payments],history:[addHistory("입금/분납","등록",c?.name||"고객",`${money(p.amount)} 납부일정 등록`),...d.history]}));setModal(false);setForm(blank)};
  return <><PageHead title="입금 / 분납" desc="계약별 납부예정, 완료, 연체와 실제 입금액을 테스트합니다." action={<button className="primary" onClick={()=>setModal(true)}><Plus size={17}/>납부 일정 추가</button>}/><div className="summary-strip"><span><b>예정 총액</b>{money(totalDue)}</span><span><b>실입금</b>{money(totalPaid)}</span><span><b>미수</b>{money(Math.max(0,totalDue-totalPaid))}</span><span><b>수납률</b>{Math.round(totalPaid/Math.max(1,totalDue)*100)}%</span></div><div className="table-card"><div className="table-scroll"><table><thead><tr><th>납부일</th><th>고객</th><th>금액</th><th>실입금</th><th>방식</th><th>상태</th><th>메모</th><th>작업</th></tr></thead><tbody>{db.payments.slice().sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).map(p=>{const m=db.matters.find(x=>x.id===p.matterId);const c=db.clients.find(x=>x.id===m?.clientId);const autoOverdue=p.status==="예정"&&p.dueDate<today();return <tr key={p.id} className={autoOverdue?"overdue-row":""}><td>{p.dueDate}</td><td><b>{c?.name}</b><small>{m?.caseType}</small></td><td>{money(p.amount)}</td><td>{money(p.paidAmount)}</td><td>{p.method}</td><td><select className="mini-select" value={autoOverdue?"연체":p.status} onChange={e=>patch(p,{status:e.target.value as PaymentStatus})}>{["예정","완료","연체","취소"].map(x=><option key={x}>{x}</option>)}</select></td><td>{p.memo||"-"}</td><td>{p.status!=="완료"?<button className="small-btn success" onClick={()=>patch(p,{status:"완료",paidAmount:p.amount,paidDate:today()})}><CheckCircle2 size={14}/>입금완료</button>:<Badge tone="green">{p.paidDate}</Badge>}</td></tr>})}</tbody></table></div></div>{modal&&<Modal title="납부 일정 추가" onClose={()=>setModal(false)}><div className="form-grid"><Field label="계약"><select value={form.contractId} onChange={e=>setForm({...form,contractId:e.target.value})}><option value="">선택</option>{db.contracts.map(c=><option key={c.id} value={c.id}>{db.clients.find(x=>x.id===db.matters.find(m=>m.id===c.matterId)?.clientId)?.name} · {money(c.contractAmount)}</option>)}</select></Field><Field label="납부예정일"><input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></Field><Field label="금액"><input type="number" value={form.amount} onChange={e=>setForm({...form,amount:+e.target.value})}/></Field><Field label="결제방식"><select value={form.method} onChange={e=>setForm({...form,method:e.target.value as PaymentMethod})}>{paymentMethods.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="메모" wide><input value={form.memo} onChange={e=>setForm({...form,memo:e.target.value})}/></Field></div><ModalActions onCancel={()=>setModal(false)} onSave={save}/></Modal>}</>
}

function ensureDocs(db:DemoDB,matterId:string){if(db.documents.some(x=>x.matterId===matterId))return db.documents;return [...db.documents,...defaultChecklist.map(x=>({id:id("doc"),matterId,no:x[0],title:x[1],source:x[2],condition:x[3],status:"미수령" as DocStatus,note:""}))]}
function Documents({db,update,addHistory}:{db:DemoDB;update:UpdateFn;addHistory:HistoryFn}){
  const candidateClients=db.clients.filter(c=>db.matters.some(m=>m.clientId===c.id&&isClientRegistered(m))).sort((a,b)=>a.name.localeCompare(b.name,"ko"));
  const [clientId,setClientId]=useState(candidateClients[0]?.id||"");
  const clientMatters=db.matters.filter(m=>m.clientId===clientId&&isClientRegistered(m)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  const m=clientMatters.find(mm=>db.documents.some(d=>d.matterId===mm.id))||clientMatters[0];
  const matterId=m?.id||"";const c=db.clients.find(x=>x.id===clientId);const docs=db.documents.filter(x=>x.matterId===matterId).sort((a,b)=>a.no-b.no);const pct=matterId?docCompletion(db,matterId):0;
  const init=()=>{if(!matterId)return;update(d=>({...d,documents:ensureDocs(d,matterId),history:[addHistory("서류수합","등록",c?.name||"고객","기본 서류체크리스트 생성"),...d.history]}))};
  const patch=(doc:typeof docs[number],status:DocStatus)=>update(d=>({...d,documents:d.documents.map(x=>x.id===doc.id?{...x,status,receivedAt:status==="수령"?today():undefined}:x),history:[addHistory("서류수합","수정",c?.name||"고객",`${doc.title} → ${status}`),...d.history]}));
  return <><PageHead title="서류 수합" desc="사건번호를 찾는 대신 의뢰인을 선택하면 해당 의뢰인의 현재 서류 체크리스트를 바로 불러옵니다."/><div className="document-toolbar"><Field label="의뢰인 선택"><select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">의뢰인 선택</option>{candidateClients.map(cc=><option key={cc.id} value={cc.id}>{cc.name} · {cc.phone||"연락처 없음"}</option>)}</select></Field><div className="document-context"><span>적용 사건</span><b>{m?`${m.caseType} · ${m.status}`:"선택된 사건 없음"}</b></div>{docs.length?<div className="document-progress-inline"><span>수합률</span><Progress value={pct}/><b>{docs.filter(x=>x.status==="수령"||x.status==="해당없음").length}/{docs.length} · {pct}%</b></div>:matterId?<button className="primary" onClick={init}><Plus size={16}/>체크리스트 생성</button>:null}</div>{docs.length?<div className="table-card"><div className="table-scroll"><table className="documents-board"><thead><tr><th>No.</th><th>준비서류</th><th>발급/출처</th><th>조건·안내</th><th>상태</th><th>수령일</th></tr></thead><tbody>{docs.map(doc=><tr key={doc.id}><td>{doc.no}</td><td><b>{doc.title}</b></td><td>{doc.source}</td><td>{doc.condition}</td><td><select className="mini-select" value={doc.status} onChange={e=>patch(doc,e.target.value as DocStatus)}>{["미수령","요청","수령","보완필요","해당없음"].map(x=><option key={x}>{x}</option>)}</select></td><td>{doc.receivedAt||"-"}</td></tr>)}</tbody></table></div></div>:<Empty text={clientId?"아직 체크리스트가 없습니다.":"의뢰인을 선택하세요."}/>}</>
}

const rehabStages=["수임완료","서류수합","서류검토","법원접수","금지/중지명령","보정","개시결정","채권자집회","인가","변제진행","종결"];
const bankruptcyStages=["수임완료","서류수합","서류검토","법원접수","보정","파산선고","면책심리","면책결정","종결"];
function Cases({db,update,addHistory}:{db:DemoDB;update:UpdateFn;addHistory:HistoryFn}){
  const [modal,setModal]=useState(false);const eligible=db.matters.filter(m=>!db.cases.some(c=>c.matterId===m.id)&&["수임","진행중","서류검토중"].includes(m.status));const [matterId,setMatterId]=useState("");
  const [expanded,setExpanded]=useState<string[]>([]);
  const toggle=(caseId:string)=>setExpanded(v=>v.includes(caseId)?v.filter(x=>x!==caseId):[...v,caseId]);
  const add=()=>{if(!matterId)return;const cs:CaseProgress={id:id("case"),matterId,currentStage:"수임완료",court:"미지정",caseNumber:"",nextDueAt:"",memo:"",updatedAt:new Date().toISOString()};const m=db.matters.find(x=>x.id===matterId);const c=db.clients.find(x=>x.id===m?.clientId);update(d=>({...d,cases:[cs,...d.cases],history:[addHistory("사건진행","등록",c?.name||"고객","사건진행 등록"),...d.history]}));setModal(false);setMatterId("");setExpanded(v=>[cs.id,...v])};
  const patch=(cs:CaseProgress,pp:Partial<CaseProgress>)=>{const m=db.matters.find(x=>x.id===cs.matterId);const c=db.clients.find(x=>x.id===m?.clientId);update(d=>({...d,cases:d.cases.map(x=>x.id===cs.id?{...x,...pp,updatedAt:new Date().toISOString()}:x),matters:pp.currentStage?d.matters.map(x=>x.id===cs.matterId?{...x,status:pp.currentStage==="종결"?"종결(성공)":"진행중"}:x):d.matters,history:[addHistory("사건진행","수정",c?.name||"고객",pp.currentStage?`단계 → ${pp.currentStage}`:"사건정보 수정"),...d.history]}))};
  return <><PageHead title="사건 진행" desc="기본 화면은 게시판 목록만 보여주고, 우측 펼치기 버튼을 눌렀을 때만 진행단계·법원·사건번호·기한을 표시합니다." action={<button className="primary" disabled={!eligible.length} onClick={()=>setModal(true)}><Plus size={17}/>사건 등록</button>}/><div className="table-card"><div className="table-scroll"><table className="cases-board"><thead><tr><th>의뢰인</th><th>사건유형</th><th>담당자</th><th>최근수정</th><th className="expand-col">상세</th></tr></thead><tbody>{db.cases.map(cs=>{const m=db.matters.find(x=>x.id===cs.matterId);const c=db.clients.find(x=>x.id===m?.clientId);const stages=m?.caseType==="개인파산"?bankruptcyStages:rehabStages;const idx=Math.max(0,stages.indexOf(cs.currentStage));const open=expanded.includes(cs.id);return <Fragment key={cs.id}>
    <tr className={open?"case-main-row open":"case-main-row"}><td><b>{c?.name}</b><small>{c?.phone||"-"}</small></td><td>{m?.caseType||"-"}</td><td>{m?.assignedTo||"-"}</td><td>{new Date(cs.updatedAt).toLocaleString("ko-KR")}</td><td className="expand-col"><button className="expand-btn" onClick={()=>toggle(cs.id)} aria-label={open?"상세 접기":"상세 펼치기"}>{open?<ChevronUp size={18}/>:<ChevronDown size={18}/>}</button></td></tr>
    {open&&<tr key={`${cs.id}-detail`} className="case-detail-row"><td colSpan={5}><div className="case-expand"><div className="stage-track board-stage">{stages.map((stage,i)=><div key={stage} className={i<=idx?"done":""}><i/><span>{stage}</span></div>)}</div><div className="case-fields board-fields"><Field label="현재 단계"><select value={cs.currentStage} onChange={e=>patch(cs,{currentStage:e.target.value})}>{stages.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="관할 법원"><input value={cs.court} onChange={e=>patch(cs,{court:e.target.value})}/></Field><Field label="사건번호"><input value={cs.caseNumber} onChange={e=>patch(cs,{caseNumber:e.target.value})}/></Field><Field label="다음 기한"><input type="date" value={cs.nextDueAt||""} onChange={e=>patch(cs,{nextDueAt:e.target.value})}/></Field><Field label="진행 메모" wide><input value={cs.memo} onChange={e=>patch(cs,{memo:e.target.value})}/></Field></div></div></td></tr>}
  </Fragment>})}</tbody></table></div></div>{modal&&<Modal title="사건 등록" onClose={()=>setModal(false)}><Field label="의뢰인 선택"><select value={matterId} onChange={e=>setMatterId(e.target.value)}><option value="">의뢰인 선택</option>{eligible.map(m=><option key={m.id} value={m.id}>{db.clients.find(c=>c.id===m.clientId)?.name} · {m.caseType}</option>)}</select></Field><ModalActions onCancel={()=>setModal(false)} onSave={add}/></Modal>}</>
}

function Analytics({db}:{db:DemoDB}){
  const total=db.matters.length;const consulted=db.matters.filter(m=>!["신규접수","상담예정","부재중"].includes(m.status)).length;const retained=db.matters.filter(m=>["수임","진행중","종결(성공)"].includes(m.status)).length;const firstContact=db.matters.filter(m=>m.firstContactDone).length;const contractAmount=db.contracts.reduce((a,b)=>a+b.contractAmount,0);const paid=db.payments.filter(p=>p.status==="완료").reduce((a,b)=>a+b.paidAmount,0);const withDocs=new Set(db.documents.map(d=>d.matterId));const fullDocs=[...withDocs].filter(mid=>docCompletion(db,mid)===100).length;
  const metrics=[["DB → 상담 전환율",total?consulted/total*100:0,50],["상담 → 수임 전환율",consulted?retained/consulted*100:0,20],["1차 연락 처리율",total?firstContact/total*100:0,70],["서류수합 완료율",withDocs.size?fullDocs/withDocs.size*100:0,80]] as const;
  const byType=matterTypes.map(t=>[t,db.matters.filter(m=>m.caseType===t).length] as const);
  return <><PageHead title="데이터 집계" desc="상담 퍼널, 사건유형, 계약·수금, 서류수합 현황을 데모 데이터로 계산합니다."/><div className="analytics-grid"><section className="panel"><h3>핵심 KPI</h3><div className="metric-list">{metrics.map(([name,value,target])=><div className="metric" key={name}><div><b>{name}</b><span>현재 {Math.round(value)}% · 데모 목표 {target}%</span></div><div className="metric-bar"><i style={{width:`${Math.min(100,value)}%`}}/><u style={{left:`${target}%`}}/></div></div>)}</div></section><section className="panel"><h3>재무 요약</h3><div className="finance-big"><span><b>계약 총액</b><strong>{money(contractAmount)}</strong></span><span><b>실입금</b><strong>{money(paid)}</strong></span><span><b>미수금</b><strong>{money(Math.max(0,contractAmount-paid))}</strong></span><span><b>수금률</b><strong>{Math.round(paid/Math.max(1,contractAmount)*100)}%</strong></span></div></section><section className="panel span2"><h3>사건유형 분포</h3><div className="bars">{byType.map(([s,n])=><div key={s}><span>{s}</span><div><i style={{width:`${Math.max(3,n/Math.max(1,total)*100)}%`}}/></div><b>{n}</b></div>)}</div></section></div></>
}

function CalculatorPage({db,update,addHistory,openDetail}:{db:DemoDB;update:UpdateFn;addHistory:HistoryFn;openDetail:(id:string)=>void}){
  const rehab=db.matters.filter(m=>m.caseType==="개인회생");const [matterId,setMatterId]=useState(rehab[0]?.id||"");const m=db.matters.find(x=>x.id===matterId);const c=db.clients.find(x=>x.id===m?.clientId);const calc=m?calcMatter(db,m):null;
  const patch=(pp:Partial<Matter>)=>{if(!m)return;update(d=>({...d,matters:d.matters.map(x=>x.id===m.id?{...x,...pp}:x),history:[addHistory("예상계산","수정",c?.name||"고객","계산 입력값 변경"),...d.history]}))};
  const [region,setRegion]=useState(Object.keys(db.settings.leasePriorityByRegion)[0]||"");
  return <><PageHead title="회생 예상계산기" desc="기존 상담시트의 가구원수·소득·공제·청산가치·채무 입력을 웹 계산기로 구현한 데모입니다."/>{m&&calc?<div className="calculator-layout"><section className="panel"><div className="panel-head"><div><h3>{c?.name} · {m.caseType}</h3><p>기준연도 {db.settings.referenceYear} · 기준값은 DEMO 설정</p></div><button className="small-btn" onClick={()=>openDetail(m.id)}>상세 열기</button></div><Field label="상담건 선택"><select value={matterId} onChange={e=>setMatterId(e.target.value)}>{rehab.map(mm=><option key={mm.id} value={mm.id}>{db.clients.find(cc=>cc.id===mm.clientId)?.name} · {mm.status}</option>)}</select></Field><div className="form-grid calc-inputs"><Field label="가구원수"><input type="number" min={1} max={6} value={m.householdSize} onChange={e=>patch({householdSize:+e.target.value})}/></Field><Field label="변제개월수"><input type="number" min={1} value={m.repaymentMonths} onChange={e=>patch({repaymentMonths:+e.target.value})}/></Field><Field label="월 급여/사업소득"><input type="number" value={m.monthlyIncome} onChange={e=>patch({monthlyIncome:+e.target.value})}/></Field><Field label="부업소득"><input type="number" value={m.sideIncome} onChange={e=>patch({sideIncome:+e.target.value})}/></Field><Field label="연금소득"><input type="number" value={m.pensionIncome} onChange={e=>patch({pensionIncome:+e.target.value})}/></Field><Field label="기타공제금"><input type="number" value={m.extraDeduction} onChange={e=>patch({extraDeduction:+e.target.value})}/></Field></div></section><section className="panel calc-result"><div className="calc-disclaimer"><AlertTriangle size={18}/><span>상담용 추정치입니다. 최종 산정은 서류 검토 및 담당자 확인이 필요합니다.</span></div><div className="calc-cards"><span><b>최저생계비(데모)</b><strong>{money(calc.living)}</strong></span><span><b>월 가용소득</b><strong>{money(calc.disposable)}</strong></span><span><b>청산가치</b><strong>{money(calc.liquidation)}</strong></span><span><b>최종 월 변제금</b><strong>{money(calc.finalMonthly)}</strong></span><span><b>최종 총변제액</b><strong>{money(calc.finalTotal)}</strong></span><span><b>예상 탕감액</b><strong>{money(calc.relief)}</strong></span><span><b>예상 탕감률</b><strong>{calc.reliefRate.toFixed(1)}%</strong></span><span><b>상담 참고판정</b><strong>{calc.recommendation}</strong></span></div><div className="calc-note"><b>청산가치 보장</b><span>{calc.liquidationSatisfied?"가용소득 기준 총변제액이 청산가치 이상":"청산가치 기준으로 보정 필요"}</span></div></section><section className="panel"><h3>상담 가이드 도구</h3><div className="quick-tools"><div><b>세금·건보 50% 참고 계산</b><span>세금·건보 합계 {money(calc.taxHealth)} × 50% = <strong>{money(calc.taxPriorityLimit)}</strong></span></div><div><b>소액임차인 참고값 DEMO</b><select value={region} onChange={e=>setRegion(e.target.value)}>{Object.keys(db.settings.leasePriorityByRegion).map(r=><option key={r}>{r}</option>)}</select><span>선택지역 데모 참고액: <strong>{money(db.settings.leasePriorityByRegion[region]||0)}</strong></span></div></div></section></div>:<Empty text="개인회생 상담건이 없습니다."/>}</>
}

function SettingsPage({db,update,addHistory}:{db:DemoDB;update:UpdateFn;addHistory:HistoryFn}){
  const patchLiving=(key:string,val:number)=>update(d=>({...d,settings:{...d.settings,livingCostByHousehold:{...d.settings.livingCostByHousehold,[key]:val}},history:[addHistory("설정","수정",`${key}인가구`,`기준금액 → ${money(val)}`),...d.history]}));
  const patchLease=(key:string,val:number)=>update(d=>({...d,settings:{...d.settings,leasePriorityByRegion:{...d.settings.leasePriorityByRegion,[key]:val}},history:[addHistory("설정","수정",key,`임차보증금 참고액 → ${money(val)}`),...d.history]}));
  const [newStaff,setNewStaff]=useState("");
  const addStaff=()=>{if(!newStaff.trim())return;update(d=>({...d,settings:{...d.settings,staffOptions:[...new Set([...d.settings.staffOptions,newStaff.trim()])]},history:[addHistory("설정","등록",newStaff.trim(),"담당자 옵션 추가"),...d.history]}));setNewStaff("")};
  return <><PageHead title="기준표 / 설정" desc="구글시트의 숨김 설정 탭 역할. 모든 숫자는 DEMO 값이며 실사용 전 공식 기준 검증·교체가 필요합니다."/><div className="settings-grid"><section className="panel"><div className="panel-head"><div><h3>가구원수별 기준금액</h3><p>자동계산의 최저생계비 DEMO 기준</p></div><Badge tone="amber">DEMO</Badge></div><div className="setting-rows">{Object.entries(db.settings.livingCostByHousehold).map(([k,v])=><label key={k}><span>{k}인가구</span><input type="number" value={v} onChange={e=>patchLiving(k,+e.target.value)}/></label>)}</div></section><section className="panel"><div className="panel-head"><div><h3>소액임차인 참고값</h3><p>기능 테스트용 샘플. 실제 법률기준이 아님.</p></div><Badge tone="red">실사용 금지</Badge></div><div className="setting-rows">{Object.entries(db.settings.leasePriorityByRegion).map(([k,v])=><label key={k}><span>{k}</span><input type="number" value={v} onChange={e=>patchLease(k,+e.target.value)}/></label>)}</div></section><section className="panel"><h3>담당자 옵션</h3><div className="tag-list">{db.settings.staffOptions.map(s=><Badge key={s} tone="blue">{s}</Badge>)}</div><div className="inline-add"><input value={newStaff} onChange={e=>setNewStaff(e.target.value)} placeholder="데모 담당자명"/><button className="small-btn" onClick={addStaff}><Plus size={14}/>추가</button></div></section><section className="panel"><h3>상담상태 목록</h3><div className="tag-list">{db.settings.pipelineStatuses.map(s=><Badge key={s} tone={statusTone(s) as Tone}>{s}</Badge>)}</div><p className="muted">v2 데모에서는 상태 순서/문구를 코드 기준으로 고정하고, 향후 DB형 설정으로 확장할 수 있습니다.</p></section></div></>
}

function HistoryPage({db}:{db:DemoDB}){const [q,setQ]=useState("");const rows=db.history.filter(h=>!q||`${h.category} ${h.target} ${h.detail}`.toLowerCase().includes(q.toLowerCase()));return <><PageHead title="기간별 변동내역" desc="데모에서 수행한 등록·수정·삭제 작업을 자동 기록합니다."/><div className="toolbar"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="변동내역 검색"/></div><span className="count">{rows.length}건</span></div><div className="timeline">{rows.map(h=><div className="timeline-item" key={h.id}><div className="time-dot"/><div><span>{new Date(h.createdAt).toLocaleString("ko-KR")}</span><h4>{h.target} <Badge tone={h.action==="삭제"?"red":h.action==="등록"?"green":"blue"}>{h.action}</Badge></h4><p>{h.category} · {h.detail}</p></div></div>)}</div></>}
function Board({db,update,addHistory}:{db:DemoDB;update:UpdateFn;addHistory:HistoryFn}){const [modal,setModal]=useState(false);const [title,setTitle]=useState("");const [body,setBody]=useState("");const save=()=>{if(!title)return;const post:BoardPost={id:id("b"),createdAt:new Date().toISOString(),title,body,pinned:false};update(d=>({...d,board:[post,...d.board],history:[addHistory("내부게시판","등록",title,"게시글 작성"),...d.history]}));setModal(false);setTitle("");setBody("")};return <><PageHead title="내부 게시판" desc="데모 운영 공지와 업무 메모를 등록할 수 있습니다." action={<button className="primary" onClick={()=>setModal(true)}><Plus size={17}/>글쓰기</button>}/><div className="board-list">{db.board.slice().sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.createdAt.localeCompare(a.createdAt)).map(p=><article key={p.id}><div>{p.pinned&&<Badge tone="purple">공지</Badge>}<h3>{p.title}</h3><p>{p.body}</p></div><time>{dateLabel(p.createdAt)}</time></article>)}</div>{modal&&<Modal title="게시글 작성" onClose={()=>setModal(false)}><div className="form-grid"><Field label="제목" wide><input value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="내용" wide><textarea rows={6} value={body} onChange={e=>setBody(e.target.value)}/></Field></div><ModalActions onCancel={()=>setModal(false)} onSave={save}/></Modal>}</>}

const detailTabs=["요약","인적사항","소득","재산","채무","예상변제","상담내역","계약","입금","서류","사건진행"] as const;
type DetailTab=typeof detailTabs[number];
function ClientDetail({db,matter,update,addHistory,onClose,onPrint}:{db:DemoDB;matter:Matter;update:UpdateFn;addHistory:HistoryFn;onClose:()=>void;onPrint:()=>void}){
  const [tab,setTab]=useState<DetailTab>("요약");const client=db.clients.find(x=>x.id===matter.clientId)!;const calc=calcMatter(db,matter);
  const patchClient=(pp:Partial<Client>)=>update(d=>({...d,clients:d.clients.map(x=>x.id===client.id?{...x,...pp}:x),history:[addHistory("고객관리","수정",client.name,"인적사항 수정"),...d.history]}));
  const patchMatter=(pp:Partial<Matter>)=>update(d=>({...d,matters:d.matters.map(x=>x.id===matter.id?{...x,...pp}:x),history:[addHistory("상담관리","수정",client.name,pp.status?`상태 → ${pp.status}`:"상담정보 수정"),...d.history]}));
  const guideKey=tab==="인적사항"?"profile":tab==="소득"?"income":tab==="재산"?"assets":tab==="채무"?"debts":tab==="예상변제"?"calc":null;
  return <Modal title={`${client.name} · ${matter.caseType}`} onClose={onClose} wide extra={<button className="secondary" onClick={onPrint}><Printer size={15}/>상담카드 인쇄</button>}><div className="detail-top"><div><Badge tone={statusTone(matter.status) as Tone}>{matter.status}</Badge><span>{client.phone||"연락처 미입력"} · {matter.assignedTo} · 접수 {dateLabel(matter.createdAt)}</span></div><select value={matter.status} onChange={e=>patchMatter({status:e.target.value as MatterStatus})}>{matterStatuses.map(s=><option key={s}>{s}</option>)}</select></div><div className="detail-tabs">{detailTabs.map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t}</button>)}</div><div className="detail-layout"><div className="detail-main">{tab==="요약"&&<SummaryTab db={db} matter={matter} client={client} calc={calc}/>} {tab==="인적사항"&&<ProfileTab client={client} patch={patchClient}/>} {tab==="소득"&&<IncomeTab matter={matter} patch={patchMatter}/>} {tab==="재산"&&<AssetsTab db={db} matter={matter} update={update} addHistory={addHistory} client={client}/>} {tab==="채무"&&<DebtsTab db={db} matter={matter} update={update} addHistory={addHistory} client={client}/>} {tab==="예상변제"&&<CalcTab db={db} matter={matter} patch={patchMatter}/>} {tab==="상담내역"&&<LogsTab db={db} matter={matter} update={update} addHistory={addHistory} client={client}/>} {tab==="계약"&&<ContractsTab db={db} matter={matter}/>} {tab==="입금"&&<PaymentsTab db={db} matter={matter}/>} {tab==="서류"&&<DocsTab db={db} matter={matter} update={update} addHistory={addHistory} client={client}/>} {tab==="사건진행"&&<CaseTab db={db} matter={matter}/>}</div>{guideKey&&<aside className="guide-panel"><span className="eyebrow">상담 가이드</span><h3>{tab} 체크포인트</h3><ol>{consultationGuides[guideKey].map(x=><li key={x}>{x}</li>)}</ol>{tab==="예상변제"&&<div className="guide-warning"><AlertTriangle size={16}/>자동계산은 상담 참고용이며 최종 법률판단이 아닙니다.</div>}</aside>}</div></Modal>
}
function SummaryTab({db,matter,client,calc}:{db:DemoDB;matter:Matter;client:Client;calc:ReturnType<typeof calcMatter>}){const all=db.matters.filter(m=>m.clientId===client.id);return <div className="summary-detail"><div className="summary-cards"><span><b>다음액션</b><strong>{matter.nextActionAt||"미지정"}</strong><small>{matter.nextActionType||"-"}</small></span><span><b>월 총소득</b><strong>{money(calc.totalIncome)}</strong><small>{matter.occupationType}</small></span><span><b>신용채무</b><strong>{money(calc.unsecured)}</strong><small>탕감대상 참고</small></span><span><b>청산가치</b><strong>{money(calc.liquidation)}</strong><small>자산-담보</small></span><span><b>예상 월변제</b><strong>{matter.caseType==="개인회생"?money(calc.finalMonthly):"해당없음"}</strong><small>{calc.recommendation}</small></span><span><b>서류 수합</b><strong>{docCompletion(db,matter.id)}%</strong><small>{db.documents.filter(d=>d.matterId===matter.id).length}개 항목</small></span></div>{all.length>1&&<section className="subsection"><h3>동일 고객의 다른 상담/사건</h3>{all.map(m=><div className="linked-matter" key={m.id}><span>{dateLabel(m.createdAt)}</span><b>{m.caseType}</b><Badge tone={statusTone(m.status) as Tone}>{m.status}</Badge><small>{m.memo||"메모 없음"}</small></div>)}</section>}<section className="subsection"><h3>특이사항 / 메모</h3><p>{matter.specialIssue||"특이사항 없음"}</p><p className="muted">{matter.memo||"메모 없음"}</p></section></div>}
function ProfileTab({client,patch}:{client:Client;patch:(p:Partial<Client>)=>void}){return <div className="form-grid form-grid-3"><Field label="이름"><input value={client.name} onChange={e=>patch({name:e.target.value})}/></Field><Field label="연락처"><input value={client.phone} onChange={e=>patch({phone:e.target.value})}/></Field><Field label="생년월일"><input type="date" value={client.birthDate} onChange={e=>patch({birthDate:e.target.value})}/></Field><Field label="성별"><select value={client.gender} onChange={e=>patch({gender:e.target.value as Client["gender"]})}>{["미입력","남","여"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="거주지(초본주소)" wide><input value={client.address} onChange={e=>patch({address:e.target.value})}/></Field><Field label="배우자"><input value={client.spouse} onChange={e=>patch({spouse:e.target.value})}/></Field><Field label="자녀(인원/나이)"><input value={client.children} onChange={e=>patch({children:e.target.value})}/></Field><Field label="가구원수/부양가족"><input type="number" value={client.dependents} onChange={e=>patch({dependents:+e.target.value})}/></Field><Field label="중대질환/장기요양" wide><input value={client.healthIssue} onChange={e=>patch({healthIssue:e.target.value})}/></Field><Field label="고객 메모" wide><textarea value={client.memo} onChange={e=>patch({memo:e.target.value})}/></Field></div>}
function IncomeTab({matter,patch}:{matter:Matter;patch:(p:Partial<Matter>)=>void}){const total=matter.monthlyIncome+matter.sideIncome+matter.pensionIncome;return <div><div className="form-grid form-grid-3"><Field label="소득유형"><select value={matter.occupationType} onChange={e=>patch({occupationType:e.target.value as Matter["occupationType"]})}>{occupationTypes.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="회사명/사업자명"><input value={matter.companyName} onChange={e=>patch({companyName:e.target.value})}/></Field><Field label="재직기간/사업장정보"><input value={matter.employmentInfo} onChange={e=>patch({employmentInfo:e.target.value})}/></Field><Field label="월평균소득(최근3개월)"><input type="number" value={matter.monthlyIncome} onChange={e=>patch({monthlyIncome:+e.target.value})}/></Field><Field label="2중소득(부업)"><input type="number" value={matter.sideIncome} onChange={e=>patch({sideIncome:+e.target.value})}/></Field><Field label="연금소득"><input type="number" value={matter.pensionIncome} onChange={e=>patch({pensionIncome:+e.target.value})}/></Field></div><div className="result-banner"><span>월 총소득 <b>{money(total)}</b></span><span>연소득(단순 환산) <b>{money(total*12)}</b></span></div></div>}
function AssetsTab({db,matter,update,addHistory,client}:{db:DemoDB;matter:Matter;update:UpdateFn;addHistory:HistoryFn;client:Client}){const [form,setForm]=useState({type:assetTypes[0],value:0,securedAmount:0,note:""});const rows=db.assets.filter(x=>x.matterId===matter.id);const add=()=>{const a:AssetItem={id:id("a"),matterId:matter.id,...form};update(d=>({...d,assets:[...d.assets,a],history:[addHistory("재산","등록",client.name,`${a.type} ${money(a.value)}`),...d.history]}));setForm({type:assetTypes[0],value:0,securedAmount:0,note:""})};const del=(a:AssetItem)=>update(d=>({...d,assets:d.assets.filter(x=>x.id!==a.id),history:[addHistory("재산","삭제",client.name,a.type),...d.history]}));return <div><EditableListHeader title="재산 항목"/><div className="compact-table"><div className="compact-head"><span>항목</span><span>평가액</span><span>담보/대출</span><span>비고</span><i/></div>{rows.map(a=><div key={a.id}><span>{a.type}</span><b>{money(a.value)}</b><b>{money(a.securedAmount)}</b><span>{a.note||"-"}</span><button onClick={()=>del(a)}><Trash2 size={14}/></button></div>)}</div><div className="inline-form four"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{assetTypes.map(x=><option key={x}>{x}</option>)}</select><input type="number" value={form.value} onChange={e=>setForm({...form,value:+e.target.value})} placeholder="평가액"/><input type="number" value={form.securedAmount} onChange={e=>setForm({...form,securedAmount:+e.target.value})} placeholder="담보액"/><input value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="비고"/><button className="small-btn" onClick={add}><Plus size={14}/>추가</button></div></div>}
function DebtsTab({db,matter,update,addHistory,client}:{db:DemoDB;matter:Matter;update:UpdateFn;addHistory:HistoryFn;client:Client}){const [form,setForm]=useState({type:debtTypes[4],creditor:"",amount:0,note:""});const rows=db.debts.filter(x=>x.matterId===matter.id);const add=()=>{const a:DebtItem={id:id("d"),matterId:matter.id,...form};update(d=>({...d,debts:[...d.debts,a],history:[addHistory("채무","등록",client.name,`${a.type} ${money(a.amount)}`),...d.history]}));setForm({type:debtTypes[4],creditor:"",amount:0,note:""})};const del=(a:DebtItem)=>update(d=>({...d,debts:d.debts.filter(x=>x.id!==a.id),history:[addHistory("채무","삭제",client.name,a.creditor||a.type),...d.history]}));return <div><EditableListHeader title="채무 항목"/><div className="compact-table"><div className="compact-head"><span>구분</span><span>채권자/내용</span><span>금액</span><span>비고</span><i/></div>{rows.map(a=><div key={a.id}><span>{a.type}</span><b>{a.creditor||"-"}</b><b>{money(a.amount)}</b><span>{a.note||"-"}</span><button onClick={()=>del(a)}><Trash2 size={14}/></button></div>)}</div><div className="inline-form four"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{debtTypes.map(x=><option key={x}>{x}</option>)}</select><input value={form.creditor} onChange={e=>setForm({...form,creditor:e.target.value})} placeholder="채권자/내용"/><input type="number" value={form.amount} onChange={e=>setForm({...form,amount:+e.target.value})} placeholder="금액"/><input value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="비고"/><button className="small-btn" onClick={add}><Plus size={14}/>추가</button></div></div>}
function EditableListHeader({title}:{title:string}){return <div className="subsection-head"><h3>{title}</h3><span>행 추가 방식 · 데모</span></div>}
function CalcTab({db,matter,patch}:{db:DemoDB;matter:Matter;patch:(p:Partial<Matter>)=>void}){const x=calcMatter(db,matter);return <div><div className="calc-disclaimer"><AlertTriangle size={18}/><span>추정치이며 최종 산정은 담당자 검토가 필요합니다. 기준표는 DEMO 값입니다.</span></div><div className="form-grid form-grid-3"><Field label="가구원수"><input type="number" min={1} max={6} value={matter.householdSize} onChange={e=>patch({householdSize:+e.target.value})}/></Field><Field label="변제개월수"><input type="number" value={matter.repaymentMonths} onChange={e=>patch({repaymentMonths:+e.target.value})}/></Field><Field label="기타공제금"><input type="number" value={matter.extraDeduction} onChange={e=>patch({extraDeduction:+e.target.value})}/></Field></div><div className="calc-cards detail-calc"><span><b>월 총소득</b><strong>{money(x.totalIncome)}</strong></span><span><b>최저생계비</b><strong>{money(x.living)}</strong></span><span><b>월 가용소득</b><strong>{money(x.disposable)}</strong></span><span><b>총 자산</b><strong>{money(x.totalAssets)}</strong></span><span><b>청산가치</b><strong>{money(x.liquidation)}</strong></span><span><b>신용채무</b><strong>{money(x.unsecured)}</strong></span><span><b>최종 월변제금</b><strong>{money(x.finalMonthly)}</strong></span><span><b>최종 총변제액</b><strong>{money(x.finalTotal)}</strong></span><span><b>예상 탕감액</b><strong>{money(x.relief)}</strong></span><span><b>예상 탕감률</b><strong>{x.reliefRate.toFixed(1)}%</strong></span><span><b>진행가능여부</b><strong>{x.recommendation}</strong></span><span><b>청산가치 보장</b><strong>{x.liquidationSatisfied?"충족":"보정필요"}</strong></span></div></div>}
function LogsTab({db,matter,update,addHistory,client}:{db:DemoDB;matter:Matter;update:UpdateFn;addHistory:HistoryFn;client:Client}){const [body,setBody]=useState("");const [kind,setKind]=useState("상담");const logs=db.logs.filter(x=>x.matterId===matter.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));const add=()=>{if(!body.trim())return;const l:ConsultationLog={id:id("log"),matterId:matter.id,createdAt:new Date().toISOString(),author:matter.assignedTo,kind,body:body.trim()};update(d=>({...d,logs:[l,...d.logs],history:[addHistory("상담내역","등록",client.name,`${kind} 기록 추가`),...d.history]}));setBody("")};return <div><div className="log-compose"><select value={kind} onChange={e=>setKind(e.target.value)}><option>상담</option><option>통화</option><option>문자</option><option>서류</option><option>계약</option><option>사건</option></select><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="상담내용, 부재, 후속 요청 등을 시간순으로 기록"/><button className="primary" onClick={add}><Plus size={15}/>기록 추가</button></div><div className="log-timeline">{logs.map(l=><div key={l.id}><i/><time>{new Date(l.createdAt).toLocaleString("ko-KR")}</time><h4>{l.kind} · {l.author}</h4><p>{l.body}</p></div>)}</div></div>}
function ContractsTab({db,matter}:{db:DemoDB;matter:Matter}){const rows=db.contracts.filter(x=>x.matterId===matter.id);return rows.length?<div className="compact-table simple"><div className="compact-head"><span>계약일</span><span>수임료</span><span>결제</span><span>전자계약</span></div>{rows.map(x=><div key={x.id}><span>{x.contractDate}</span><b>{money(x.contractAmount)}</b><span>{x.paymentMethod} · {x.installmentCount}회</span><Badge tone={x.eSignStatus==="서명완료"?"green":"amber"}>{x.eSignStatus}</Badge></div>)}</div>:<Empty text="등록된 계약이 없습니다."/>}
function PaymentsTab({db,matter}:{db:DemoDB;matter:Matter}){const rows=db.payments.filter(x=>x.matterId===matter.id).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));return rows.length?<div className="compact-table simple"><div className="compact-head"><span>납부일</span><span>예정금액</span><span>실입금</span><span>상태</span></div>{rows.map(x=><div key={x.id}><span>{x.dueDate}</span><b>{money(x.amount)}</b><span>{money(x.paidAmount)}</span><Badge tone={x.status==="완료"?"green":x.status==="연체"?"red":"amber"}>{x.status}</Badge></div>)}</div>:<Empty text="등록된 납부일정이 없습니다."/>}
function DocsTab({db,matter,update,addHistory,client}:{db:DemoDB;matter:Matter;update:UpdateFn;addHistory:HistoryFn;client:Client}){const docs=db.documents.filter(x=>x.matterId===matter.id).sort((a,b)=>a.no-b.no);const init=()=>update(d=>({...d,documents:ensureDocs(d,matter.id),history:[addHistory("서류수합","등록",client.name,"기본 체크리스트 생성"),...d.history]}));const patch=(doc:typeof docs[number],status:DocStatus)=>update(d=>({...d,documents:d.documents.map(x=>x.id===doc.id?{...x,status,receivedAt:status==="수령"?today():undefined}:x),history:[addHistory("서류수합","수정",client.name,`${doc.title} → ${status}`),...d.history]}));return docs.length?<div className="detail-docs">{docs.map(doc=><div key={doc.id}><b>{doc.no}. {doc.title}</b><span>{doc.condition}</span><select value={doc.status} onChange={e=>patch(doc,e.target.value as DocStatus)}>{["미수령","요청","수령","보완필요","해당없음"].map(x=><option key={x}>{x}</option>)}</select></div>)}</div>:<button className="primary" onClick={init}><Plus size={15}/>기본 체크리스트 생성</button>}
function CaseTab({db,matter}:{db:DemoDB;matter:Matter}){const cs=db.cases.find(x=>x.matterId===matter.id);return cs?<div className="summary-cards"><span><b>현재단계</b><strong>{cs.currentStage}</strong></span><span><b>관할법원</b><strong>{cs.court}</strong></span><span><b>사건번호</b><strong>{cs.caseNumber||"미접수"}</strong></span><span><b>다음기한</b><strong>{cs.nextDueAt||"미지정"}</strong></span></div>:<Empty text="사건진행 보드가 아직 없습니다."/>}

function PrintSheet({db,matterId}:{db:DemoDB;matterId:string}){const m=db.matters.find(x=>x.id===matterId);if(!m)return null;const c=db.clients.find(x=>x.id===m.clientId);if(!c)return null;const x=calcMatter(db,m);const assets=db.assets.filter(a=>a.matterId===m.id);const debts=db.debts.filter(d=>d.matterId===m.id);const logs=db.logs.filter(l=>l.matterId===m.id).slice().sort((a,b)=>a.createdAt.localeCompare(b.createdAt));return <article className="print-sheet"><header><div><h1>개인회생 · 개인파산 상담일지</h1><p>DEMO · 상담용 출력</p></div><span>{m.caseType} / {m.status}</span></header><section className="print-grid"><div><b>이름</b>{c.name}</div><div><b>연락처</b>{c.phone}</div><div><b>생년월일</b>{c.birthDate}</div><div><b>거주지</b>{c.address}</div><div><b>담당자</b>{m.assignedTo}</div><div><b>상담일자</b>{m.consultDate||"-"}</div><div><b>다음액션</b>{m.nextActionAt} {m.nextActionType}</div><div><b>관할법원</b>{m.court}</div></section><h2>1. 인적사항 / 소득</h2><section className="print-grid"><div><b>배우자</b>{c.spouse||"-"}</div><div><b>자녀</b>{c.children||"-"}</div><div><b>가구원수</b>{m.householdSize}</div><div><b>직업</b>{m.occupationType}</div><div><b>월 총소득</b>{money(x.totalIncome)}</div><div><b>기타공제</b>{money(m.extraDeduction)}</div></section><h2>2. 재산현황</h2><table><thead><tr><th>항목</th><th>평가액</th><th>담보액</th><th>비고</th></tr></thead><tbody>{assets.map(a=><tr key={a.id}><td>{a.type}</td><td>{money(a.value)}</td><td>{money(a.securedAmount)}</td><td>{a.note}</td></tr>)}</tbody></table><h2>3. 채무현황</h2><table><thead><tr><th>구분</th><th>채권자/내용</th><th>금액</th><th>비고</th></tr></thead><tbody>{debts.map(a=><tr key={a.id}><td>{a.type}</td><td>{a.creditor}</td><td>{money(a.amount)}</td><td>{a.note}</td></tr>)}</tbody></table><h2>4. 변제계획 자동계산</h2><section className="print-grid"><div><b>최저생계비</b>{money(x.living)}</div><div><b>월 가용소득</b>{money(x.disposable)}</div><div><b>청산가치</b>{money(x.liquidation)}</div><div><b>최종 월변제금</b>{money(x.finalMonthly)}</div><div><b>예상 탕감액</b>{money(x.relief)}</div><div><b>예상 탕감률</b>{x.reliefRate.toFixed(1)}%</div></section><p className="print-warning">※ 본 계산은 DEMO 상담용 추정치이며 법적 최종 확정치가 아닙니다.</p><h2>5. 상담내역</h2>{logs.map(l=><div className="print-log" key={l.id}><b>{dateLabel(l.createdAt)} · {l.kind}</b><span>{l.body}</span></div>)}</article>}
