"use client";
import {Bell,Inbox,RefreshCcw,Search,X} from "lucide-react";
import {useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {today,useAdminStore} from "./store";
function kstDate(){return new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
export function Header(){
 const {db}=useAdminStore();const router=useRouter();const [noticeOpen,setNoticeOpen]=useState(false);const [q,setQ]=useState("");const [searchOpen,setSearchOpen]=useState(false);const t=today();
 const matches=useMemo(()=>q.trim()?db.clients.filter(c=>`${c.name} ${c.phone}`.toLowerCase().includes(q.trim().toLowerCase())).slice(0,8):[],[q,db.clients]);
 const unregistered=db.matters.filter(m=>!m.clientRegistered).length;
 const alerts=db.matters.filter(m=>m.clientRegistered&&m.nextActionDate&&m.nextActionDate<=t&&!(["종결(성공)","종결(중단)","거절","부적합"] as string[]).includes(m.status));
 function choose(id:string){setQ("");setSearchOpen(false);router.push(`/customers?client=${encodeURIComponent(id)}`)}
 return <header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-slate-200 bg-white/95 pl-16 pr-4 backdrop-blur lg:px-7">
  <div className="relative hidden w-full max-w-md md:block"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={q} onChange={e=>{setQ(e.target.value);setSearchOpen(true)}} onFocus={()=>setSearchOpen(true)} placeholder="의뢰인명 또는 전화번호 검색" className="h-9 w-full rounded-lg border border-slate-200 bg-slate-50 pl-9 pr-3 text-sm outline-none focus:border-blue-400 focus:bg-white focus:ring-2 focus:ring-blue-100"/>{searchOpen&&q.trim()&&<div className="absolute left-0 right-0 top-11 z-50 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-xl">{matches.length===0?<div className="px-4 py-6 text-center text-sm text-slate-400">일치하는 의뢰인이 없습니다.</div>:matches.map(c=><button key={c.id} onClick={()=>choose(c.id)} className="flex w-full items-center justify-between border-b border-slate-100 px-4 py-3 text-left last:border-0 hover:bg-blue-50"><div><div className="text-sm font-semibold">{c.name}</div><div className="text-xs text-slate-400">{c.phone}</div></div><span className="text-xs text-slate-500">{c.manager}</span></button>)}</div>}</div>
  <div className="ml-auto flex items-center gap-2">{unregistered>0&&<button type="button" onClick={()=>router.push("/leads")} className="new-db-alert-pulse flex h-9 items-center gap-2 rounded-lg border border-amber-300 bg-amber-50 px-2.5 text-left shadow-sm hover:bg-amber-100"><span className="relative grid size-5 place-items-center rounded-full bg-amber-500 text-white"><Inbox size={12}/></span><span className="hidden text-[11px] font-bold text-amber-950 sm:block">신규 상담 DB 확인</span><span className="rounded-full bg-amber-600 px-1.5 py-0.5 text-[10px] font-black text-white">{unregistered}</span></button>}
   <button onClick={()=>window.location.reload()} title="새로고침" className="grid size-9 place-items-center rounded-lg border border-slate-200 text-slate-500 hover:border-blue-200 hover:bg-blue-50 hover:text-blue-700"><RefreshCcw size={16}/></button>
   <div className="relative"><button onClick={()=>setNoticeOpen(v=>!v)} className="relative grid size-9 place-items-center rounded-lg border border-slate-200 text-slate-500 hover:border-blue-200 hover:bg-blue-50 hover:text-blue-700"><Bell size={17}/>{alerts.length>0&&<span className="absolute right-1 top-1 min-w-4 rounded-full bg-blue-600 px-1 text-center text-[9px] font-bold leading-4 text-white">{alerts.length>9?"9+":alerts.length}</span>}</button>{noticeOpen&&<div className="absolute right-0 top-11 z-50 w-[calc(100vw-24px)] max-w-[380px] overflow-hidden rounded-xl border border-slate-200 bg-white shadow-xl"><div className="flex items-center justify-between border-b border-slate-100 px-4 py-3"><div><div className="text-sm font-bold">업무 알림</div><div className="text-[11px] text-slate-400">오늘까지 확인할 일정 {alerts.length}건</div></div><button onClick={()=>setNoticeOpen(false)} className="grid size-7 place-items-center rounded-md text-slate-400 hover:bg-slate-100"><X size={15}/></button></div><div className="max-h-96 overflow-y-auto">{alerts.length===0?<div className="px-4 py-8 text-center text-sm text-slate-400">확인할 알림이 없습니다.</div>:alerts.map(m=>{const c=db.clients.find(x=>x.id===m.clientId);return <button key={m.id} onClick={()=>router.push(`/customers?client=${m.clientId}`)} className="block w-full border-b border-slate-100 px-4 py-3 text-left hover:bg-slate-50"><div className="flex justify-between gap-2"><b className="text-sm">{c?.name||"의뢰인"}</b><span className="text-xs font-semibold text-blue-700">{m.nextActionType||"확인"}</span></div><div className="mt-1 text-[11px] text-slate-400">{m.nextActionDate} · {m.status}</div></button>})}</div></div>}</div>
   <div className="ml-1 hidden text-right sm:block"><div className="text-xs font-semibold text-slate-800">{kstDate()}</div><div className="text-[11px] text-slate-400">KST</div></div>
  </div>
 </header>
}
