"use client";

import {useEffect,useMemo,useState} from "react";
import {
  Activity, AlertTriangle, BarChart3, Bell, BriefcaseBusiness, Building2, CalendarDays,
  ChevronDown, ChevronLeft, ChevronRight, ChevronUp, CircleDollarSign, ClipboardCheck,
  Clock3, CreditCard, Database, FileCheck2, FileSignature, History, Home, Inbox, Landmark,
  ListTodo, Menu, MessageSquareText, Plus, RefreshCw, Search, Settings, Sparkles, Users, WalletCards, X
} from "lucide-react";

const STORAGE_KEY="ropower-admin-demo-v1";
const TODAY="2026-09-19";
const managers=["김도윤","이서현","박지훈"];
const caseTypes=["개인회생","개인파산","워크아웃/기타","민사","형사","불법사채구제"];
const matterStatuses=["신규접수","상담예정","상담완료","재통화필요","고려중","서류검토중","계약진행중","수임","진행중","종결(성공)","거절","부적합","부재중","종결(중단)"];
const documentChecklist=[
  "인감증명서 20장","주민등록등본/초본","가족관계/혼인관계증명서","지방세 관련 서류","국세 완납증명서","소득금액증명원 최근 5년",
  "자동차등록원부","부동산 등기사항전부증명서","근로소득원천징수영수증 최근 2년","건강보험자격득실확인서","인감도장","신분증 앞·뒤",
  "재직증명서/사업자등록증/퇴직금·연금 자료","급여명세서 최근 1년/사업자 장부","급여입금내역 최근 1년/사업자 장부"
];

const seedClients=[
  {id:"c1",createdAt:"2026-09-19T09:10:00",name:"김민준",phone:"010-2451-8831",birthDate:"1988-04-11",gender:"남",address:"서울 송파구",manager:"김도윤",registered:true,spouse:"유",children:"1명",dependents:2,healthIssue:"",memo:"급여소득자"},
  {id:"c2",createdAt:"2026-09-19T09:45:00",name:"박서연",phone:"010-6712-3204",birthDate:"1992-09-23",gender:"여",address:"경기 성남시",manager:"이서현",registered:true,spouse:"무",children:"",dependents:1,healthIssue:"",memo:"사업소득 혼합"},
  {id:"c3",createdAt:"2026-09-19T10:12:00",name:"이준호",phone:"010-9082-1477",birthDate:"1985-02-03",gender:"남",address:"인천 남동구",manager:"박지훈",registered:true,spouse:"유",children:"2명",dependents:3,healthIssue:"",memo:"부동산 담보채무 있음"},
  {id:"c4",createdAt:"2026-09-19T11:02:00",name:"최유진",phone:"010-1160-7362",birthDate:"1995-12-16",gender:"여",address:"서울 강서구",manager:"김도윤",registered:false,spouse:"미입력",children:"",dependents:1,healthIssue:"",memo:"첫 통화 예정"},
  {id:"c5",createdAt:"2026-09-18T15:30:00",name:"정우성",phone:"010-7322-5541",birthDate:"1981-07-07",gender:"남",address:"경기 수원시",manager:"이서현",registered:true,spouse:"유",children:"1명",dependents:2,healthIssue:"",memo:"파산 상담"},
  {id:"c6",createdAt:"2026-09-18T14:18:00",name:"한지민",phone:"010-3981-0675",birthDate:"1990-11-30",gender:"여",address:"대전 서구",manager:"박지훈",registered:true,spouse:"무",children:"",dependents:1,healthIssue:"",memo:"재통화 요청"},
  {id:"c7",createdAt:"2026-09-17T16:22:00",name:"오세훈",phone:"010-5104-9926",birthDate:"1987-01-14",gender:"남",address:"충북 청주시",manager:"김도윤",registered:true,spouse:"유",children:"2명",dependents:3,healthIssue:"",memo:"서류 일부 수합"},
  {id:"c8",createdAt:"2026-09-17T13:10:00",name:"윤하늘",phone:"010-8250-4318",birthDate:"1998-05-19",gender:"여",address:"부산 해운대구",manager:"이서현",registered:true,spouse:"무",children:"",dependents:1,healthIssue:"",memo:"프리랜서"},
  {id:"c9",createdAt:"2026-09-16T10:40:00",name:"임재현",phone:"010-4420-7723",birthDate:"1983-08-02",gender:"남",address:"서울 영등포구",manager:"박지훈",registered:true,spouse:"유",children:"1명",dependents:2,healthIssue:"",memo:"수임 후 사건진행"},
  {id:"c10",createdAt:"2026-09-15T12:05:00",name:"백지우",phone:"010-6501-2144",birthDate:"1993-03-21",gender:"여",address:"경기 고양시",manager:"김도윤",registered:true,spouse:"무",children:"",dependents:1,healthIssue:"",memo:"워크아웃 비교"},
  {id:"c11",createdAt:"2026-09-19T13:20:00",name:"강현수",phone:"010-2201-6689",birthDate:"1989-06-11",gender:"남",address:"서울 마포구",manager:"이서현",registered:false,spouse:"미입력",children:"",dependents:1,healthIssue:"",memo:"온라인 광고 유입"},
  {id:"c12",createdAt:"2026-09-19T14:10:00",name:"조아라",phone:"010-7710-5519",birthDate:"1996-10-08",gender:"여",address:"경기 용인시",manager:"박지훈",registered:false,spouse:"미입력",children:"",dependents:1,healthIssue:"",memo:"카카오 상담 신청"}
];

const seedMatters=[
  {id:"m1",clientId:"c1",createdAt:"2026-09-19T09:10:00",caseType:"개인회생",status:"상담완료",source:"온라인 광고",manager:"김도윤",consultDate:"2026-09-19",nextActionDate:"2026-09-20",nextActionType:"서류 안내",occupation:"직장인",companyName:"에이치솔루션",monthlyIncome:3400000,sideIncome:0,pensionIncome:0,householdSize:2,extraDeduction:180000,repaymentMonths:36,court:"서울회생법원",memo:"채권자 7곳",clientRegistered:true},
  {id:"m2",clientId:"c2",createdAt:"2026-09-19T09:45:00",caseType:"개인회생",status:"계약진행중",source:"소개",manager:"이서현",consultDate:"2026-09-19",nextActionDate:"2026-09-19",nextActionType:"계약서 확인",occupation:"사업자",companyName:"더봄스튜디오",monthlyIncome:4200000,sideIncome:600000,pensionIncome:0,householdSize:1,extraDeduction:250000,repaymentMonths:36,court:"수원회생법원",memo:"사업장 매출 자료 필요",clientRegistered:true},
  {id:"m3",clientId:"c3",createdAt:"2026-09-19T10:12:00",caseType:"개인회생",status:"서류검토중",source:"검색",manager:"박지훈",consultDate:"2026-09-19",nextActionDate:"2026-09-22",nextActionType:"부동산 자료 보완",occupation:"직장인",companyName:"미래유통",monthlyIncome:5100000,sideIncome:0,pensionIncome:0,householdSize:3,extraDeduction:220000,repaymentMonths:36,court:"인천지방법원",memo:"담보부채 확인",clientRegistered:true},
  {id:"m4",clientId:"c4",createdAt:"2026-09-19T11:02:00",caseType:"개인회생",status:"신규접수",source:"메타 리드",manager:"김도윤",consultDate:"",nextActionDate:"2026-09-19",nextActionType:"첫 연락",occupation:"미입력",companyName:"",monthlyIncome:0,sideIncome:0,pensionIncome:0,householdSize:1,extraDeduction:0,repaymentMonths:36,court:"미지정",memo:"",clientRegistered:false},
  {id:"m5",clientId:"c5",createdAt:"2026-09-18T15:30:00",caseType:"개인파산",status:"상담완료",source:"지인소개",manager:"이서현",consultDate:"2026-09-18",nextActionDate:"2026-09-21",nextActionType:"파산 서류 점검",occupation:"무직",companyName:"",monthlyIncome:900000,sideIncome:0,pensionIncome:0,householdSize:2,extraDeduction:0,repaymentMonths:36,court:"수원회생법원",memo:"면책 가능성 별도 검토 필요",clientRegistered:true},
  {id:"m6",clientId:"c6",createdAt:"2026-09-18T14:18:00",caseType:"개인회생",status:"재통화필요",source:"블로그",manager:"박지훈",consultDate:"2026-09-18",nextActionDate:"2026-09-19",nextActionType:"재통화",occupation:"프리랜서",companyName:"",monthlyIncome:2900000,sideIncome:0,pensionIncome:0,householdSize:1,extraDeduction:120000,repaymentMonths:36,court:"대전지방법원",memo:"오후 5시 이후 통화",clientRegistered:true},
  {id:"m7",clientId:"c7",createdAt:"2026-09-17T16:22:00",caseType:"개인회생",status:"수임",source:"온라인 광고",manager:"김도윤",consultDate:"2026-09-17",nextActionDate:"2026-09-23",nextActionType:"미수령 서류 재안내",occupation:"직장인",companyName:"한빛테크",monthlyIncome:3800000,sideIncome:300000,pensionIncome:0,householdSize:3,extraDeduction:200000,repaymentMonths:36,court:"청주지방법원",memo:"계약 완료",clientRegistered:true},
  {id:"m8",clientId:"c8",createdAt:"2026-09-17T13:10:00",caseType:"개인회생",status:"고려중",source:"카카오",manager:"이서현",consultDate:"2026-09-17",nextActionDate:"2026-09-24",nextActionType:"의사 확인",occupation:"프리랜서",companyName:"",monthlyIncome:2600000,sideIncome:400000,pensionIncome:0,householdSize:1,extraDeduction:100000,repaymentMonths:36,court:"부산회생법원",memo:"비용 고민",clientRegistered:true},
  {id:"m9",clientId:"c9",createdAt:"2026-09-16T10:40:00",caseType:"개인회생",status:"진행중",source:"소개",manager:"박지훈",consultDate:"2026-09-16",nextActionDate:"2026-09-25",nextActionType:"보정권고 확인",occupation:"직장인",companyName:"케이로지스",monthlyIncome:4500000,sideIncome:0,pensionIncome:0,householdSize:2,extraDeduction:160000,repaymentMonths:36,court:"서울회생법원",memo:"접수 완료",clientRegistered:true},
  {id:"m10",clientId:"c10",createdAt:"2026-09-15T12:05:00",caseType:"워크아웃/기타",status:"상담완료",source:"검색",manager:"김도윤",consultDate:"2026-09-15",nextActionDate:"2026-09-22",nextActionType:"신복위 비교 안내",occupation:"직장인",companyName:"에코서비스",monthlyIncome:3100000,sideIncome:0,pensionIncome:0,householdSize:1,extraDeduction:0,repaymentMonths:36,court:"미지정",memo:"회생/워크아웃 비교",clientRegistered:true},
  {id:"m11",clientId:"c11",createdAt:"2026-09-19T13:20:00",caseType:"개인파산",status:"신규접수",source:"온라인 광고",manager:"이서현",consultDate:"",nextActionDate:"2026-09-19",nextActionType:"첫 연락",occupation:"미입력",companyName:"",monthlyIncome:0,sideIncome:0,pensionIncome:0,householdSize:1,extraDeduction:0,repaymentMonths:36,court:"미지정",memo:"",clientRegistered:false},
  {id:"m12",clientId:"c12",createdAt:"2026-09-19T14:10:00",caseType:"개인회생",status:"신규접수",source:"카카오 상담",manager:"박지훈",consultDate:"",nextActionDate:"2026-09-19",nextActionType:"첫 연락",occupation:"미입력",companyName:"",monthlyIncome:0,sideIncome:0,pensionIncome:0,householdSize:1,extraDeduction:0,repaymentMonths:36,court:"미지정",memo:"",clientRegistered:false}
];

const seedAssets=[
 {id:"a1",matterId:"m1",type:"예금/적금",value:1800000,securedAmount:0,note:""},{id:"a2",matterId:"m1",type:"자동차",value:8000000,securedAmount:3000000,note:""},
 {id:"a3",matterId:"m2",type:"임차보증금",value:30000000,securedAmount:0,note:""},{id:"a4",matterId:"m2",type:"예금/적금",value:4200000,securedAmount:0,note:""},
 {id:"a5",matterId:"m3",type:"주택/토지",value:220000000,securedAmount:160000000,note:"시세 추가확인"},{id:"a6",matterId:"m7",type:"퇴직금(1/2)",value:6200000,securedAmount:0,note:""},
 {id:"a7",matterId:"m9",type:"자동차",value:12000000,securedAmount:6000000,note:""}
];
const seedDebts=[
 {id:"d1",matterId:"m1",type:"신용채무",creditor:"A카드",amount:18000000,note:""},{id:"d2",matterId:"m1",type:"신용채무",creditor:"B저축은행",amount:24000000,note:""},{id:"d3",matterId:"m1",type:"세금체납",creditor:"국세",amount:1800000,note:""},
 {id:"d4",matterId:"m2",type:"신용채무",creditor:"C캐피탈",amount:33000000,note:""},{id:"d5",matterId:"m2",type:"개인채무",creditor:"지인",amount:9000000,note:""},
 {id:"d6",matterId:"m3",type:"담보채무",creditor:"D은행",amount:160000000,note:"부동산 담보"},{id:"d7",matterId:"m3",type:"신용채무",creditor:"E카드",amount:41000000,note:""},
 {id:"d8",matterId:"m5",type:"신용채무",creditor:"F은행",amount:78000000,note:""},{id:"d9",matterId:"m7",type:"신용채무",creditor:"G카드 외",amount:56000000,note:""},
 {id:"d10",matterId:"m9",type:"신용채무",creditor:"H저축은행 외",amount:69000000,note:""}
];
const seedContracts=[
 {id:"ct1",matterId:"m7",contractDate:"2026-09-17",amount:2200000,upfrontAmount:500000,installmentCount:4,paymentMethod:"카드/계좌",status:"계약완료",paymentMethodRegistered:true},
 {id:"ct2",matterId:"m9",contractDate:"2026-09-16",amount:2600000,upfrontAmount:800000,installmentCount:3,paymentMethod:"카드",status:"계약완료",paymentMethodRegistered:true},
 {id:"ct3",matterId:"m2",contractDate:"2026-09-19",amount:2400000,upfrontAmount:600000,installmentCount:4,paymentMethod:"카드",status:"서명대기",paymentMethodRegistered:false}
];
const seedPayments=[
 {id:"p1",matterId:"m7",dueDate:"2026-09-17",amount:500000,paidAmount:500000,paidDate:"2026-09-17",status:"완료",method:"카드",installmentNo:1,taxInvoiceStatus:"발행"},
 {id:"p2",matterId:"m7",dueDate:"2026-09-24",amount:425000,paidAmount:0,paidDate:"",status:"예정",method:"카드",installmentNo:2,taxInvoiceStatus:"미발행"},
 {id:"p3",matterId:"m7",dueDate:"2026-10-24",amount:425000,paidAmount:0,paidDate:"",status:"예정",method:"카드",installmentNo:3,taxInvoiceStatus:"미발행"},
 {id:"p4",matterId:"m9",dueDate:"2026-09-16",amount:800000,paidAmount:800000,paidDate:"2026-09-16",status:"완료",method:"카드",installmentNo:1,taxInvoiceStatus:"발행"},
 {id:"p5",matterId:"m9",dueDate:"2026-09-30",amount:600000,paidAmount:0,paidDate:"",status:"예정",method:"카드",installmentNo:2,taxInvoiceStatus:"미발행"},
 {id:"p6",matterId:"m2",dueDate:"2026-09-19",amount:600000,paidAmount:0,paidDate:"",status:"실패",method:"카드",installmentNo:1,taxInvoiceStatus:"미발행",failReason:"결제수단 미등록"},
 {id:"p7",matterId:"m1",dueDate:"2026-09-12",amount:440000,paidAmount:0,paidDate:"",status:"연체",method:"카드",installmentNo:2,taxInvoiceStatus:"미발행",failReason:"한도초과"},
 {id:"p8",matterId:"m6",dueDate:"2026-09-05",amount:330000,paidAmount:0,paidDate:"",status:"연체",method:"가상계좌",installmentNo:2,taxInvoiceStatus:"미발행",failReason:"미입금"},
 {id:"p9",matterId:"m5",dueDate:"2026-08-28",amount:550000,paidAmount:0,paidDate:"",status:"연체",method:"카드",installmentNo:3,taxInvoiceStatus:"미발행",failReason:"결제실패"},
 {id:"p10",matterId:"m3",dueDate:"2026-09-20",amount:495000,paidAmount:0,paidDate:"",status:"예정",method:"카드",installmentNo:1,taxInvoiceStatus:"미발행"},
 {id:"p11",matterId:"m8",dueDate:"2026-09-18",amount:220000,paidAmount:220000,paidDate:"2026-09-18",status:"완료",method:"간편결제",installmentNo:1,taxInvoiceStatus:"발행"},
 {id:"p12",matterId:"m10",dueDate:"2026-09-18",amount:350000,paidAmount:350000,paidDate:"2026-09-18",status:"완료",method:"카드",installmentNo:1,taxInvoiceStatus:"발행"},
 {id:"p13",matterId:"m1",dueDate:"2026-09-03",amount:440000,paidAmount:440000,paidDate:"2026-09-03",status:"완료",method:"카드",installmentNo:1,taxInvoiceStatus:"발행"},
 {id:"p14",matterId:"m3",dueDate:"2026-08-25",amount:495000,paidAmount:495000,paidDate:"2026-08-25",status:"완료",method:"가상계좌",installmentNo:1,taxInvoiceStatus:"발행"}
];
const seedCases=[
 {id:"case1",matterId:"m7",currentStage:"서류 수합",court:"청주지방법원",caseNumber:"",filedAt:"",nextDueAt:"2026-09-30",memo:"누락 서류 4건",updatedAt:"2026-09-19T09:30:00"},
 {id:"case2",matterId:"m9",currentStage:"보정권고 대응",court:"서울회생법원",caseNumber:"2026개회123456",filedAt:"2026-09-18",nextDueAt:"2026-09-25",memo:"보정자료 정리 중",updatedAt:"2026-09-19T10:15:00"},
 {id:"case3",matterId:"m3",currentStage:"서류검토",court:"인천지방법원",caseNumber:"",filedAt:"",nextDueAt:"2026-09-26",memo:"부동산 시세 및 담보채무 확인",updatedAt:"2026-09-19T11:40:00"}
];

function makeDocs(matterId,done=0){return documentChecklist.map((title,i)=>({id:`doc-${matterId}-${i+1}`,matterId,no:i+1,title,status:i<done?"수령":i===done?"요청":"미수령",receivedAt:i<done?"2026-09-18":"",note:""}))}
const seedDocuments=[...makeDocs("m7",9),...makeDocs("m9",14),...makeDocs("m3",5)];
const seedLogs=[
 {id:"l1",matterId:"m1",createdAt:"2026-09-19T10:05:00",author:"김도윤",kind:"상담메모",body:"월 소득 및 채무규모 1차 확인. 가족관계서류 안내."},
 {id:"l2",matterId:"m7",createdAt:"2026-09-18T16:30:00",author:"김도윤",kind:"서류",body:"15종 중 9종 수령. 급여입금내역 재요청."},
 {id:"l3",matterId:"m9",createdAt:"2026-09-19T10:20:00",author:"박지훈",kind:"사건진행",body:"보정권고 확인 후 의뢰인에게 추가자료 요청."}
];
const seedPosts=[
 {id:"b1",createdAt:"2026-09-19T08:30:00",title:"9월 회생 사건 서류 체크 기준",body:"초본 주소변동 포함 여부와 최근 1년 급여입금내역을 우선 확인해 주세요.",author:"관리자",pinned:true},
 {id:"b2",createdAt:"2026-09-18T18:20:00",title:"결제실패 건 처리 메모",body:"실패 사유 확인 후 결제수단 재등록 안내 → 다음 영업일 재확인 순으로 진행합니다.",author:"관리자",pinned:false}
];

function seedDB(){return {
  schemaVersion:1,clients:seedClients,matters:seedMatters,assets:seedAssets,debts:seedDebts,contracts:seedContracts,payments:seedPayments,
  documents:seedDocuments,cases:seedCases,logs:seedLogs,posts:seedPosts,history:[
    {id:"h1",createdAt:"2026-09-19T14:10:00",category:"신규DB",action:"접수",target:"조아라",detail:"카카오 상담 신규 DB 접수"},
    {id:"h2",createdAt:"2026-09-19T11:40:00",category:"사건진행",action:"수정",target:"이준호",detail:"부동산 자료 보완 일정 등록"},
    {id:"h3",createdAt:"2026-09-19T10:20:00",category:"사건진행",action:"메모",target:"임재현",detail:"보정권고 대응 메모 추가"}
  ],
  settings:{referenceYear:2026,livingCostByHousehold:{"1":1435000,"2":2359000,"3":3015000,"4":3659000,"5":4218000,"6":4753000},caseTypeEnabled:{"개인회생":true,"개인파산":true,"워크아웃/기타":true,"민사":true,"형사":true,"불법사채구제":false},pgFeeRate:2.75,serviceFeeRate:3.2}
}}

const fmtWon=v=>`${Math.round(Number(v||0)).toLocaleString("ko-KR")}원`;
const fmtPct=v=>`${Number(v||0).toFixed(1)}%`;
const dateOnly=s=>(s||"").slice(0,10);
const diffDays=(a,b)=>Math.floor((new Date(a)-new Date(b))/86400000);
const id=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,6)}`;
function clientOf(db,matterId){const m=db.matters.find(x=>x.id===matterId);return m?db.clients.find(c=>c.id===m.clientId):null}
function currentMatter(db,clientId){return [...db.matters].filter(m=>m.clientId===clientId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0]||null}
function tone(status){if(["완료","수임","진행중","종결(성공)","수령","결제완료"].some(x=>status?.includes(x)))return"green";if(["실패","연체","거절","부적합","보완필요","중단"].some(x=>status?.includes(x)))return"red";if(["재통화","고려중","요청","서명대기"].some(x=>status?.includes(x)))return"gold";return"blue"}
function calcMatter(db,m){
 const income=(m.monthlyIncome||0)+(m.sideIncome||0)+(m.pensionIncome||0);
 const living=db.settings.livingCostByHousehold[String(m.householdSize)]??db.settings.livingCostByHousehold["6"]??0;
 const disposable=Math.max(0,income-living-(m.extraDeduction||0));
 const assets=db.assets.filter(a=>a.matterId===m.id);const assetTotal=assets.reduce((s,a)=>s+a.value,0);const secured=assets.reduce((s,a)=>s+a.securedAmount,0);const liquidation=Math.max(0,assetTotal-secured);
 const debts=db.debts.filter(d=>d.matterId===m.id);const unsecured=debts.filter(d=>!["담보채무"].includes(d.type)).reduce((s,d)=>s+d.amount,0);const months=Math.max(1,m.repaymentMonths||36);
 const incomePlan=disposable*months;const planned=Math.min(unsecured||incomePlan,Math.max(incomePlan,liquidation));const monthly=planned/months;const relief=Math.max(0,unsecured-planned);const reliefRate=unsecured?relief/unsecured*100:0;
 return{income,living,disposable,assetTotal,liquidation,unsecured,planned,monthly,relief,reliefRate};
}
function monthKey(d){return d.slice(0,7)}
function sumPayments(db,start,end){
 const rows=db.payments.filter(p=>p.dueDate>=start&&p.dueDate<=end);const billed=rows.reduce((s,p)=>s+p.amount,0);const paid=rows.reduce((s,p)=>s+p.paidAmount,0);return{billed,paid,receivable:Math.max(0,billed-paid)}
}
function periodBounds(mode,anchor){
 const a=new Date(anchor+"T00:00:00");let start,end;
 if(mode==="year"){start=`${a.getFullYear()}-01-01`;end=`${a.getFullYear()}-12-31`}
 else if(mode==="month"){const y=a.getFullYear(),m=a.getMonth();start=`${y}-${String(m+1).padStart(2,"0")}-01`;const last=new Date(y,m+1,0).getDate();end=`${y}-${String(m+1).padStart(2,"0")}-${last}`}
 else if(mode==="week"){const block=Math.floor((a.getDate()-1)/7)*7+1;const s=new Date(a.getFullYear(),a.getMonth(),block);const e=new Date(a.getFullYear(),a.getMonth(),Math.min(block+6,new Date(a.getFullYear(),a.getMonth()+1,0).getDate()));start=s.toISOString().slice(0,10);end=e.toISOString().slice(0,10)}
 else{start=anchor;end=anchor}
 if(end>TODAY)end=TODAY;return{start,end}
}
function shiftAnchor(mode,anchor,delta){const d=new Date(anchor+"T00:00:00");if(mode==="year")d.setFullYear(d.getFullYear()+delta);else if(mode==="month")d.setMonth(d.getMonth()+delta);else if(mode==="week")d.setDate(d.getDate()+delta*7);else d.setDate(d.getDate()+delta);return d.toISOString().slice(0,10)}
function periodLabel(mode,anchor){const d=new Date(anchor+"T00:00:00");const y=d.getFullYear(),m=d.getMonth()+1;if(mode==="year")return`${y}년`;if(mode==="month")return`${y}년 ${m}월`;if(mode==="week")return`${y}년 ${m}월 ${Math.floor((d.getDate()-1)/7)+1}주차`;return`${y}년 ${m}월 ${d.getDate()}일`}

function useDemoDB(){
 const [db,setDb]=useState(seedDB);
 const [loaded,setLoaded]=useState(false);
 useEffect(()=>{
   try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const parsed=JSON.parse(raw);if(parsed?.schemaVersion===1&&parsed?.clients&&parsed?.settings)setDb(parsed)}}catch{}
   setLoaded(true);
 },[]);
 useEffect(()=>{if(!loaded)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(db))}catch{}},[db,loaded]);
 const update=fn=>setDb(d=>typeof fn==="function"?fn(d):fn);
 const addHistory=(category,action,target,detail)=>({id:id("h"),createdAt:new Date().toISOString(),category,action,target,detail});
 return{db,update,reset:()=>{const n=seedDB();setDb(n);try{localStorage.setItem(STORAGE_KEY,JSON.stringify(n))}catch{}},addHistory};
}

function IconButton({children,onClick,title,className=""}){return <button className={`icon-btn ${className}`} onClick={onClick} title={title}>{children}</button>}
function Button({children,onClick,variant="primary",disabled=false,className="",type="button"}){return <button type={type} disabled={disabled} onClick={onClick} className={`btn btn-${variant} ${className}`}>{children}</button>}
function Badge({children,tone:t="blue"}){return <span className={`badge badge-${t}`}>{children}</span>}
function Field({label,children,hint}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
function Modal({open,title,onClose,children,wide=false}){if(!open)return null;return <div className="modal-layer"><button className="modal-backdrop" onClick={onClose}/><div className={`modal ${wide?"modal-wide":""}`}><div className="modal-head"><div><b>{title}</b></div><IconButton onClick={onClose}><X size={18}/></IconButton></div><div className="modal-body">{children}</div></div></div>}
function PageTitle({title,desc,action}){return <div className="page-title"><div><h1>{title}</h1><p>{desc}</p></div>{action&&<div>{action}</div>}</div>}
function EmptyRow({cols,text="데이터가 없습니다."}){return <tr><td colSpan={cols} className="empty-cell">{text}</td></tr>}
function SearchBox({value,onChange,placeholder="검색"}){return <div className="search-box"><Search size={16}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>{value&&<button onClick={()=>onChange("")}><X size={14}/></button>}</div>}
function Pagination({page,total,size=10,onChange}){const pages=Math.max(1,Math.ceil(total/size));if(pages<=1)return null;return <div className="pagination"><button disabled={page<=1} onClick={()=>onChange(page-1)}><ChevronLeft size={15}/></button><span>{page} / {pages}</span><button disabled={page>=pages} onClick={()=>onChange(page+1)}><ChevronRight size={15}/></button></div>}
function Select({value,onChange,children,className=""}){return <select className={`control ${className}`} value={value} onChange={e=>onChange(e.target.value)}>{children}</select>}
function Input(props){return <input {...props} className={`control ${props.className||""}`}/>}
function MoneyInput({value,onChange}){return <input className="control" inputMode="numeric" value={value?Number(value).toLocaleString("ko-KR"):""} onChange={e=>onChange(Number(e.target.value.replace(/[^0-9]/g,""))||0)} placeholder="0"/>}

const menuGroups=[
 {label:"업무",items:[
  ["대시보드","dashboard",Home],["신규 상담 DB","leads",Inbox],["상담 / 고객 관리","customers",Users],["파이프라인","pipeline",ListTodo],["오늘의 일정","schedule",CalendarDays]
 ]},
 {label:"계약 · 결제",items:[
  ["계약 관리","contracts",FileSignature],["청구 / 결제","payments",CreditCard],["PG / 정산 데모","settlement",CircleDollarSign]
 ]},
 {label:"사건",items:[
  ["서류 수합","documents",FileCheck2],["사건 진행","cases",Landmark],["데이터 집계","analytics",BarChart3]
 ]},
 {label:"관리",items:[
  ["내부 게시판","board",MessageSquareText],["기간별 변동내역","changes",History],["기준표 / 설정","settings",Settings]
 ]}
];

function Sidebar({section,setSection,mobileOpen,setMobileOpen}){
 const body=<>
   <div className="brand"><div className="brand-mark">LP</div><div><b>로파워</b><span>LAW FIRM POWER OS</span></div>{setMobileOpen&&<button className="sidebar-close" onClick={()=>setMobileOpen(false)}><X size={18}/></button>}</div>
   <div className="brand-sub">회생·파산 중심 통합 Admin</div>
   <nav className="sidebar-nav">{menuGroups.map(g=><div key={g.label}><div className="nav-label">{g.label}</div>{g.items.map(([label,key,Icon])=><button key={key} onClick={()=>{setSection(key);setMobileOpen?.(false)}} className={`nav-item ${section===key?"active":""}`}><Icon size={16}/><span>{label}</span></button>)}</div>)}</nav>
   <div className="sidebar-ai"><span><Sparkles size={12}/> AI</span><p>오늘 상담·미수금·서류·기한을 한 번에 요약하는 영역입니다.</p><button onClick={()=>{setSection("dashboard");setMobileOpen?.(false)}}>브리핑 보기</button></div>
   <div className="profile"><div className="avatar">관</div><div><b>데모 관리자</b><span>ADMIN · 로파워</span></div></div>
 </>;
 return <>
   <aside className="sidebar desktop-sidebar">{body}</aside>
   {mobileOpen&&<div className="mobile-drawer"><button className="drawer-bg" onClick={()=>setMobileOpen(false)}/><aside className="sidebar mobile-sidebar">{body}</aside></div>}
 </>
}

function Topbar({setMobileOpen,db,reset}){
 const newLeads=db.matters.filter(m=>!m.clientRegistered).length;
 const overdue=db.payments.filter(p=>["연체","실패"].includes(p.status)).length;
 return <header className="topbar"><button className="mobile-menu" onClick={()=>setMobileOpen(true)}><Menu size={20}/></button><div className="topbar-title"><b>로파워 회생·파산 통합 Admin</b><span>도원 Admin 업무 UX + 로피 대시보드 설계 통합 데모</span></div><div className="topbar-spacer"/><div className="top-alert"><Bell size={16}/>{newLeads+overdue>0&&<em>{newLeads+overdue}</em>}</div><Badge tone="gold">FUNCTIONAL DEMO</Badge><button className="reset-link" onClick={()=>{if(confirm("데모 데이터를 초기화할까요?"))reset()}}><RefreshCw size={14}/>초기화</button></header>
}

function StatChip({icon:Icon,label,value,toneClass=""}){return <div className={`stat-chip ${toneClass}`}><Icon size={15}/><div><span>{label}</span><b>{value}</b></div></div>}
function Kpi({label,value,delta,sub,accent}){const d=Number(delta||0);const cls=d>0?"up":d<0?"down":"neutral";return <div className="kpi"><div className="kpi-top"><span>{label}</span><em className={cls}>{d>0?"▲ ":d<0?"▼ ":""}{Math.abs(d).toFixed(1)}%</em></div><strong className={accent||""}>{value}</strong><p>{sub}</p></div>}

function MiniBarChart({items,max,labelKey="label",valueKey="value",secondKey,secondLabel}){
 const m=max||Math.max(...items.map(x=>Math.max(x[valueKey]||0,x[secondKey]||0)),1);
 return <div className="mini-chart"><div className="chart-bars">{items.map((x,i)=><div className="bar-col" key={i}><div className="bar-wrap">{secondKey&&<div className="bar second" title={`${secondLabel||"2"}: ${fmtWon(x[secondKey])}`} style={{height:`${Math.max(2,(x[secondKey]/m)*100)}%`}}/>}<div className="bar" title={fmtWon(x[valueKey])} style={{height:`${Math.max(2,(x[valueKey]/m)*100)}%`}}/></div><span>{x[labelKey]}</span></div>)}</div></div>
}

function Dashboard({db,update,setSection}){
 const [mode,setMode]=useState("month");const [anchor,setAnchor]=useState(TODAY);const bounds=periodBounds(mode,anchor);const cur=sumPayments(db,bounds.start,bounds.end);const prevAnchor=shiftAnchor(mode,anchor,-1);const pb=periodBounds(mode,prevAnchor);const prev=sumPayments(db,pb.start,pb.end);
 const delta=(a,b)=>b?((a-b)/b*100):0;
 const scheduled=Math.round(cur.billed*1.18);
 const registered=db.matters.filter(m=>m.clientRegistered).length;const newLeads=db.matters.filter(m=>!m.clientRegistered).length;const todayConsult=db.matters.filter(m=>m.consultDate===TODAY).length;const todayDue=db.payments.filter(p=>p.dueDate===TODAY).length;const todayPaid=db.payments.filter(p=>p.paidDate===TODAY).reduce((s,p)=>s+p.paidAmount,0);const overdue=db.payments.filter(p=>["연체","실패"].includes(p.status));const dueCases=db.cases.filter(c=>c.nextDueAt&&c.nextDueAt>=TODAY&&diffDays(c.nextDueAt,TODAY)<=7);
 const monthBuckets=[1,2,3,4].map(w=>{const s=`2026-09-${String((w-1)*7+1).padStart(2,"0")}`;const e=`2026-09-${String(Math.min(w*7,28)).padStart(2,"0")}`;const t=sumPayments(db,s,e);return{label:`${w}주`,value:t.billed,paid:t.paid}});
 const caseAcc={};db.payments.filter(p=>p.paidAmount>0).forEach(p=>{const m=db.matters.find(x=>x.id===p.matterId);if(m)caseAcc[m.caseType]=(caseAcc[m.caseType]||0)+p.paidAmount});const totalCase=Object.values(caseAcc).reduce((s,v)=>s+v,0)||1;
 const nextBlocked=shiftAnchor(mode,anchor,1)>TODAY;
 return <div>
   <div className="topstats"><StatChip icon={Inbox} label="신규 상담 DB" value={`${newLeads}건`} toneClass={newLeads?"warn":""}/><StatChip icon={Users} label="등록 의뢰인" value={`${registered}건`}/><StatChip icon={CalendarDays} label="오늘 상담" value={`${todayConsult}건`}/><StatChip icon={CreditCard} label="오늘 청구" value={`${todayDue}건`}/><StatChip icon={WalletCards} label="오늘 결제" value={fmtWon(todayPaid)}/><StatChip icon={Clock3} label="7일 내 법원기한" value={`${dueCases.length}건`} toneClass={dueCases.length?"danger":""}/></div>
   {(newLeads||overdue.length)&&<div className="alert-banner"><div className="alert-icon"><AlertTriangle size={17}/></div><div><b>확인 필요한 업무 {newLeads+overdue.length}건</b><span>신규 상담 {newLeads}건 · 결제실패/연체 {overdue.length}건</span></div><div className="alert-actions"><Button variant="ghost" onClick={()=>setSection("leads")}>신규 DB 보기</Button><Button onClick={()=>setSection("payments")}>결제 확인</Button></div></div>}
   <section className="ai-panel"><div className="ai-head"><span><Sparkles size={14}/> AI 생성</span><b>오늘의 브리핑</b></div><ul><li><b>{newLeads}건의 신규 상담 DB</b>가 아직 의뢰인 등록 전이에요. 첫 연락 예정 건부터 확인하세요.</li><li><b>{overdue.length}건의 결제실패·연체</b>가 있습니다. 오래된 미수금부터 연락 순서를 정리했어요.</li><li><b>{dueCases.length}건의 사건 기한</b>이 7일 안에 도래합니다. 서류 수합률이 낮은 사건을 먼저 확인하세요.</li></ul><div className="ai-actions"><Button variant="light" onClick={()=>setSection("schedule")}>오늘 업무 열기</Button><Button variant="dark" onClick={()=>setSection("documents")}>서류 미수령 보기</Button></div></section>

   <div className="section-kicker"><span className="live-dot"/>실시간 현황 <small>아래 기간 설정과 무관하게 현재 기준으로 표시됩니다.</small></div>
   <div className="grid-two"><section className="panel"><div className="panel-head"><div><b>청구·결제 스냅샷</b><span>출근 후 바로 보는 당일/주간 결제 흐름</span></div><Badge tone="gold">실시간</Badge></div><div className="snapshot-row"><div><span>오늘 청구 예정</span><b>{fmtWon(db.payments.filter(p=>p.dueDate===TODAY).reduce((s,p)=>s+p.amount,0))}</b></div><div><span>오늘 결제 완료</span><b className="blue">{fmtWon(todayPaid)}</b></div><div><span>현재 미수금</span><b className="red">{fmtWon(overdue.reduce((s,p)=>s+(p.amount-p.paidAmount),0))}</b></div></div><MiniBarChart items={monthBuckets} valueKey="value" secondKey="paid" secondLabel="결제"/></section>
   <section className="panel"><div className="panel-head"><div><b>캐시플로우 예측</b><span>등록 분납 스케줄 기준 향후 결제 예정</span></div><Badge tone="gold">향후 6개월</Badge></div><div className="cashflow-list">{["9월","10월","11월","12월","1월","2월"].map((m,i)=>{const v=[1480000,1250000,1010000,820000,740000,620000][i];return <div key={m}><span>{m}</span><i style={{width:`${v/1480000*100}%`}}/><b>{fmtWon(v)}</b></div>})}</div><p className="footnote">최근 완결 결제 흐름을 기준으로 보는 데모 예측입니다. 실제 운영 시 PG/청구 데이터와 연결하도록 설계합니다.</p></section></div>

   <div className="period-box"><div className="section-kicker static"><span className="period-dot"/>기간별 통계 <small>헤드라인·KPI·결제 현황·사건유형 구성·담당자 실적이 함께 변경됩니다.</small></div><div className="period-controls"><div className="tabs">{["year","month","week","day"].map((x,i)=><button key={x} className={mode===x?"active":""} onClick={()=>setMode(x)}>{["년","월","주","일"][i]}</button>)}</div><IconButton onClick={()=>setAnchor(shiftAnchor(mode,anchor,-1))}><ChevronLeft size={16}/></IconButton><button className="date-pill">{periodLabel(mode,anchor)}</button><IconButton className={nextBlocked?"disabled":""} onClick={()=>{if(!nextBlocked)setAnchor(shiftAnchor(mode,anchor,1))}}><ChevronRight size={16}/></IconButton><Button variant="ghost" onClick={()=>setAnchor(TODAY)}>현재 기간</Button></div></div>
   <div className="headline"><h2>{periodLabel(mode,anchor)}, 결제 완료액 <b>{fmtWon(cur.paid)}</b>을 기록하고 있어요</h2><span>데이터는 데모 기준 · 결제/청구 명칭은 로피 스펙 기준</span></div>
   <div className="kpi-row"><Kpi label="청구 예정 총액" value={fmtWon(scheduled)} delta={delta(scheduled,prev.billed*1.18)} sub="청구 전 + 예정 스케줄 포함"/><Kpi label="청구 완료액" value={fmtWon(cur.billed)} delta={delta(cur.billed,prev.billed)} sub="선택 기간 내 청구 처리 총액"/><Kpi label="결제 완료액" value={fmtWon(cur.paid)} delta={delta(cur.paid,prev.paid)} sub={`결제율 ${cur.billed?Math.round(cur.paid/cur.billed*100):0}%`} accent="blue"/><Kpi label="미수금" value={fmtWon(cur.receivable)} delta={delta(cur.receivable,prev.receivable)} sub="청구 완료액 − 결제 완료액" accent="red"/></div>
   <div className="grid-two dashboard-mid"><section className="panel"><div className="panel-head"><div><b>청구·결제 현황</b><span>{periodLabel(mode,anchor)} 기준</span></div><div className="legend"><i className="blue-dot"/>청구 <i className="gold-dot"/>결제</div></div><MiniBarChart items={monthBuckets} valueKey="value" secondKey="paid" secondLabel="결제"/></section><section className="panel"><div className="panel-head"><div><b>사건유형별 매출 구성</b><span>결제 완료액 기준</span></div><IconButton onClick={()=>setSection("settings")}><Settings size={15}/></IconButton></div><div className="donut-wrap"><div className="donut" style={{background:`conic-gradient(#2944af 0 52%,#b06a1a 52% 73%,#2c7a3f 73% 87%,#b32c2c 87% 100%)`}}><div><b>{fmtWon(totalCase)}</b><span>결제 완료 합계</span></div></div><div className="donut-legend">{Object.entries(caseAcc).sort((a,b)=>b[1]-a[1]).map(([k,v],i)=><div key={k}><i className={`c${i%4}`}/><span>{k}</span><b>{fmtWon(v)} · {Math.round(v/totalCase*100)}%</b></div>)}</div></div></section></div>
   <div className="grid-two"><ReceivableTable db={db} compact setSection={setSection}/><UpcomingPanel db={db}/></div>
 </div>
}

function ReceivableTable({db,compact=false,setSection}){
 const rows=db.payments.filter(p=>["연체","실패"].includes(p.status)).map(p=>({p,c:clientOf(db,p.matterId),days:Math.max(0,diffDays(TODAY,p.dueDate))})).sort((a,b)=>b.days-a.days);
 return <section className="panel"><div className="panel-head"><div><b>미수금 우선순위</b><span>오늘 기준 연체일수 순</span></div><Badge tone="gold">실시간</Badge></div><div className="table-scroll"><table className="data-table"><thead><tr><th>고객명</th><th>연체</th><th className="num">금액</th><th>사유</th><th></th></tr></thead><tbody>{rows.slice(0,compact?5:50).map(({p,c,days})=><tr key={p.id}><td><b>{c?.name||"-"}</b></td><td><span className={`overdue d${days>=30?3:days>=15?2:1}`}>D+{days}</span></td><td className="num">{fmtWon(p.amount-p.paidAmount)}</td><td><Badge tone={tone(p.status)}>{p.failReason||p.status}</Badge></td><td><Button variant="ghost" onClick={()=>setSection?.("payments")}>확인</Button></td></tr>)}{rows.length===0&&<EmptyRow cols={5}/>}</tbody></table></div></section>
}
function UpcomingPanel({db}){
 const upcoming=[...db.payments].filter(p=>p.dueDate>=TODAY&&p.status!=="완료").sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,5);const recent=[...db.payments].filter(p=>p.status==="완료").sort((a,b)=>b.paidDate.localeCompare(a.paidDate)).slice(0,5);
 return <section className="panel"><div className="panel-head"><div><b>다가오는 청구 / 최근 결제</b><span>청구예정일 임박순 · 결제일 최신순</span></div><Badge tone="gold">실시간</Badge></div><div className="split-lists"><div><h4>다가오는 청구</h4>{upcoming.map(p=><div className="mini-row" key={p.id}><span>{p.dueDate.slice(5)}</span><b>{clientOf(db,p.matterId)?.name||"-"}</b><em>{fmtWon(p.amount)}</em></div>)}</div><div><h4>최근 결제</h4>{recent.map(p=><div className="mini-row" key={p.id}><span>{p.paidDate.slice(5)}</span><b>{clientOf(db,p.matterId)?.name||"-"}</b><em>{fmtWon(p.paidAmount)}</em></div>)}</div></div></section>
}

function LeadsPage({db,update,addHistory,setSection}){
 const [q,setQ]=useState("");const [open,setOpen]=useState(false);const [draft,setDraft]=useState({name:"",phone:"",caseType:"개인회생",source:"온라인 광고",manager:managers[0],memo:""});
 const rows=db.matters.filter(m=>!m.clientRegistered).filter(m=>{const c=db.clients.find(x=>x.id===m.clientId);return `${c?.name} ${c?.phone} ${m.caseType} ${m.source}`.toLowerCase().includes(q.toLowerCase())}).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
 function save(){if(!draft.name.trim()||!draft.phone.trim())return alert("이름과 연락처를 입력해주세요.");const dup=db.clients.find(c=>c.phone.replace(/\D/g,"")===draft.phone.replace(/\D/g,""));if(dup&&!confirm(`${dup.name} 의뢰인과 동일한 연락처가 있습니다. 새 상담 건으로 추가할까요?`))return;const cid=dup?.id||id("c"),mid=id("m"),now=new Date().toISOString();update(d=>({...d,clients:dup?d.clients:[{id:cid,createdAt:now,name:draft.name.trim(),phone:draft.phone.trim(),birthDate:"",gender:"미입력",address:"",manager:draft.manager,registered:false,spouse:"미입력",children:"",dependents:1,healthIssue:"",memo:draft.memo},...d.clients],matters:[{id:mid,clientId:cid,createdAt:now,caseType:draft.caseType,status:"신규접수",source:draft.source,manager:draft.manager,consultDate:"",nextActionDate:TODAY,nextActionType:"첫 연락",occupation:"미입력",companyName:"",monthlyIncome:0,sideIncome:0,pensionIncome:0,householdSize:1,extraDeduction:0,repaymentMonths:36,court:"미지정",memo:draft.memo,clientRegistered:false},...d.matters],history:[addHistory("신규DB","접수",draft.name,`${draft.caseType} · ${draft.source}`),...d.history]}));setOpen(false);setDraft({name:"",phone:"",caseType:"개인회생",source:"온라인 광고",manager:managers[0],memo:""})}
 function register(m){const c=db.clients.find(x=>x.id===m.clientId);if(!c)return;update(d=>({...d,clients:d.clients.map(x=>x.id===c.id?{...x,registered:true}:x),matters:d.matters.map(x=>x.id===m.id?{...x,clientRegistered:true,status:x.status==="신규접수"?"상담예정":x.status}:x),history:[addHistory("신규DB","의뢰인 등록",c.name,"상담/고객 관리로 이관"),...d.history]}))}
 return <><PageTitle title="신규 상담 DB" desc="신규 유입 → 연락 확인 → 의뢰인 등록 → 상담/고객 관리로 넘어가는 흐름을 단순하게 관리합니다." action={<Button onClick={()=>setOpen(true)}><Plus size={15}/>신규 DB 등록</Button>}/><div className="flow-strip"><div className="active"><b>1</b><span>신규 DB 접수</span></div><i>→</i><div><b>2</b><span>연락/상담 확인</span></div><i>→</i><div><b>3</b><span>의뢰인 등록</span></div><i>→</i><div><b>4</b><span>상담/고객 관리</span></div></div><section className="board"><div className="board-tools"><SearchBox value={q} onChange={setQ} placeholder="이름·전화번호·사건유형·유입경로 검색"/><span className="tool-note">미등록 {rows.length}건</span></div><div className="table-scroll"><table className="data-table wide"><thead><tr><th>접수일</th><th>이름</th><th>연락처</th><th>사건유형</th><th>상태</th><th>담당자</th><th>유입</th><th>다음 액션</th><th></th></tr></thead><tbody>{rows.map(m=>{const c=db.clients.find(x=>x.id===m.clientId);return <tr key={m.id}><td>{dateOnly(m.createdAt)}</td><td><b>{c?.name}</b></td><td>{c?.phone}</td><td>{m.caseType}</td><td><Badge tone={tone(m.status)}>{m.status}</Badge></td><td>{m.manager}</td><td>{m.source}</td><td>{m.nextActionDate}<small className="cell-sub">{m.nextActionType}</small></td><td className="actions"><Button onClick={()=>register(m)}>의뢰인 등록 →</Button></td></tr>})}{rows.length===0&&<EmptyRow cols={9} text="미등록 신규 DB가 없습니다."/>}</tbody></table></div></section><Modal open={open} title="신규 상담 DB 등록" onClose={()=>setOpen(false)}><div className="form-grid"><Field label="이름"><Input value={draft.name} onChange={e=>setDraft(v=>({...v,name:e.target.value}))}/></Field><Field label="연락처"><Input value={draft.phone} onChange={e=>setDraft(v=>({...v,phone:e.target.value}))} placeholder="010-0000-0000"/></Field><Field label="사건유형"><Select value={draft.caseType} onChange={v=>setDraft(x=>({...x,caseType:v}))}>{caseTypes.map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="담당자"><Select value={draft.manager} onChange={v=>setDraft(x=>({...x,manager:v}))}>{managers.map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="유입경로"><Input value={draft.source} onChange={e=>setDraft(v=>({...v,source:e.target.value}))}/></Field><Field label="메모"><Input value={draft.memo} onChange={e=>setDraft(v=>({...v,memo:e.target.value}))}/></Field></div><div className="modal-actions"><Button variant="ghost" onClick={()=>setOpen(false)}>취소</Button><Button onClick={save}>저장</Button></div></Modal></>
}

function CustomersPage({db,update,addHistory}){
 const [q,setQ]=useState("");const [status,setStatus]=useState("전체");const [type,setType]=useState("전체");const [page,setPage]=useState(1);const [selected,setSelected]=useState(null);
 const rows=db.matters.filter(m=>m.clientRegistered).filter(m=>{const c=db.clients.find(x=>x.id===m.clientId);return(status==="전체"||m.status===status)&&(type==="전체"||m.caseType===type)&&`${c?.name} ${c?.phone} ${m.caseType} ${m.manager}`.toLowerCase().includes(q.toLowerCase())}).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));const slice=rows.slice((page-1)*10,page*10);
 return <><PageTitle title="상담 / 고객 관리" desc="도원 Admin의 게시판형 고객 관리 흐름을 유지하고, 회생·파산 상담시트 내용을 상세 탭으로 통합했습니다."/><section className="board"><div className="board-tools multi"><SearchBox value={q} onChange={v=>{setQ(v);setPage(1)}} placeholder="이름·전화번호 검색"/><Select value={type} onChange={v=>{setType(v);setPage(1)}}><option>전체</option>{caseTypes.map(x=><option key={x}>{x}</option>)}</Select><Select value={status} onChange={v=>{setStatus(v);setPage(1)}}><option>전체</option>{matterStatuses.map(x=><option key={x}>{x}</option>)}</Select></div><div className="table-scroll"><table className="data-table wide"><thead><tr><th>이름</th><th>연락처</th><th>사건유형</th><th>상태</th><th>상담일</th><th>다음 액션</th><th>담당자</th><th>관할법원</th><th></th></tr></thead><tbody>{slice.map(m=>{const c=db.clients.find(x=>x.id===m.clientId);return <tr key={m.id}><td><button className="link-text" onClick={()=>setSelected(c?.id)}>{c?.name}</button></td><td>{c?.phone}</td><td>{m.caseType}</td><td><Select value={m.status} onChange={v=>update(d=>({...d,matters:d.matters.map(x=>x.id===m.id?{...x,status:v}:x),history:[addHistory("고객관리","상태변경",c?.name||"",`${m.status} → ${v}`),...d.history]}))}>{matterStatuses.map(x=><option key={x}>{x}</option>)}</Select></td><td>{m.consultDate||"-"}</td><td>{m.nextActionDate||"-"}<small className="cell-sub">{m.nextActionType||"-"}</small></td><td>{m.manager}</td><td>{m.court}</td><td><Button variant="ghost" onClick={()=>setSelected(c?.id)}>상세보기</Button></td></tr>})}{rows.length===0&&<EmptyRow cols={9}/>}</tbody></table></div><Pagination page={page} total={rows.length} onChange={setPage}/></section>{selected&&<ClientDetail db={db} update={update} addHistory={addHistory} clientId={selected} onClose={()=>setSelected(null)}/>}</>
}

function ClientDetail({db,update,addHistory,clientId,onClose}){
 const client=db.clients.find(c=>c.id===clientId);const matter=currentMatter(db,clientId);const [tab,setTab]=useState("요약");const [logBody,setLogBody]=useState("");if(!client||!matter)return null;const c=calcMatter(db,matter);const tabs=["요약","인적사항","소득","재산","채무","예상 변제계획","상담내역","계약/결제","서류","사건진행"];
 const patchClient=p=>update(d=>({...d,clients:d.clients.map(x=>x.id===client.id?{...x,...p}:x)}));const patchMatter=p=>update(d=>({...d,matters:d.matters.map(x=>x.id===matter.id?{...x,...p}:x)}));
 const assets=db.assets.filter(x=>x.matterId===matter.id);const debts=db.debts.filter(x=>x.matterId===matter.id);const docs=db.documents.filter(x=>x.matterId===matter.id).sort((a,b)=>a.no-b.no);const contracts=db.contracts.filter(x=>x.matterId===matter.id);const payments=db.payments.filter(x=>x.matterId===matter.id).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));const caseRow=db.cases.find(x=>x.matterId===matter.id);const logs=db.logs.filter(x=>x.matterId===matter.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
 function addAsset(){update(d=>({...d,assets:[...d.assets,{id:id("a"),matterId:matter.id,type:"기타",value:0,securedAmount:0,note:""}]}))}function addDebt(){update(d=>({...d,debts:[...d.debts,{id:id("d"),matterId:matter.id,type:"신용채무",creditor:"",amount:0,note:""}]}))}
 function addLog(){if(!logBody.trim())return;const item={id:id("l"),matterId:matter.id,createdAt:new Date().toISOString(),author:matter.manager,kind:"상담메모",body:logBody.trim()};update(d=>({...d,logs:[item,...d.logs],history:[addHistory("고객관리","상담메모",client.name,logBody.trim()),...d.history]}));setLogBody("")}
 function createDocs(){if(docs.length)return;update(d=>({...d,documents:[...d.documents,...makeDocs(matter.id,0)]}))}
 function createCase(){if(caseRow)return;update(d=>({...d,cases:[...d.cases,{id:id("case"),matterId:matter.id,currentStage:"상담/수임",court:matter.court,caseNumber:"",filedAt:"",nextDueAt:"",memo:"",updatedAt:new Date().toISOString()}]}))}
 return <Modal open title={`${client.name} · ${matter.caseType}`} onClose={onClose} wide><div className="detail-tabs">{tabs.map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</div>
 {tab==="요약"&&<div className="detail-stack"><div className="summary-grid"><Info label="상태" value={matter.status}/><Info label="담당자" value={matter.manager}/><Info label="다음 액션" value={`${matter.nextActionDate||"-"} · ${matter.nextActionType||"-"}`}/><Info label="관할법원" value={matter.court}/><Info label="월 총소득" value={fmtWon(c.income)}/><Info label="신용/우선 채무" value={fmtWon(c.unsecured)}/><Info label="추정 월 변제금" value={fmtWon(c.monthly)}/><Info label="서류 수합" value={`${docs.filter(x=>["수령","해당없음"].includes(x.status)).length}/${docs.length||15}건`}/></div><Field label="상담 메모"><textarea className="control textarea" value={matter.memo} onChange={e=>patchMatter({memo:e.target.value})}/></Field><div className="notice amber">회생·파산 계산 영역은 상담 참고용 추정치이며 최종 법률판단이나 법원 인가 결과를 의미하지 않습니다.</div></div>}
 {tab==="인적사항"&&<div className="form-grid"><Field label="이름"><Input value={client.name} onChange={e=>patchClient({name:e.target.value})}/></Field><Field label="연락처"><Input value={client.phone} onChange={e=>patchClient({phone:e.target.value})}/></Field><Field label="생년월일"><Input type="date" value={client.birthDate} onChange={e=>patchClient({birthDate:e.target.value})}/></Field><Field label="성별"><Select value={client.gender} onChange={v=>patchClient({gender:v})}><option>미입력</option><option>남</option><option>여</option></Select></Field><Field label="거주지 / 초본주소"><Input value={client.address} onChange={e=>patchClient({address:e.target.value})}/></Field><Field label="관할법원"><Input value={matter.court} onChange={e=>patchMatter({court:e.target.value})}/></Field><Field label="배우자"><Input value={client.spouse} onChange={e=>patchClient({spouse:e.target.value})}/></Field><Field label="자녀"><Input value={client.children} onChange={e=>patchClient({children:e.target.value})}/></Field><Field label="부양가족 수"><MoneyInput value={client.dependents} onChange={v=>patchClient({dependents:v})}/></Field><Field label="중대질환 / 장기요양"><Input value={client.healthIssue} onChange={e=>patchClient({healthIssue:e.target.value})}/></Field></div>}
 {tab==="소득"&&<div className="form-grid"><Field label="직업"><Select value={matter.occupation} onChange={v=>patchMatter({occupation:v})}><option>미입력</option><option>직장인</option><option>사업자</option><option>프리랜서</option><option>무직</option><option>연금소득</option></Select></Field><Field label="회사 / 사업자명"><Input value={matter.companyName} onChange={e=>patchMatter({companyName:e.target.value})}/></Field><Field label="월평균소득"><MoneyInput value={matter.monthlyIncome} onChange={v=>patchMatter({monthlyIncome:v})}/></Field><Field label="2중/부업소득"><MoneyInput value={matter.sideIncome} onChange={v=>patchMatter({sideIncome:v})}/></Field><Field label="연금소득"><MoneyInput value={matter.pensionIncome} onChange={v=>patchMatter({pensionIncome:v})}/></Field><Field label="기타 공제"><MoneyInput value={matter.extraDeduction} onChange={v=>patchMatter({extraDeduction:v})}/></Field><Info label="연소득 추정" value={fmtWon(c.income*12)}/><Info label="기준 생활비" value={fmtWon(c.living)}/></div>}
 {tab==="재산"&&<div><div className="inline-head"><b>재산 목록</b><Button variant="ghost" onClick={addAsset}><Plus size={14}/>재산 추가</Button></div><div className="table-scroll"><table className="data-table"><thead><tr><th>종류</th><th className="num">가액</th><th className="num">담보액</th><th>비고</th></tr></thead><tbody>{assets.map(r=><tr key={r.id}><td><Select value={r.type} onChange={v=>update(d=>({...d,assets:d.assets.map(x=>x.id===r.id?{...x,type:v}:x)}))}><option>주택/토지</option><option>임차보증금</option><option>예금/적금</option><option>보험(해약환급금)</option><option>자동차</option><option>퇴직금(1/2)</option><option>주식/펀드</option><option>기타</option></Select></td><td><MoneyInput value={r.value} onChange={v=>update(d=>({...d,assets:d.assets.map(x=>x.id===r.id?{...x,value:v}:x)}))}/></td><td><MoneyInput value={r.securedAmount} onChange={v=>update(d=>({...d,assets:d.assets.map(x=>x.id===r.id?{...x,securedAmount:v}:x)}))}/></td><td><Input value={r.note} onChange={e=>update(d=>({...d,assets:d.assets.map(x=>x.id===r.id?{...x,note:e.target.value}:x)}))}/></td></tr>)}{assets.length===0&&<EmptyRow cols={4}/>}</tbody></table></div><div className="totals-line"><span>재산 합계 <b>{fmtWon(c.assetTotal)}</b></span><span>청산가치 추정 <b>{fmtWon(c.liquidation)}</b></span></div></div>}
 {tab==="채무"&&<div><div className="inline-head"><b>채무 / 채권자 목록</b><Button variant="ghost" onClick={addDebt}><Plus size={14}/>채무 추가</Button></div><div className="table-scroll"><table className="data-table"><thead><tr><th>구분</th><th>채권자</th><th className="num">금액</th><th>비고</th></tr></thead><tbody>{debts.map(r=><tr key={r.id}><td><Select value={r.type} onChange={v=>update(d=>({...d,debts:d.debts.map(x=>x.id===r.id?{...x,type:v}:x)}))}><option>신용채무</option><option>개인채무</option><option>세금체납</option><option>건강보험체납</option><option>담보채무</option><option>기타</option></Select></td><td><Input value={r.creditor} onChange={e=>update(d=>({...d,debts:d.debts.map(x=>x.id===r.id?{...x,creditor:e.target.value}:x)}))}/></td><td><MoneyInput value={r.amount} onChange={v=>update(d=>({...d,debts:d.debts.map(x=>x.id===r.id?{...x,amount:v}:x)}))}/></td><td><Input value={r.note} onChange={e=>update(d=>({...d,debts:d.debts.map(x=>x.id===r.id?{...x,note:e.target.value}:x)}))}/></td></tr>)}{debts.length===0&&<EmptyRow cols={4}/>}</tbody></table></div><div className="totals-line"><span>회생 계산 대상 채무 추정 <b>{fmtWon(c.unsecured)}</b></span></div></div>}
 {tab==="예상 변제계획"&&<div className="detail-stack"><div className="notice amber">상담용 추정치입니다. 실제 변제계획·청산가치·생계비·인가 여부는 사건별 자료와 담당변호사 검토가 필요합니다.</div><div className="summary-grid"><Info label="월 총소득" value={fmtWon(c.income)}/><Info label="기준 생활비" value={fmtWon(c.living)}/><Info label="월 가용소득" value={fmtWon(c.disposable)}/><Info label="청산가치 추정" value={fmtWon(c.liquidation)}/><Info label="추정 월 변제금" value={fmtWon(c.monthly)}/><Info label="추정 총 변제액" value={fmtWon(c.planned)}/><Info label="추정 탕감액" value={fmtWon(c.relief)}/><Info label="추정 탕감률" value={fmtPct(c.reliefRate)}/></div><div className="form-grid"><Field label="가구원 수"><MoneyInput value={matter.householdSize} onChange={v=>patchMatter({householdSize:Math.max(1,v)})}/></Field><Field label="변제기간(개월)"><MoneyInput value={matter.repaymentMonths} onChange={v=>patchMatter({repaymentMonths:Math.max(1,v)})}/></Field></div></div>}
 {tab==="상담내역"&&<div><div className="log-input"><Input value={logBody} onChange={e=>setLogBody(e.target.value)} placeholder="상담 메모 입력"/><Button onClick={addLog}>추가</Button></div><div className="timeline">{logs.map(r=><div key={r.id}><i/><div><small>{r.createdAt.slice(0,16).replace("T"," ")} · {r.author} · {r.kind}</small><p>{r.body}</p></div></div>)}{logs.length===0&&<div className="empty-box">상담 메모가 없습니다.</div>}</div></div>}
 {tab==="계약/결제"&&<div className="detail-stack"><div className="inline-head"><b>계약</b></div><div className="table-scroll"><table className="data-table"><thead><tr><th>계약일</th><th className="num">계약금액</th><th className="num">선납금</th><th>분납</th><th>상태</th></tr></thead><tbody>{contracts.map(r=><tr key={r.id}><td>{r.contractDate}</td><td className="num">{fmtWon(r.amount)}</td><td className="num">{fmtWon(r.upfrontAmount)}</td><td>{r.installmentCount}회</td><td><Badge tone={tone(r.status)}>{r.status}</Badge></td></tr>)}{contracts.length===0&&<EmptyRow cols={5}/>}</tbody></table></div><div className="inline-head"><b>청구 / 결제</b></div><div className="table-scroll"><table className="data-table"><thead><tr><th>예정일</th><th>회차</th><th className="num">청구액</th><th className="num">결제액</th><th>상태</th><th>수단</th></tr></thead><tbody>{payments.map(r=><tr key={r.id}><td>{r.dueDate}</td><td>{r.installmentNo}회</td><td className="num">{fmtWon(r.amount)}</td><td className="num">{fmtWon(r.paidAmount)}</td><td><Badge tone={tone(r.status)}>{r.status}</Badge></td><td>{r.method}</td></tr>)}{payments.length===0&&<EmptyRow cols={6}/>}</tbody></table></div></div>}
 {tab==="서류"&&<div>{docs.length===0?<div className="empty-box"><p>서류 체크리스트가 없습니다.</p><Button onClick={createDocs}>기본 15종 체크리스트 생성</Button></div>:<div className="table-scroll"><table className="data-table"><thead><tr><th>No</th><th>서류명</th><th>상태</th><th>수령일</th></tr></thead><tbody>{docs.map(r=><tr key={r.id}><td>{r.no}</td><td>{r.title}</td><td><Select value={r.status} onChange={v=>update(d=>({...d,documents:d.documents.map(x=>x.id===r.id?{...x,status:v,receivedAt:v==="수령"?TODAY:x.receivedAt}:x)}))}><option>미수령</option><option>요청</option><option>수령</option><option>보완필요</option><option>해당없음</option></Select></td><td>{r.receivedAt||"-"}</td></tr>)}</tbody></table></div>}</div>}
 {tab==="사건진행"&&<div>{!caseRow?<div className="empty-box"><p>사건진행 레코드가 없습니다.</p><Button onClick={createCase}>사건진행 생성</Button></div>:<div className="form-grid"><Field label="현재단계"><Input value={caseRow.currentStage} onChange={e=>update(d=>({...d,cases:d.cases.map(x=>x.id===caseRow.id?{...x,currentStage:e.target.value,updatedAt:new Date().toISOString()}:x)}))}/></Field><Field label="관할법원"><Input value={caseRow.court} onChange={e=>update(d=>({...d,cases:d.cases.map(x=>x.id===caseRow.id?{...x,court:e.target.value,updatedAt:new Date().toISOString()}:x)}))}/></Field><Field label="사건번호"><Input value={caseRow.caseNumber} onChange={e=>update(d=>({...d,cases:d.cases.map(x=>x.id===caseRow.id?{...x,caseNumber:e.target.value,updatedAt:new Date().toISOString()}:x)}))}/></Field><Field label="다음 기한"><Input type="date" value={caseRow.nextDueAt} onChange={e=>update(d=>({...d,cases:d.cases.map(x=>x.id===caseRow.id?{...x,nextDueAt:e.target.value,updatedAt:new Date().toISOString()}:x)}))}/></Field><Field label="진행 메모"><textarea className="control textarea" value={caseRow.memo} onChange={e=>update(d=>({...d,cases:d.cases.map(x=>x.id===caseRow.id?{...x,memo:e.target.value,updatedAt:new Date().toISOString()}:x)}))}/></Field></div>}</div>}
 </Modal>
}
function Info({label,value}){return <div className="info-cell"><span>{label}</span><b>{value||"-"}</b></div>}

function PipelinePage({db,update}){
 const [q,setQ]=useState("");const rows=db.matters.filter(m=>m.clientRegistered).filter(m=>{const c=db.clients.find(x=>x.id===m.clientId);return`${c?.name} ${m.caseType} ${m.status}`.toLowerCase().includes(q.toLowerCase())}).sort((a,b)=>a.nextActionDate.localeCompare(b.nextActionDate));
 const flow=["상담예정","상담완료","재통화필요","고려중","서류검토중","계약진행중","수임","진행중","종결(성공)"];
 return <><PageTitle title="상담 파이프라인" desc="칸반 대신 게시판형으로 상태·의뢰인·다음 액션을 한 화면에서 봅니다."/><div className="status-strip">{flow.map(s=><div key={s}><span>{s}</span><b>{rows.filter(x=>x.status===s).length}</b></div>)}</div><section className="board"><div className="board-tools"><SearchBox value={q} onChange={setQ} placeholder="의뢰인·사건유형·상태 검색"/></div><div className="table-scroll"><table className="data-table wide"><thead><tr><th>상태</th><th>의뢰인</th><th>사건유형</th><th>담당자</th><th>다음 액션일</th><th>다음 액션</th><th>상담일</th></tr></thead><tbody>{rows.map(m=>{const c=clientOf(db,m.id);return <tr key={m.id}><td><Select value={m.status} onChange={v=>update(d=>({...d,matters:d.matters.map(x=>x.id===m.id?{...x,status:v}:x)}))}>{matterStatuses.map(x=><option key={x}>{x}</option>)}</Select></td><td><b>{c?.name}</b></td><td>{m.caseType}</td><td>{m.manager}</td><td><Input type="date" value={m.nextActionDate} onChange={e=>update(d=>({...d,matters:d.matters.map(x=>x.id===m.id?{...x,nextActionDate:e.target.value}:x)}))}/></td><td><Input value={m.nextActionType} onChange={e=>update(d=>({...d,matters:d.matters.map(x=>x.id===m.id?{...x,nextActionType:e.target.value}:x)}))}/></td><td>{m.consultDate||"-"}</td></tr>})}{rows.length===0&&<EmptyRow cols={7}/>}</tbody></table></div></section></>
}

function SchedulePage({db}){
 const [kind,setKind]=useState("전체");const tasks=[];db.matters.filter(m=>m.clientRegistered&&m.nextActionDate).forEach(m=>tasks.push({date:m.nextActionDate,kind:"상담/업무",client:clientOf(db,m.id)?.name||"-",title:m.nextActionType,owner:m.manager,status:m.status}));db.payments.filter(p=>p.status!=="완료").forEach(p=>tasks.push({date:p.dueDate,kind:"청구/결제",client:clientOf(db,p.matterId)?.name||"-",title:`${fmtWon(p.amount)} 청구`,owner:"결제",status:p.status}));db.cases.filter(c=>c.nextDueAt).forEach(c=>tasks.push({date:c.nextDueAt,kind:"사건기한",client:clientOf(db,c.matterId)?.name||"-",title:`${c.currentStage} · ${c.court}`,owner:"사건",status:c.nextDueAt<TODAY?"기한경과":"예정"}));const rows=tasks.filter(x=>kind==="전체"||x.kind===kind).sort((a,b)=>a.date.localeCompare(b.date));
 return <><PageTitle title="오늘의 일정" desc="상담·청구·법원기한을 카드로 나누지 않고 하나의 업무 게시판에서 확인합니다."/><section className="board"><div className="board-tools"><div className="tabs small">{["전체","상담/업무","청구/결제","사건기한"].map(x=><button key={x} onClick={()=>setKind(x)} className={kind===x?"active":""}>{x}</button>)}</div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>일자</th><th>구분</th><th>의뢰인</th><th>업무</th><th>담당/영역</th><th>상태</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i} className={r.date<TODAY?"danger-row":r.date===TODAY?"today-row":""}><td><b>{r.date}</b></td><td><Badge tone={r.kind==="사건기한"?"red":r.kind==="청구/결제"?"gold":"blue"}>{r.kind}</Badge></td><td>{r.client}</td><td>{r.title}</td><td>{r.owner}</td><td><Badge tone={tone(r.status)}>{r.status}</Badge></td></tr>)}{rows.length===0&&<EmptyRow cols={6}/>}</tbody></table></div></section></>
}

function ContractsPage({db,update,addHistory}){
 const matters=db.matters.filter(m=>m.clientRegistered);const [open,setOpen]=useState(false);const [draft,setDraft]=useState({matterId:matters[0]?.id||"",amount:2200000,upfrontAmount:500000,installmentCount:4,paymentMethod:"카드",paymentMethodRegistered:true});
 function save(){if(!draft.matterId)return;const x={id:id("ct"),matterId:draft.matterId,contractDate:TODAY,amount:draft.amount,upfrontAmount:draft.upfrontAmount,installmentCount:draft.installmentCount,paymentMethod:draft.paymentMethod,status:"계약완료",paymentMethodRegistered:draft.paymentMethodRegistered};const c=clientOf(db,draft.matterId);const existingDocs=db.documents.some(d=>d.matterId===draft.matterId);update(d=>({...d,contracts:[x,...d.contracts],matters:d.matters.map(m=>m.id===draft.matterId?{...m,status:"수임"}:m),documents:existingDocs?d.documents:[...d.documents,...makeDocs(draft.matterId,0)],history:[addHistory("계약관리","계약등록",c?.name||"",fmtWon(draft.amount)),...d.history]}));setOpen(false)}
 const rows=[...db.contracts].sort((a,b)=>b.contractDate.localeCompare(a.contractDate));return <><PageTitle title="계약 관리" desc="의뢰인 계약금액·분납 조건·결제수단 등록 여부를 관리합니다. 계약 완료 시 서류 체크리스트를 자동 생성합니다." action={<Button onClick={()=>setOpen(true)}><Plus size={15}/>계약 등록</Button>}/><section className="board"><div className="table-scroll"><table className="data-table wide"><thead><tr><th>계약일</th><th>의뢰인</th><th>사건유형</th><th className="num">계약금액</th><th className="num">선납금</th><th>분납</th><th>결제수단</th><th>상태</th></tr></thead><tbody>{rows.map(r=>{const m=db.matters.find(x=>x.id===r.matterId);const c=clientOf(db,r.matterId);return <tr key={r.id}><td>{r.contractDate}</td><td><b>{c?.name}</b></td><td>{m?.caseType}</td><td className="num">{fmtWon(r.amount)}</td><td className="num">{fmtWon(r.upfrontAmount)}</td><td>{r.installmentCount}회</td><td>{r.paymentMethodRegistered?<Badge tone="green">등록완료</Badge>:<Badge tone="red">미등록</Badge>}</td><td><Badge tone={tone(r.status)}>{r.status}</Badge></td></tr>})}{rows.length===0&&<EmptyRow cols={8}/>}</tbody></table></div></section><Modal open={open} title="계약 등록" onClose={()=>setOpen(false)}><div className="form-grid"><Field label="의뢰인"><Select value={draft.matterId} onChange={v=>setDraft(x=>({...x,matterId:v}))}>{matters.map(m=><option key={m.id} value={m.id}>{clientOf(db,m.id)?.name} · {m.caseType}</option>)}</Select></Field><Field label="계약금액"><MoneyInput value={draft.amount} onChange={v=>setDraft(x=>({...x,amount:v}))}/></Field><Field label="선납금"><MoneyInput value={draft.upfrontAmount} onChange={v=>setDraft(x=>({...x,upfrontAmount:v}))}/></Field><Field label="분납 회차"><MoneyInput value={draft.installmentCount} onChange={v=>setDraft(x=>({...x,installmentCount:Math.max(1,v)}))}/></Field><Field label="결제 방식"><Select value={draft.paymentMethod} onChange={v=>setDraft(x=>({...x,paymentMethod:v}))}><option>카드</option><option>계좌이체</option><option>가상계좌</option><option>간편결제</option></Select></Field><Field label="결제수단 등록"><Select value={draft.paymentMethodRegistered?"등록":"미등록"} onChange={v=>setDraft(x=>({...x,paymentMethodRegistered:v==="등록"}))}><option>등록</option><option>미등록</option></Select></Field></div><div className="modal-actions"><Button variant="ghost" onClick={()=>setOpen(false)}>취소</Button><Button onClick={save}>저장</Button></div></Modal></>
}

function PaymentsPage({db,update,addHistory}){
 const matters=db.matters.filter(m=>m.clientRegistered);const [open,setOpen]=useState(false);const [status,setStatus]=useState("전체");const [q,setQ]=useState("");const [draft,setDraft]=useState({matterId:matters[0]?.id||"",dueDate:TODAY,amount:0,method:"카드",installmentNo:1});
 function save(){if(!draft.matterId||!draft.amount)return;const x={id:id("p"),matterId:draft.matterId,dueDate:draft.dueDate,amount:draft.amount,paidAmount:0,paidDate:"",status:"예정",method:draft.method,installmentNo:draft.installmentNo,taxInvoiceStatus:"미발행"};const c=clientOf(db,draft.matterId);update(d=>({...d,payments:[...d.payments,x],history:[addHistory("청구/결제","청구등록",c?.name||"",`${draft.dueDate} · ${fmtWon(draft.amount)}`),...d.history]}));setOpen(false)}
 const rows=[...db.payments].filter(p=>status==="전체"||p.status===status).filter(p=>{const c=clientOf(db,p.matterId);return`${c?.name} ${p.method} ${p.status}`.toLowerCase().includes(q.toLowerCase())}).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));const totalBilled=rows.reduce((s,p)=>s+p.amount,0),totalPaid=rows.reduce((s,p)=>s+p.paidAmount,0);
 function togglePaid(p){const done=p.status==="완료";const c=clientOf(db,p.matterId);update(d=>({...d,payments:d.payments.map(x=>x.id===p.id?{...x,status:done?"예정":"완료",paidAmount:done?0:x.amount,paidDate:done?"":TODAY}:x),history:[addHistory("청구/결제",done?"결제취소":"결제완료",c?.name||"",fmtWon(p.amount)),...d.history]}))}
 return <><PageTitle title="청구 / 결제" desc="로피 자료의 ‘수금’ 대신 ‘결제’ 명칭을 적용하고, 도원 Admin의 입금/분납 게시판 UX로 구성했습니다." action={<Button onClick={()=>setOpen(true)}><Plus size={15}/>청구 일정 추가</Button>}/><div className="summary-strip"><div><span>조회 청구액</span><b>{fmtWon(totalBilled)}</b></div><div><span>결제 완료액</span><b className="blue">{fmtWon(totalPaid)}</b></div><div><span>미수금</span><b className="red">{fmtWon(totalBilled-totalPaid)}</b></div><div><span>결제율</span><b>{totalBilled?Math.round(totalPaid/totalBilled*100):0}%</b></div></div><section className="board"><div className="board-tools multi"><SearchBox value={q} onChange={setQ} placeholder="의뢰인·수단·상태 검색"/><Select value={status} onChange={setStatus}><option>전체</option><option>예정</option><option>완료</option><option>실패</option><option>연체</option><option>취소</option></Select></div><div className="table-scroll"><table className="data-table wide"><thead><tr><th>예정일</th><th>의뢰인</th><th>회차</th><th className="num">청구액</th><th className="num">결제액</th><th>결제일</th><th>상태</th><th>수단</th><th>세금계산서</th><th></th></tr></thead><tbody>{rows.map(p=><tr key={p.id} className={p.status==="연체"||p.status==="실패"?"danger-row":""}><td><b>{p.dueDate}</b></td><td>{clientOf(db,p.matterId)?.name}</td><td>{p.installmentNo}회</td><td className="num">{fmtWon(p.amount)}</td><td className="num"><b>{fmtWon(p.paidAmount)}</b></td><td>{p.paidDate||"-"}</td><td><Select value={p.status} onChange={v=>update(d=>({...d,payments:d.payments.map(x=>x.id===p.id?{...x,status:v}:x)}))}><option>예정</option><option>완료</option><option>실패</option><option>연체</option><option>취소</option></Select></td><td>{p.method}</td><td><Badge tone={p.taxInvoiceStatus==="발행"?"green":"gold"}>{p.taxInvoiceStatus}</Badge></td><td><Button variant={p.status==="완료"?"ghost":"primary"} onClick={()=>togglePaid(p)}>{p.status==="완료"?"완료취소":"결제완료"}</Button></td></tr>)}{rows.length===0&&<EmptyRow cols={10}/>}</tbody></table></div></section><Modal open={open} title="청구 일정 추가" onClose={()=>setOpen(false)}><div className="form-grid"><Field label="의뢰인"><Select value={draft.matterId} onChange={v=>setDraft(x=>({...x,matterId:v}))}>{matters.map(m=><option key={m.id} value={m.id}>{clientOf(db,m.id)?.name} · {m.caseType}</option>)}</Select></Field><Field label="청구 예정일"><Input type="date" value={draft.dueDate} onChange={e=>setDraft(x=>({...x,dueDate:e.target.value}))}/></Field><Field label="청구액"><MoneyInput value={draft.amount} onChange={v=>setDraft(x=>({...x,amount:v}))}/></Field><Field label="회차"><MoneyInput value={draft.installmentNo} onChange={v=>setDraft(x=>({...x,installmentNo:Math.max(1,v)}))}/></Field><Field label="결제 수단"><Select value={draft.method} onChange={v=>setDraft(x=>({...x,method:v}))}><option>카드</option><option>가상계좌</option><option>계좌이체</option><option>간편결제</option></Select></Field></div><div className="modal-actions"><Button variant="ghost" onClick={()=>setOpen(false)}>취소</Button><Button onClick={save}>저장</Button></div></Modal></>
}

function SettlementPage({db,update}){
 const paidToday=db.payments.filter(p=>p.status==="완료"&&p.paidDate===TODAY);const billed=paidToday.reduce((s,p)=>s+p.paidAmount,0);const feeRate=db.settings.serviceFeeRate/100,pgRate=db.settings.pgFeeRate/100;const fee=Math.round(billed*feeRate),pg=Math.round(billed*pgRate),profit=Math.max(0,fee-pg),firmSettle=billed-fee;const [firmPaid,setFirmPaid]=useState(false),[companyPaid,setCompanyPaid]=useState(false),[reconciled,setReconciled]=useState(true);const remain=Math.max(0,(billed-pg)-(firmPaid?firmSettle:0)-(companyPaid?profit:0));
 return <><PageTitle title="PG / 정산 데모" desc="로피 운영사 어드민 자료의 정산·잔액 제로화·대사 개념을 로파워 확장 영역으로 정리한 기능 데모입니다. 실제 PG 송금 API는 연결하지 않았습니다."/><div className="notice blue">현재 페이지는 구조/업무흐름 검증용입니다. 실제 지급·송금 버튼은 외부 PG/뱅킹 API와 권한·감사로그를 붙인 뒤 운영해야 합니다.</div><section className="settle-hero"><div className="panel-head light"><div><b>당일 PG 정산 스냅샷</b><span>결제액 → 로펌 정산 → 운영 수수료/PG 원가 → 잔액 0원 검증</span></div><Badge tone="gold">실시간 데모</Badge></div><div className="settle-kpis"><div><span>오늘 결제액</span><b>{fmtWon(billed)}</b></div><div><span>로펌 정산 지급액</span><b>{fmtWon(firmSettle)}</b></div><div><span>수수료매출</span><b>{fmtWon(fee)}</b></div><div><span>PG 원가</span><b>{fmtWon(pg)}</b></div><div><span>순수익</span><b>{fmtWon(profit)}</b></div></div><div className="settle-actions"><Button disabled={!billed||firmPaid} onClick={()=>setFirmPaid(true)}>{firmPaid?"✓ 로펌 지급완료":"로펌 정산 지급하기"}</Button><Button variant="light" disabled={!firmPaid||companyPaid} onClick={()=>setCompanyPaid(true)}>{companyPaid?"✓ 본사 송금완료":"순수익 송금하기"}</Button></div></section><section className="recon-card"><div className="recon-side"><span>AI 정산 대사</span><div><em>로파워 어드민 합계</em><b>{fmtWon(billed-pg)}</b></div><div><em>PG 사이트 합계(시뮬레이션)</em><b>{fmtWon(reconciled?billed-pg:billed-pg+1000)}</b></div><strong className={reconciled?"ok":"bad"}>{reconciled?"✓ 일치 — 대사 완료":"! 1,000원 불일치"}</strong><Button variant="dark" onClick={()=>setReconciled(true)}>지금 다시 대사하기</Button></div><div className="zero-side"><span>PG 잔액 제로화</span><b>{fmtWon(remain)} 남음</b><p>{remain===0?"✓ 오늘 정산 잔액이 0원입니다.":"로펌 지급과 순수익 송금을 모두 완료하면 0원이 됩니다."}</p><div className="zero-meter"><i style={{width:`${billed?Math.max(0,100-remain/(billed-pg)*100):0}%`}}/></div></div></section><section className="board"><div className="board-title">오늘 결제 건</div><div className="table-scroll"><table className="data-table"><thead><tr><th>의뢰인</th><th>결제일</th><th className="num">결제액</th><th>수단</th><th>상태</th></tr></thead><tbody>{paidToday.map(p=><tr key={p.id}><td>{clientOf(db,p.matterId)?.name}</td><td>{p.paidDate}</td><td className="num">{fmtWon(p.paidAmount)}</td><td>{p.method}</td><td><Badge tone="green">결제완료</Badge></td></tr>)}{paidToday.length===0&&<EmptyRow cols={5} text="오늘 결제 완료 건이 없어 정산금액이 0원입니다."/>}</tbody></table></div></section></>
}

function DocumentsPage({db,update}){
 const registered=db.clients.filter(c=>db.matters.some(m=>m.clientId===c.id&&m.clientRegistered));const [clientId,setClientId]=useState(registered[0]?.id||"");const matter=currentMatter(db,clientId);const rows=matter?db.documents.filter(x=>x.matterId===matter.id).sort((a,b)=>a.no-b.no):[];const done=rows.filter(r=>["수령","해당없음"].includes(r.status)).length;
 function create(){if(!matter)return;update(d=>({...d,documents:[...d.documents,...makeDocs(matter.id,0)]}))}
 return <><PageTitle title="서류 수합" desc="‘상담/사건 선택’ 대신 의뢰인을 선택하면 최근 사건과 15종 서류 체크리스트가 자동 연결됩니다."/><section className="board"><div className="board-tools docs-tools"><Field label="의뢰인 선택"><Select value={clientId} onChange={setClientId}>{registered.map(c=><option key={c.id} value={c.id}>{c.name} · {c.phone}</option>)}</Select></Field><div className="doc-summary"><span>연결 사건 <b>{matter?`${matter.caseType} · ${matter.status}`:"-"}</b></span><span>수합률 <b>{rows.length?Math.round(done/rows.length*100):0}%</b> ({done}/{rows.length||15})</span></div>{matter&&rows.length===0&&<Button onClick={create}>체크리스트 생성</Button>}</div><div className="table-scroll"><table className="data-table wide"><thead><tr><th>No</th><th>서류명</th><th>상태</th><th>수령일</th><th>메모</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.no}</td><td><b>{r.title}</b></td><td><Select value={r.status} onChange={v=>update(d=>({...d,documents:d.documents.map(x=>x.id===r.id?{...x,status:v,receivedAt:v==="수령"?TODAY:x.receivedAt}:x)}))}><option>미수령</option><option>요청</option><option>수령</option><option>보완필요</option><option>해당없음</option></Select></td><td>{r.receivedAt||"-"}</td><td><Input value={r.note} onChange={e=>update(d=>({...d,documents:d.documents.map(x=>x.id===r.id?{...x,note:e.target.value}:x)}))}/></td></tr>)}{rows.length===0&&<EmptyRow cols={5} text="의뢰인을 선택하고 체크리스트를 생성해주세요."/>}</tbody></table></div></section></>
}

function CasesPage({db,update}){
 const [expanded,setExpanded]=useState(null);const [q,setQ]=useState("");const matters=db.matters.filter(m=>m.clientRegistered&&["서류검토중","계약진행중","수임","진행중"].includes(m.status)).filter(m=>{const c=clientOf(db,m.id);return`${c?.name} ${m.caseType} ${m.court}`.toLowerCase().includes(q.toLowerCase())});function getCase(m){return db.cases.find(x=>x.matterId===m.id)}function ensure(m){const f=getCase(m);if(f)return;update(d=>({...d,cases:[...d.cases,{id:id("case"),matterId:m.id,currentStage:"상담/수임",court:m.court,caseNumber:"",filedAt:"",nextDueAt:"",memo:"",updatedAt:new Date().toISOString()}]}))}
 return <><PageTitle title="사건 진행" desc="기본은 게시판형 목록만 보이고, 우측 ▼ 버튼을 눌러야 현재단계·법원·사건번호·기한·메모가 펼쳐집니다."/><section className="board"><div className="board-tools"><SearchBox value={q} onChange={setQ} placeholder="의뢰인·사건유형·법원 검색"/></div><div className="table-scroll"><table className="data-table wide"><thead><tr><th>의뢰인</th><th>사건유형</th><th>담당자</th><th>상태</th><th>최근수정</th><th>다음기한</th><th></th></tr></thead><tbody>{matters.flatMap(m=>{const c=clientOf(db,m.id),cp=getCase(m),is=expanded===m.id;return[<tr key={`${m.id}-main`}><td><b>{c?.name}</b><small className="cell-sub">{c?.phone}</small></td><td>{m.caseType}</td><td>{m.manager}</td><td><Badge tone={tone(m.status)}>{m.status}</Badge></td><td>{cp?.updatedAt?.slice(0,10)||"미생성"}</td><td>{cp?.nextDueAt||"-"}</td><td className="actions"><IconButton onClick={()=>{if(!cp)ensure(m);setExpanded(is?null:m.id)}}>{is?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</IconButton></td></tr>,is&&<tr key={`${m.id}-detail`} className="expanded-row"><td colSpan={7}>{cp?<div className="expand-grid"><Field label="현재단계"><Input value={cp.currentStage} onChange={e=>update(d=>({...d,cases:d.cases.map(x=>x.id===cp.id?{...x,currentStage:e.target.value,updatedAt:new Date().toISOString()}:x)}))}/></Field><Field label="관할법원"><Input value={cp.court} onChange={e=>update(d=>({...d,cases:d.cases.map(x=>x.id===cp.id?{...x,court:e.target.value,updatedAt:new Date().toISOString()}:x)}))}/></Field><Field label="사건번호"><Input value={cp.caseNumber} onChange={e=>update(d=>({...d,cases:d.cases.map(x=>x.id===cp.id?{...x,caseNumber:e.target.value,updatedAt:new Date().toISOString()}:x)}))}/></Field><Field label="다음기한"><Input type="date" value={cp.nextDueAt} onChange={e=>update(d=>({...d,cases:d.cases.map(x=>x.id===cp.id?{...x,nextDueAt:e.target.value,updatedAt:new Date().toISOString()}:x)}))}/></Field><Field label="진행 메모"><textarea className="control textarea" value={cp.memo} onChange={e=>update(d=>({...d,cases:d.cases.map(x=>x.id===cp.id?{...x,memo:e.target.value,updatedAt:new Date().toISOString()}:x)}))}/></Field></div>:<div className="empty-box">사건진행 정보를 생성하는 중입니다.</div>}</td></tr>].filter(Boolean)})}{matters.length===0&&<EmptyRow cols={7}/>}</tbody></table></div></section></>
}

function AnalyticsPage({db}){
 const total=db.matters.length,registered=db.matters.filter(m=>m.clientRegistered).length,retained=db.matters.filter(m=>["수임","진행중","종결(성공)"].includes(m.status)).length,contracts=db.contracts.reduce((s,x)=>s+x.amount,0),paid=db.payments.reduce((s,x)=>s+x.paidAmount,0),billed=db.payments.reduce((s,x)=>s+x.amount,0);const statusRows=matterStatuses.map(s=>({status:s,count:db.matters.filter(m=>m.status===s).length})).filter(x=>x.count);const managerRows=managers.map(m=>{const mids=db.matters.filter(x=>x.manager===m).map(x=>x.id);const b=db.payments.filter(p=>mids.includes(p.matterId)).reduce((s,p)=>s+p.amount,0);const p=db.payments.filter(x=>mids.includes(x.matterId)).reduce((s,x)=>s+x.paidAmount,0);return{name:m,matters:mids.length,billed:b,paid:p,rate:b?p/b*100:0}});
 return <><PageTitle title="데이터 집계" desc="상담 DB → 의뢰인 등록 → 수임/진행 전환과 계약·청구·결제 흐름을 함께 봅니다."/><div className="kpi-row"><Kpi label="전체 상담 DB" value={`${total}건`} delta={8.4} sub={`의뢰인 등록 ${registered}건`}/><Kpi label="의뢰인 등록률" value={fmtPct(total?registered/total*100:0)} delta={4.1} sub="신규 DB → 고객관리 전환" accent="blue"/><Kpi label="수임/진행 전환" value={fmtPct(registered?retained/registered*100:0)} delta={2.7} sub="수임·진행·성공 종결"/><Kpi label="계약 / 결제" value={`${fmtWon(contracts)} / ${fmtWon(paid)}`} delta={billed?paid/billed*100-50:0} sub={`전체 청구 ${fmtWon(billed)}`}/></div><div className="grid-two"><section className="panel"><div className="panel-head"><div><b>상담 상태별 현황</b><span>전체 상담 건 기준</span></div></div>{statusRows.map(r=><div className="dist-row" key={r.status}><div><Badge tone={tone(r.status)}>{r.status}</Badge><i><em style={{width:`${r.count/total*100}%`}}/></i></div><b>{r.count}건</b></div>)}</section><section className="panel"><div className="panel-head"><div><b>담당자별 실적</b><span>청구액 · 결제율</span></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>담당자</th><th>사건</th><th className="num">청구</th><th>결제율</th></tr></thead><tbody>{managerRows.map(r=><tr key={r.name}><td><b>{r.name}</b></td><td>{r.matters}건</td><td className="num">{fmtWon(r.billed)}</td><td><b>{fmtPct(r.rate)}</b></td></tr>)}</tbody></table></div></section></div><div className="grid-two"><section className="panel"><div className="panel-head"><div><b>신규 vs 기존 분납 매출</b><span>최근 6개월 데모 추이</span></div></div><MiniBarChart items={[{label:"4월",value:900000,old:1600000},{label:"5월",value:760000,old:1700000},{label:"6월",value:1200000,old:1900000},{label:"7월",value:1100000,old:2150000},{label:"8월",value:1500000,old:2500000},{label:"9월",value:1800000,old:2800000}]} valueKey="old" secondKey="value" secondLabel="신규"/></section><section className="panel"><div className="panel-head"><div><b>분납 설정 비율</b><span>당월 스냅샷</span></div></div><div className="stacked"><i style={{width:"34%"}}/><i style={{width:"28%"}}/><i style={{width:"24%"}}/><i style={{width:"14%"}}/></div><div className="stack-legend"><span>일시불 34%</span><span>2개월 28%</span><span>3개월 24%</span><span>6개월 14%</span></div><div className="notice amber">분납 비중이 급증하면 현금흐름과 결제실패 위험을 함께 확인하는 구조로 확장할 수 있습니다.</div></section></div></>
}

function BoardPage({db,update,addHistory}){
 const [open,setOpen]=useState(false);const [draft,setDraft]=useState({title:"",body:"",author:"관리자",pinned:false});function save(){if(!draft.title.trim())return;const x={id:id("b"),createdAt:new Date().toISOString(),...draft};update(d=>({...d,posts:[x,...d.posts],history:[addHistory("내부게시판","등록",x.title,"게시글 등록"),...d.history]}));setOpen(false);setDraft({title:"",body:"",author:"관리자",pinned:false})}const rows=[...db.posts].sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.createdAt.localeCompare(a.createdAt));return <><PageTitle title="내부 게시판" desc="팀 공지·처리 기준·업무 메모를 게시판 형식으로 공유합니다." action={<Button onClick={()=>setOpen(true)}><Plus size={14}/>글쓰기</Button>}/><section className="board"><div className="table-scroll"><table className="data-table"><thead><tr><th>구분</th><th>제목</th><th>내용</th><th>작성자</th><th>등록일</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><td>{r.pinned?<Badge tone="blue">공지</Badge>:i+1}</td><td><b>{r.title}</b></td><td className="long-cell">{r.body}</td><td>{r.author}</td><td>{r.createdAt.slice(0,10)}</td></tr>)}</tbody></table></div></section><Modal open={open} title="게시글 작성" onClose={()=>setOpen(false)}><div className="detail-stack"><Field label="제목"><Input value={draft.title} onChange={e=>setDraft(v=>({...v,title:e.target.value}))}/></Field><Field label="본문"><textarea className="control textarea" value={draft.body} onChange={e=>setDraft(v=>({...v,body:e.target.value}))}/></Field><label className="check"><input type="checkbox" checked={draft.pinned} onChange={e=>setDraft(v=>({...v,pinned:e.target.checked}))}/>공지로 고정</label></div><div className="modal-actions"><Button variant="ghost" onClick={()=>setOpen(false)}>취소</Button><Button onClick={save}>저장</Button></div></Modal></>
}

function ChangesPage({db}){const rows=[...db.history].sort((a,b)=>b.createdAt.localeCompare(a.createdAt));return <><PageTitle title="기간별 변동내역" desc="신규 접수·이관·상태변경·상담메모·계약·청구·사건수정 이력을 최신순으로 확인합니다."/><section className="board"><div className="table-scroll"><table className="data-table wide"><thead><tr><th>일시</th><th>메뉴</th><th>작업</th><th>대상</th><th>내용</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.createdAt.slice(0,16).replace("T"," ")}</td><td>{r.category}</td><td><Badge>{r.action}</Badge></td><td><b>{r.target}</b></td><td>{r.detail}</td></tr>)}{rows.length===0&&<EmptyRow cols={5}/>}</tbody></table></div></section></>}

function SettingsPage({db,update}){
 const [popover,setPopover]=useState(false);const enabled=db.settings.caseTypeEnabled;function toggle(k){if(["민사","형사"].includes(k))return;update(d=>({...d,settings:{...d.settings,caseTypeEnabled:{...d.settings.caseTypeEnabled,[k]:!d.settings.caseTypeEnabled[k]}}}))}
 return <><PageTitle title="기준표 / 설정" desc="회생 상담 기준값과 사건유형 노출, 결제/PG 데모 요율을 관리합니다."/><div className="grid-two settings-grid"><section className="panel"><div className="panel-head"><div><b>회생 예상계산 기준</b><span>기준연도 {db.settings.referenceYear} · 데모값</span></div></div>{Object.entries(db.settings.livingCostByHousehold).map(([k,v])=><div className="setting-row" key={k}><span>{k}인 가구 기준 생활비</span><MoneyInput value={v} onChange={n=>update(d=>({...d,settings:{...d.settings,livingCostByHousehold:{...d.settings.livingCostByHousehold,[k]:n}}}))}/></div>)}<div className="notice amber">실운영 전에는 해당 연도의 공식 기준과 내부 업무정책을 검토하여 교체해야 합니다.</div></section><section className="panel"><div className="panel-head"><div><b>매출 구성 카테고리 설정</b><span>로피 고객사 대시보드의 사건유형 설정 구조 반영</span></div><Button variant="ghost" onClick={()=>setPopover(!popover)}>설정 미리보기</Button></div><div className="case-settings">{caseTypes.map(k=><label key={k} className={['민사','형사'].includes(k)?"fixed":""}><input type="checkbox" checked={!!enabled[k]} disabled={['민사','형사'].includes(k)} onChange={()=>toggle(k)}/><span>{k}{['민사','형사'].includes(k)&&<em>기본</em>}</span></label>)}</div><div className="divider"/><div className="setting-row"><span>PG 원가율</span><div className="percent-control"><input className="control" type="number" step="0.01" value={db.settings.pgFeeRate} onChange={e=>update(d=>({...d,settings:{...d.settings,pgFeeRate:Number(e.target.value)}}))}/><b>%</b></div></div><div className="setting-row"><span>서비스 수수료율(데모)</span><div className="percent-control"><input className="control" type="number" step="0.01" value={db.settings.serviceFeeRate} onChange={e=>update(d=>({...d,settings:{...d.settings,serviceFeeRate:Number(e.target.value)}}))}/><b>%</b></div></div><p className="footnote">PG 수수료 및 정산 조건은 실제 계약/정책값을 연결해야 하며 현재 값은 기능 시연용입니다.</p></section></div>{popover&&<Modal open title="매출 구성 카테고리 설정" onClose={()=>setPopover(false)}><p className="modal-help">우리 로펌이 다루는 사건 유형만 선택합니다. 민사·형사는 기본 제공, 개인회생·개인파산·불법사채구제 등은 선택형으로 운용할 수 있습니다.</p><div className="case-settings modal-case">{caseTypes.map(k=><label key={k} className={['민사','형사'].includes(k)?"fixed":""}><input type="checkbox" checked={!!enabled[k]} disabled={['민사','형사'].includes(k)} onChange={()=>toggle(k)}/><span>{k}{['민사','형사'].includes(k)?<em>기본</em>:<em>선택</em>}</span></label>)}</div><div className="modal-actions"><Button onClick={()=>setPopover(false)}>저장</Button></div></Modal>}</>
}

export default function RoPowerAdmin(){
 const {db,update,reset,addHistory}=useDemoDB();const [section,setSection]=useState("dashboard");const [mobileOpen,setMobileOpen]=useState(false);let page=null;
 if(section==="dashboard")page=<Dashboard db={db} update={update} setSection={setSection}/>;
 else if(section==="leads")page=<LeadsPage db={db} update={update} addHistory={addHistory} setSection={setSection}/>;
 else if(section==="customers")page=<CustomersPage db={db} update={update} addHistory={addHistory}/>;
 else if(section==="pipeline")page=<PipelinePage db={db} update={update}/>;
 else if(section==="schedule")page=<SchedulePage db={db}/>;
 else if(section==="contracts")page=<ContractsPage db={db} update={update} addHistory={addHistory}/>;
 else if(section==="payments")page=<PaymentsPage db={db} update={update} addHistory={addHistory}/>;
 else if(section==="settlement")page=<SettlementPage db={db} update={update}/>;
 else if(section==="documents")page=<DocumentsPage db={db} update={update}/>;
 else if(section==="cases")page=<CasesPage db={db} update={update}/>;
 else if(section==="analytics")page=<AnalyticsPage db={db}/>;
 else if(section==="board")page=<BoardPage db={db} update={update} addHistory={addHistory}/>;
 else if(section==="changes")page=<ChangesPage db={db}/>;
 else if(section==="settings")page=<SettingsPage db={db} update={update}/>;
 return <div className="app-shell"><Sidebar section={section} setSection={setSection} mobileOpen={mobileOpen} setMobileOpen={setMobileOpen}/><div className="app-main"><Topbar setMobileOpen={setMobileOpen} db={db} reset={reset}/><main className="content">{page}</main></div></div>
}
