"use client";

import {Fragment,useMemo,useState} from "react";
import {useParams,useSearchParams} from "next/navigation";
import {ChevronDown,ChevronUp,FilePlus2,Plus,Search,UserPlus} from "lucide-react";
import {Badge,Button,Card,Input,Modal,PageHeader} from "@/components/ui";
import {Pagination,pageRows} from "@/components/pagination";
import {
 Asset,assetTypes,CaseProgress,Client,Contract,Debt,debtTypes,documentChecklist,DocumentItem,DocStatus,Manager,managers,Matter,MatterStatus,matterStatuses,matterTypes,nextId,occupations,Payment,PaymentStatus,today,useAdminStore
} from "@/components/store";
import {won} from "@/lib/utils";

const field="h-11 w-full rounded-lg border border-slate-200 bg-white px-3 text-base outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100 sm:h-10 sm:text-sm";
const textarea="min-h-24 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-base outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100 sm:text-sm";
function tone(status:string){if(status.includes("종결")||status==="수임"||status==="진행중"||status==="완료"||status==="수령")return "green" as const;if(status.includes("거절")||status==="부적합"||status==="연체"||status==="보완필요")return "red" as const;if(status.includes("재통화")||status==="부재중"||status==="요청")return "amber" as const;return "blue" as const}
function Label({text,children}:{text:string;children:React.ReactNode}){return <label className="text-sm font-semibold text-slate-700">{text}<div className="mt-1.5">{children}</div></label>}
function NumberInput({value,onChange}:{value:number;onChange:(v:number)=>void}){return <input inputMode="numeric" className={field} value={value?value.toLocaleString("ko-KR"):""} placeholder="0" onChange={e=>{const n=Number(e.target.value.replace(/[^0-9]/g,""));onChange(Number.isFinite(n)?n:0)}}/>}
function SearchBox({value,onChange,placeholder="이름 또는 전화번호 검색"}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <div className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><Input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="pl-9"/></div>}
function clientOf(db:ReturnType<typeof useAdminStore>["db"],matterId:string){const m=db.matters.find(x=>x.id===matterId);return m?db.clients.find(c=>c.id===m.clientId):undefined}
function currentMatterForClient(db:ReturnType<typeof useAdminStore>["db"],clientId:string){return [...db.matters].filter(m=>m.clientId===clientId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0]}
function calc(db:ReturnType<typeof useAdminStore>["db"],m:Matter){const income=(m.monthlyIncome||0)+(m.sideIncome||0)+(m.pensionIncome||0);const living=db.settings.livingCostByHousehold[String(m.householdSize)]??db.settings.livingCostByHousehold["6"]??0;const disposable=Math.max(0,income-living-(m.extraDeduction||0));const assets=db.assets.filter(a=>a.matterId===m.id);const assetTotal=assets.reduce((s,a)=>s+a.value,0);const securedOnAssets=assets.reduce((s,a)=>s+a.securedAmount,0);const liquidation=Math.max(0,assetTotal-securedOnAssets);const debts=db.debts.filter(d=>d.matterId===m.id);const unsecured=debts.filter(d=>["신용채무","개인채무","기타"].includes(d.type)).reduce((s,d)=>s+d.amount,0);const months=Math.max(1,m.repaymentMonths||36);const incomePlan=disposable*months;const total=Math.max(incomePlan,liquidation);const planned=unsecured>0?Math.min(unsecured,total):total;const monthly=planned/months;const relief=Math.max(0,unsecured-planned);const reliefRate=unsecured?relief/unsecured*100:0;return{income,living,disposable,assetTotal,liquidation,unsecured,planned,monthly,relief,reliefRate}}
function addDocsForMatter(matterId:string):DocumentItem[]{return documentChecklist.map(x=>({id:nextId("doc"),matterId,no:x[0],title:x[1],source:x[2],condition:x[3],status:"미수령",receivedAt:"",note:""}))}

export default function Section(){const {section}=useParams<{section:string}>();if(section==="leads")return <Leads/>;if(section==="customers")return <Customers/>;if(section==="contracts")return <Contracts/>;if(section==="payments")return <Payments/>;if(section==="documents")return <Documents/>;if(section==="cases")return <Cases/>;if(section==="board")return <Board/>;if(section==="changes")return <Changes/>;if(section==="analytics")return <Analytics/>;if(section==="settings")return <Settings/>;return <Customers/>}

function Leads(){
 const {db,update,addHistory}=useAdminStore();const [q,setQ]=useState("");const [open,setOpen]=useState(false);const [draft,setDraft]=useState({name:"",phone:"",caseType:"개인회생",source:"온라인 광고",manager:"상담1",memo:""});
 const rows=db.matters.filter(m=>!m.clientRegistered).filter(m=>{const c=db.clients.find(x=>x.id===m.clientId);return `${c?.name} ${c?.phone} ${m.source}`.toLowerCase().includes(q.toLowerCase())}).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
 function register(m:Matter){const c=db.clients.find(x=>x.id===m.clientId);if(!c)return;update(d=>({...d,matters:d.matters.map(x=>x.id===m.id?{...x,clientRegistered:true,clientRegisteredAt:today(),status:x.status==="신규접수"?"상담예정":x.status}:x),history:[addHistory("신규 DB","의뢰인 등록",c.name,"신규 상담 DB를 상담 / 의뢰인 관리로 이관했습니다."),...d.history]}))}
 function save(){if(!draft.name.trim()||!draft.phone.trim())return alert("이름과 연락처를 입력해주세요.");const cid=nextId("c");const mid=nextId("m");const now=new Date().toISOString();const client:Client={id:cid,createdAt:now,name:draft.name.trim(),phone:draft.phone.trim(),birthDate:"",gender:"미입력",address:"",spouse:"",children:"",dependents:1,healthIssue:"",manager:draft.manager as Manager,memo:draft.memo};const matter:Matter={id:mid,clientId:cid,createdAt:now,caseType:draft.caseType as Matter["caseType"],status:"신규접수",source:draft.source,manager:draft.manager as Manager,consultDate:"",nextActionDate:today(),nextActionType:"첫 연락",occupation:"미입력",companyName:"",employmentInfo:"",monthlyIncome:0,sideIncome:0,pensionIncome:0,extraDeduction:0,repaymentMonths:36,householdSize:1,court:"미지정",memo:draft.memo,firstContactDone:false,contactAttempts:0,clientRegistered:false,clientRegisteredAt:""};update(d=>({...d,clients:[client,...d.clients],matters:[matter,...d.matters],history:[addHistory("신규 DB","등록",client.name,"신규 상담 DB를 등록했습니다."),...d.history]}));setOpen(false);setDraft({name:"",phone:"",caseType:"개인회생",source:"온라인 광고",manager:"상담1",memo:""})}
 return <><PageHeader title="신규 상담 DB" description="신규 DB는 여기서 먼저 확인한 뒤 ‘의뢰인 등록’을 눌러 상담 / 의뢰인 관리로 넘깁니다." action={<Button onClick={()=>setOpen(true)}><Plus size={16}/>신규 DB 등록</Button>}/>
  <Card className="mb-4 overflow-hidden"><div className="grid grid-cols-4 divide-x divide-slate-200 border-b border-slate-200 bg-slate-50 text-center text-xs font-bold text-slate-500"><div className="px-3 py-3 text-blue-700">① 신규 DB 접수</div><div className="px-3 py-3">② 연락 / 상담 확인</div><div className="px-3 py-3">③ 의뢰인 등록</div><div className="px-3 py-3">④ 상담 / 의뢰인 관리</div></div><div className="px-4 py-3 text-xs text-slate-500">DB를 확인하고 담당자·상태를 정리한 뒤 <b className="text-blue-700">의뢰인 등록</b> 버튼을 누르면 고객 관리 목록으로 이동합니다.</div></Card>
  <Card className="overflow-hidden"><div className="border-b border-slate-100 p-4"><SearchBox value={q} onChange={setQ}/></div><div className="overflow-x-auto"><table className="admin-responsive-table w-full text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3 text-left">접수일</th><th className="px-4 py-3 text-left">이름</th><th className="px-4 py-3 text-left">연락처</th><th className="px-4 py-3 text-left">사건유형</th><th className="px-4 py-3 text-left">상태</th><th className="px-4 py-3 text-left">담당자</th><th className="px-4 py-3 text-left">유입</th><th className="px-4 py-3 text-right">이관</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.length===0?<tr><td colSpan={8} className="px-4 py-12 text-center text-slate-400">신규 상담 DB가 없습니다.</td></tr>:rows.map(m=>{const c=db.clients.find(x=>x.id===m.clientId);return <tr key={m.id} className="hover:bg-slate-50"><td className="px-4 py-3 text-slate-500">{m.createdAt.slice(0,10)}</td><td className="px-4 py-3 font-bold">{c?.name}</td><td className="px-4 py-3">{c?.phone}</td><td className="px-4 py-3">{m.caseType}</td><td className="px-4 py-3"><Badge tone={tone(m.status)}>{m.status}</Badge></td><td className="px-4 py-3">{m.manager}</td><td className="px-4 py-3">{m.source}</td><td className="px-4 py-3 text-right"><Button onClick={()=>register(m)}><UserPlus size={15}/>의뢰인 등록</Button></td></tr>})}</tbody></table></div></Card>
  <Modal open={open} title="신규 상담 DB 등록" onClose={()=>setOpen(false)}><div className="grid gap-4 sm:grid-cols-2"><Label text="이름"><Input value={draft.name} onChange={e=>setDraft(v=>({...v,name:e.target.value}))}/></Label><Label text="연락처"><Input value={draft.phone} onChange={e=>setDraft(v=>({...v,phone:e.target.value}))}/></Label><Label text="사건유형"><select className={field} value={draft.caseType} onChange={e=>setDraft(v=>({...v,caseType:e.target.value}))}>{matterTypes.map(x=><option key={x}>{x}</option>)}</select></Label><Label text="담당자"><select className={field} value={draft.manager} onChange={e=>setDraft(v=>({...v,manager:e.target.value}))}>{managers.map(x=><option key={x}>{x}</option>)}</select></Label><Label text="유입경로"><Input value={draft.source} onChange={e=>setDraft(v=>({...v,source:e.target.value}))}/></Label><Label text="메모"><Input value={draft.memo} onChange={e=>setDraft(v=>({...v,memo:e.target.value}))}/></Label></div><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setOpen(false)}>취소</Button><Button onClick={save}>저장</Button></div></Modal>
 </>
}

function Customers(){
 const {db,update,addHistory}=useAdminStore();const searchParams=useSearchParams();const [selected,setSelected]=useState<string|null>(()=>searchParams.get("client"));const [q,setQ]=useState("");const [status,setStatus]=useState("전체");const [page,setPage]=useState(1);
 const rows=db.matters.filter(m=>m.clientRegistered).filter(m=>{const c=db.clients.find(x=>x.id===m.clientId);return (status==="전체"||m.status===status)&&`${c?.name} ${c?.phone} ${m.caseType} ${m.manager}`.toLowerCase().includes(q.toLowerCase())}).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
 return <><PageHeader title="상담 / 의뢰인 관리" description="신규 DB에서 ‘의뢰인 등록’ 처리된 건만 표시됩니다. 이름을 눌러 상담·소득·재산·채무·계산·서류·사건 진행을 확인합니다."/>
  <Card className="overflow-hidden"><div className="grid gap-3 border-b border-slate-100 p-4 md:grid-cols-[1fr_190px]"><SearchBox value={q} onChange={v=>{setQ(v);setPage(1)}}/><select className={field} value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option>전체</option>{matterStatuses.map(x=><option key={x}>{x}</option>)}</select></div><div className="overflow-x-auto"><table className="admin-responsive-table w-full text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3 text-left">이름</th><th className="px-4 py-3 text-left">연락처</th><th className="px-4 py-3 text-left">사건유형</th><th className="px-4 py-3 text-left">상태</th><th className="px-4 py-3 text-left">상담일</th><th className="px-4 py-3 text-left">다음 액션</th><th className="px-4 py-3 text-left">담당자</th><th className="px-4 py-3 text-right">상세</th></tr></thead><tbody className="divide-y divide-slate-100">{pageRows(rows,page,10).map(m=>{const c=db.clients.find(x=>x.id===m.clientId);return <tr key={m.id} className="hover:bg-slate-50"><td className="px-4 py-3 font-bold"><button className="text-blue-700 hover:underline" onClick={()=>setSelected(c?.id||null)}>{c?.name}</button></td><td className="px-4 py-3">{c?.phone}</td><td className="px-4 py-3">{m.caseType}</td><td className="px-4 py-3"><select className="h-8 rounded-md border border-slate-200 bg-white px-2 text-xs" value={m.status} onChange={e=>{const next=e.target.value as MatterStatus;update(d=>({...d,matters:d.matters.map(x=>x.id===m.id?{...x,status:next}:x),history:[addHistory("의뢰인 관리","상태변경",c?.name||"",`${m.status} → ${next}`),...d.history]}))}}>{matterStatuses.map(x=><option key={x}>{x}</option>)}</select></td><td className="px-4 py-3">{m.consultDate||"-"}</td><td className="px-4 py-3"><div className="font-semibold">{m.nextActionDate||"-"}</div><div className="text-xs text-slate-400">{m.nextActionType||"-"}</div></td><td className="px-4 py-3">{m.manager}</td><td className="px-4 py-3 text-right"><Button variant="secondary" onClick={()=>setSelected(c?.id||null)}>상세보기</Button></td></tr>})}{rows.length===0&&<tr><td colSpan={8} className="px-4 py-12 text-center text-slate-400">조건에 맞는 의뢰인이 없습니다.</td></tr>}</tbody></table></div><Pagination page={page} total={rows.length} pageSize={10} onChange={setPage}/></Card>
  {selected&&<ClientDetail clientId={selected} onClose={()=>setSelected(null)} db={db} update={update} addHistory={addHistory}/>} 
 </>
}

function ClientDetail({clientId,onClose,db,update,addHistory}:{clientId:string;onClose:()=>void;db:ReturnType<typeof useAdminStore>["db"];update:ReturnType<typeof useAdminStore>["update"];addHistory:ReturnType<typeof useAdminStore>["addHistory"]}){
 const client=db.clients.find(c=>c.id===clientId);const matter=currentMatterForClient(db,clientId);const [tab,setTab]=useState("요약");if(!client||!matter)return null;const matterId=matter.id;const c=calc(db,matter);const tabs=["요약","인적사항","소득","재산","채무","예상 변제계획","상담내역","서류","사건진행"];
 function patchClient(p:Partial<Client>){update(d=>({...d,clients:d.clients.map(x=>x.id===clientId?{...x,...p}:x)}))}
 function patchMatter(p:Partial<Matter>){update(d=>({...d,matters:d.matters.map(x=>x.id===matterId?{...x,...p}:x)}))}
 return <Modal open title={`${client.name} · ${matter.caseType}`} onClose={onClose}><div className="-mx-5 -mt-1 mb-4 overflow-x-auto border-b border-slate-100 px-5"><div className="flex min-w-max gap-1">{tabs.map(x=><button key={x} onClick={()=>setTab(x)} className={`border-b-2 px-3 py-3 text-sm font-semibold ${tab===x?"border-blue-600 text-blue-700":"border-transparent text-slate-500"}`}>{x}</button>)}</div></div>
  {tab==="요약"&&<div className="space-y-4"><div className="overflow-hidden rounded-xl border border-slate-200"><div className="grid sm:grid-cols-2"><Info label="상태" value={matter.status}/><Info label="담당자" value={matter.manager}/><Info label="다음 액션" value={`${matter.nextActionDate||"-"} · ${matter.nextActionType||"-"}`}/><Info label="관할법원" value={matter.court}/><Info label="월 총소득" value={won(c.income)}/><Info label="신용채무" value={won(c.unsecured)}/></div></div><Label text="메모"><textarea className={textarea} value={matter.memo} onChange={e=>patchMatter({memo:e.target.value})}/></Label><div className="text-xs text-slate-400">입력 내용은 데모 브라우저에만 저장됩니다.</div></div>}
  {tab==="인적사항"&&<div className="grid gap-4 sm:grid-cols-2"><Label text="이름"><Input value={client.name} onChange={e=>patchClient({name:e.target.value})}/></Label><Label text="연락처"><Input value={client.phone} onChange={e=>patchClient({phone:e.target.value})}/></Label><Label text="생년월일"><Input type="date" value={client.birthDate} onChange={e=>patchClient({birthDate:e.target.value})}/></Label><Label text="주소"><Input value={client.address} onChange={e=>patchClient({address:e.target.value})}/></Label><Label text="배우자"><Input value={client.spouse} onChange={e=>patchClient({spouse:e.target.value})}/></Label><Label text="자녀"><Input value={client.children} onChange={e=>patchClient({children:e.target.value})}/></Label><Label text="부양가족 수"><NumberInput value={client.dependents} onChange={v=>patchClient({dependents:v})}/></Label><Label text="특이 건강사항"><Input value={client.healthIssue} onChange={e=>patchClient({healthIssue:e.target.value})}/></Label></div>}
  {tab==="소득"&&<div className="grid gap-4 sm:grid-cols-2"><Label text="직업"><select className={field} value={matter.occupation} onChange={e=>patchMatter({occupation:e.target.value as Matter["occupation"]})}>{occupations.map(x=><option key={x}>{x}</option>)}</select></Label><Label text="회사 / 사업장"><Input value={matter.companyName} onChange={e=>patchMatter({companyName:e.target.value})}/></Label><Label text="월평균소득"><NumberInput value={matter.monthlyIncome} onChange={v=>patchMatter({monthlyIncome:v})}/></Label><Label text="부업소득"><NumberInput value={matter.sideIncome} onChange={v=>patchMatter({sideIncome:v})}/></Label><Label text="연금소득"><NumberInput value={matter.pensionIncome} onChange={v=>patchMatter({pensionIncome:v})}/></Label><Label text="기타 공제"><NumberInput value={matter.extraDeduction} onChange={v=>patchMatter({extraDeduction:v})}/></Label></div>}
  {tab==="재산"&&<AssetEditor db={db} matter={matter} update={update}/>} 
  {tab==="채무"&&<DebtEditor db={db} matter={matter} update={update}/>} 
  {tab==="예상 변제계획"&&<div className="space-y-4"><div className="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-xs leading-5 text-amber-900">아래 값은 상담용 추정치이며 최종 변제금·탕감액·진행 가능 여부를 확정하는 법률판단이 아닙니다.</div><div className="overflow-hidden rounded-xl border border-slate-200"><div className="grid sm:grid-cols-2"><Info label="월 총소득" value={won(c.income)}/><Info label="기준 생활비" value={won(c.living)}/><Info label="월 가용소득" value={won(c.disposable)}/><Info label="청산가치 추정" value={won(c.liquidation)}/><Info label="추정 월 변제금" value={won(c.monthly)}/><Info label="추정 총 변제액" value={won(c.planned)}/><Info label="추정 탕감액" value={won(c.relief)}/><Info label="추정 탕감률" value={`${c.reliefRate.toFixed(1)}%`}/></div></div><div className="grid gap-4 sm:grid-cols-2"><Label text="가구원 수"><NumberInput value={matter.householdSize} onChange={v=>patchMatter({householdSize:Math.max(1,v)})}/></Label><Label text="변제기간(개월)"><NumberInput value={matter.repaymentMonths} onChange={v=>patchMatter({repaymentMonths:Math.max(1,v)})}/></Label></div></div>}
  {tab==="상담내역"&&<ConsultationLogs db={db} matter={matter} update={update} addHistory={addHistory} client={client}/>} 
  {tab==="서류"&&<MiniDocuments db={db} matter={matter} update={update}/>} 
  {tab==="사건진행"&&<MiniCase db={db} matter={matter} update={update}/>} 
 </Modal>
}
function Info({label,value}:{label:string;value:string}){return <div className="border-b border-slate-100 px-4 py-3 last:border-b-0 sm:border-r"><div className="text-[11px] font-semibold text-slate-400">{label}</div><div className="mt-1 text-sm font-bold text-slate-800">{value||"-"}</div></div>}

function AssetEditor({db,matter,update}:{db:ReturnType<typeof useAdminStore>["db"];matter:Matter;update:ReturnType<typeof useAdminStore>["update"]}){const rows=db.assets.filter(x=>x.matterId===matter.id);function add(){const x:Asset={id:nextId("a"),matterId:matter.id,type:"기타",value:0,securedAmount:0,note:""};update(d=>({...d,assets:[...d.assets,x]}))}function patch(id:string,p:Partial<Asset>){update(d=>({...d,assets:d.assets.map(x=>x.id===id?{...x,...p}:x)}))}return <div><div className="mb-3 flex justify-end"><Button variant="secondary" onClick={add}><Plus size={15}/>재산 추가</Button></div><div className="overflow-x-auto rounded-xl border border-slate-200"><table className="admin-responsive-table w-full text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-3 py-2 text-left">종류</th><th className="px-3 py-2 text-left">가액</th><th className="px-3 py-2 text-left">담보액</th><th className="px-3 py-2 text-left">비고</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(r=><tr key={r.id}><td className="p-2"><select className={field} value={r.type} onChange={e=>patch(r.id,{type:e.target.value})}>{assetTypes.map(x=><option key={x}>{x}</option>)}</select></td><td className="p-2"><NumberInput value={r.value} onChange={v=>patch(r.id,{value:v})}/></td><td className="p-2"><NumberInput value={r.securedAmount} onChange={v=>patch(r.id,{securedAmount:v})}/></td><td className="p-2"><Input value={r.note} onChange={e=>patch(r.id,{note:e.target.value})}/></td></tr>)}</tbody></table></div></div>}
function DebtEditor({db,matter,update}:{db:ReturnType<typeof useAdminStore>["db"];matter:Matter;update:ReturnType<typeof useAdminStore>["update"]}){const rows=db.debts.filter(x=>x.matterId===matter.id);function add(){const x:Debt={id:nextId("d"),matterId:matter.id,type:"신용채무",creditor:"",amount:0,note:""};update(d=>({...d,debts:[...d.debts,x]}))}function patch(id:string,p:Partial<Debt>){update(d=>({...d,debts:d.debts.map(x=>x.id===id?{...x,...p}:x)}))}return <div><div className="mb-3 flex justify-end"><Button variant="secondary" onClick={add}><Plus size={15}/>채무 추가</Button></div><div className="overflow-x-auto rounded-xl border border-slate-200"><table className="admin-responsive-table w-full text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-3 py-2 text-left">구분</th><th className="px-3 py-2 text-left">채권자</th><th className="px-3 py-2 text-left">금액</th><th className="px-3 py-2 text-left">비고</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(r=><tr key={r.id}><td className="p-2"><select className={field} value={r.type} onChange={e=>patch(r.id,{type:e.target.value})}>{debtTypes.map(x=><option key={x}>{x}</option>)}</select></td><td className="p-2"><Input value={r.creditor} onChange={e=>patch(r.id,{creditor:e.target.value})}/></td><td className="p-2"><NumberInput value={r.amount} onChange={v=>patch(r.id,{amount:v})}/></td><td className="p-2"><Input value={r.note} onChange={e=>patch(r.id,{note:e.target.value})}/></td></tr>)}</tbody></table></div></div>}
function ConsultationLogs({db,matter,update,addHistory,client}:{db:ReturnType<typeof useAdminStore>["db"];matter:Matter;update:ReturnType<typeof useAdminStore>["update"];addHistory:ReturnType<typeof useAdminStore>["addHistory"];client:Client}){const [body,setBody]=useState("");const rows=db.logs.filter(x=>x.matterId===matter.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));function add(){if(!body.trim())return;const l={id:nextId("log"),matterId:matter.id,createdAt:new Date().toISOString(),author:matter.manager,kind:"상담메모",body:body.trim()};update(d=>({...d,logs:[l,...d.logs],history:[addHistory("의뢰인 관리","상담메모",client.name,body.trim()),...d.history]}));setBody("")}return <div><div className="flex gap-2"><Input value={body} onChange={e=>setBody(e.target.value)} placeholder="상담메모 입력"/><Button onClick={add}>추가</Button></div><div className="mt-4 divide-y divide-slate-100 rounded-xl border border-slate-200">{rows.map(r=><div key={r.id} className="px-4 py-3"><div className="flex justify-between text-xs text-slate-400"><span>{r.kind} · {r.author}</span><span>{r.createdAt.slice(0,16).replace("T"," ")}</span></div><div className="mt-1 text-sm leading-6 text-slate-700">{r.body}</div></div>)}</div></div>}
function MiniDocuments({db,matter,update}:{db:ReturnType<typeof useAdminStore>["db"];matter:Matter;update:ReturnType<typeof useAdminStore>["update"]}){let rows=db.documents.filter(x=>x.matterId===matter.id);function create(){update(d=>({...d,documents:[...d.documents,...addDocsForMatter(matter.id)]}))}if(rows.length===0)return <div className="rounded-xl border border-dashed border-slate-300 p-8 text-center"><div className="text-sm text-slate-500">서류 체크리스트가 아직 없습니다.</div><Button className="mt-3" onClick={create}><FilePlus2 size={15}/>기본 체크리스트 생성</Button></div>;return <div className="overflow-x-auto rounded-xl border border-slate-200"><table className="admin-responsive-table w-full text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-3 py-2">No</th><th className="px-3 py-2 text-left">서류</th><th className="px-3 py-2">상태</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(r=><tr key={r.id}><td className="px-3 py-2 text-center">{r.no}</td><td className="px-3 py-2">{r.title}</td><td className="px-3 py-2"><select className="h-8 rounded-md border border-slate-200 bg-white px-2 text-xs" value={r.status} onChange={e=>update(d=>({...d,documents:d.documents.map(x=>x.id===r.id?{...x,status:e.target.value as DocStatus,receivedAt:e.target.value==="수령"?today():x.receivedAt}:x)}))}>{["미수령","요청","수령","보완필요","해당없음"].map(x=><option key={x}>{x}</option>)}</select></td></tr>)}</tbody></table></div>}
function MiniCase({db,matter,update}:{db:ReturnType<typeof useAdminStore>["db"];matter:Matter;update:ReturnType<typeof useAdminStore>["update"]}){const row=db.cases.find(x=>x.matterId===matter.id);function create(){const x:CaseProgress={id:nextId("case"),matterId:matter.id,currentStage:"상담/수임",court:matter.court,caseNumber:"",filedAt:"",nextDueAt:"",memo:"",updatedAt:new Date().toISOString()};update(d=>({...d,cases:[...d.cases,x]}))}if(!row)return <div className="rounded-xl border border-dashed border-slate-300 p-8 text-center"><div className="text-sm text-slate-500">사건진행 레코드가 없습니다.</div><Button className="mt-3" onClick={create}>사건진행 생성</Button></div>;function patch(p:Partial<CaseProgress>){update(d=>({...d,cases:d.cases.map(x=>x.id===row.id?{...x,...p,updatedAt:new Date().toISOString()}:x)}))}return <div className="grid gap-4 sm:grid-cols-2"><Label text="현재단계"><Input value={row.currentStage} onChange={e=>patch({currentStage:e.target.value})}/></Label><Label text="관할법원"><Input value={row.court} onChange={e=>patch({court:e.target.value})}/></Label><Label text="사건번호"><Input value={row.caseNumber} onChange={e=>patch({caseNumber:e.target.value})}/></Label><Label text="다음기한"><Input type="date" value={row.nextDueAt} onChange={e=>patch({nextDueAt:e.target.value})}/></Label><div className="sm:col-span-2"><Label text="진행메모"><textarea className={textarea} value={row.memo} onChange={e=>patch({memo:e.target.value})}/></Label></div></div>}

function Contracts(){
 const {db,update,addHistory}=useAdminStore();const [open,setOpen]=useState(false);const matters=db.matters.filter(m=>m.clientRegistered);const [draft,setDraft]=useState({matterId:matters[0]?.id||"",contractAmount:0,upfrontAmount:0,installmentCount:3,paymentMethod:"분납"});
 const rows=[...db.contracts].sort((a,b)=>b.contractDate.localeCompare(a.contractDate));function save(){if(!draft.matterId)return;const x:Contract={id:nextId("ct"),matterId:draft.matterId,contractDate:today(),contractAmount:draft.contractAmount,paymentMethod:draft.paymentMethod,upfrontAmount:draft.upfrontAmount,installmentCount:draft.installmentCount,status:"계약완료",memo:""};const c=clientOf(db,draft.matterId);update(d=>({...d,contracts:[x,...d.contracts],matters:d.matters.map(m=>m.id===draft.matterId?{...m,status:"수임"}:m),documents:d.documents.some(z=>z.matterId===draft.matterId)?d.documents:[...d.documents,...addDocsForMatter(draft.matterId)],history:[addHistory("계약 관리","등록",c?.name||"",`계약금액 ${won(draft.contractAmount)}`),...d.history]}));setOpen(false)}
 return <><PageHeader title="계약 관리" description="의뢰인별 계약금액·계약상태·분납 조건을 관리합니다." action={<Button onClick={()=>setOpen(true)}><Plus size={15}/>계약 등록</Button>}/><Card className="overflow-hidden"><div className="overflow-x-auto"><table className="admin-responsive-table w-full text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3 text-left">계약일</th><th className="px-4 py-3 text-left">의뢰인</th><th className="px-4 py-3 text-left">사건유형</th><th className="px-4 py-3 text-right">계약금액</th><th className="px-4 py-3 text-right">선납금</th><th className="px-4 py-3 text-center">분납</th><th className="px-4 py-3 text-left">상태</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(r=>{const m=db.matters.find(x=>x.id===r.matterId);const c=m?db.clients.find(x=>x.id===m.clientId):undefined;return <tr key={r.id} className="hover:bg-slate-50"><td className="px-4 py-3">{r.contractDate}</td><td className="px-4 py-3 font-bold">{c?.name}</td><td className="px-4 py-3">{m?.caseType}</td><td className="px-4 py-3 text-right font-bold">{won(r.contractAmount)}</td><td className="px-4 py-3 text-right">{won(r.upfrontAmount)}</td><td className="px-4 py-3 text-center">{r.installmentCount}회</td><td className="px-4 py-3"><Badge tone={tone(r.status)}>{r.status}</Badge></td></tr>})}</tbody></table></div></Card><Modal open={open} title="계약 등록" onClose={()=>setOpen(false)}><div className="grid gap-4 sm:grid-cols-2"><Label text="의뢰인"><select className={field} value={draft.matterId} onChange={e=>setDraft(v=>({...v,matterId:e.target.value}))}>{matters.map(m=>{const c=db.clients.find(x=>x.id===m.clientId);return <option key={m.id} value={m.id}>{c?.name} · {m.caseType}</option>})}</select></Label><Label text="결제방식"><select className={field} value={draft.paymentMethod} onChange={e=>setDraft(v=>({...v,paymentMethod:e.target.value}))}><option>분납</option><option>일시납</option><option>카드</option></select></Label><Label text="계약금액"><NumberInput value={draft.contractAmount} onChange={v=>setDraft(x=>({...x,contractAmount:v}))}/></Label><Label text="선납금"><NumberInput value={draft.upfrontAmount} onChange={v=>setDraft(x=>({...x,upfrontAmount:v}))}/></Label><Label text="분납회차"><NumberInput value={draft.installmentCount} onChange={v=>setDraft(x=>({...x,installmentCount:Math.max(1,v)}))}/></Label></div><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setOpen(false)}>취소</Button><Button onClick={save}>저장</Button></div></Modal></>
}

function Payments(){
 const {db,update,addHistory}=useAdminStore();const [open,setOpen]=useState(false);const matters=db.matters.filter(m=>m.clientRegistered);const [draft,setDraft]=useState({matterId:matters[0]?.id||"",dueDate:today(),amount:0,method:"계좌이체",memo:""});const rows=[...db.payments].sort((a,b)=>a.dueDate.localeCompare(b.dueDate));function save(){if(!draft.matterId)return;const x:Payment={id:nextId("p"),matterId:draft.matterId,dueDate:draft.dueDate,amount:draft.amount,paidAmount:0,paidDate:"",status:"예정",method:draft.method,memo:draft.memo};const c=clientOf(db,draft.matterId);update(d=>({...d,payments:[...d.payments,x],history:[addHistory("입금 / 분납 관리","등록",c?.name||"",`${draft.dueDate} ${won(draft.amount)}`),...d.history]}));setOpen(false)}function patch(id:string,p:Partial<Payment>){update(d=>({...d,payments:d.payments.map(x=>x.id===id?{...x,...p}:x)}))}
 return <><PageHeader title="입금 / 분납 관리" description="계약 후 예정 입금과 실제 입금 상태를 한 게시판에서 관리합니다." action={<Button onClick={()=>setOpen(true)}><Plus size={15}/>입금 일정 추가</Button>}/><Card className="overflow-hidden"><div className="overflow-x-auto"><table className="admin-responsive-table w-full text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3 text-left">예정일</th><th className="px-4 py-3 text-left">의뢰인</th><th className="px-4 py-3 text-right">예정금액</th><th className="px-4 py-3 text-right">실입금</th><th className="px-4 py-3 text-left">입금일</th><th className="px-4 py-3 text-left">상태</th><th className="px-4 py-3 text-left">결제방법</th><th className="px-4 py-3 text-left">비고</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(r=>{const c=clientOf(db,r.matterId);return <tr key={r.id} className="hover:bg-slate-50"><td className="px-4 py-3 font-semibold">{r.dueDate}</td><td className="px-4 py-3 font-bold">{c?.name}</td><td className="px-4 py-3 text-right">{won(r.amount)}</td><td className="px-4 py-3 text-right"><button className="font-bold text-blue-700" onClick={()=>{const paid=r.status==="완료"?0:r.amount;patch(r.id,{status:r.status==="완료"?"예정":"완료",paidAmount:paid,paidDate:paid?today():""})}}>{won(r.paidAmount)}</button></td><td className="px-4 py-3">{r.paidDate||"-"}</td><td className="px-4 py-3"><select className="h-8 rounded-md border border-slate-200 bg-white px-2 text-xs" value={r.status} onChange={e=>patch(r.id,{status:e.target.value as PaymentStatus})}>{["예정","완료","연체","취소"].map(x=><option key={x}>{x}</option>)}</select></td><td className="px-4 py-3">{r.method}</td><td className="px-4 py-3 text-slate-500">{r.memo}</td></tr>})}</tbody></table></div></Card><Modal open={open} title="입금 일정 추가" onClose={()=>setOpen(false)}><div className="grid gap-4 sm:grid-cols-2"><Label text="의뢰인"><select className={field} value={draft.matterId} onChange={e=>setDraft(v=>({...v,matterId:e.target.value}))}>{matters.map(m=>{const c=db.clients.find(x=>x.id===m.clientId);return <option key={m.id} value={m.id}>{c?.name} · {m.caseType}</option>})}</select></Label><Label text="예정일"><Input type="date" value={draft.dueDate} onChange={e=>setDraft(v=>({...v,dueDate:e.target.value}))}/></Label><Label text="예정금액"><NumberInput value={draft.amount} onChange={v=>setDraft(x=>({...x,amount:v}))}/></Label><Label text="결제방법"><select className={field} value={draft.method} onChange={e=>setDraft(v=>({...v,method:e.target.value}))}><option>계좌이체</option><option>카드</option><option>현금</option><option>기타</option></select></Label><div className="sm:col-span-2"><Label text="비고"><Input value={draft.memo} onChange={e=>setDraft(v=>({...v,memo:e.target.value}))}/></Label></div></div><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setOpen(false)}>취소</Button><Button onClick={save}>저장</Button></div></Modal></>
}

function Documents(){
 const {db,update}=useAdminStore();const registeredClients=db.clients.filter(c=>db.matters.some(m=>m.clientId===c.id&&m.clientRegistered));const [clientId,setClientId]=useState(registeredClients[0]?.id||"");const matter=currentMatterForClient(db,clientId);const rows=matter?db.documents.filter(x=>x.matterId===matter.id).sort((a,b)=>a.no-b.no):[];function create(){if(!matter)return;update(d=>({...d,documents:[...d.documents,...addDocsForMatter(matter.id)]}))}function patch(id:string,p:Partial<DocumentItem>){update(d=>({...d,documents:d.documents.map(x=>x.id===id?{...x,...p}:x)}))}
 const done=rows.filter(r=>r.status==="수령"||r.status==="해당없음").length;
 return <><PageHeader title="서류 수합" description="‘상담/사건 선택’ 대신 의뢰인만 선택하면 해당 의뢰인의 최근 사건과 서류목록이 자동으로 연결됩니다."/><Card className="mb-4 overflow-hidden"><div className="grid items-end gap-3 p-4 md:grid-cols-[minmax(240px,380px)_1fr_auto]"><Label text="의뢰인 선택"><select className={field} value={clientId} onChange={e=>setClientId(e.target.value)}>{registeredClients.map(c=><option key={c.id} value={c.id}>{c.name} · {c.phone}</option>)}</select></Label><div className="text-sm text-slate-500"><b className="text-slate-800">연결 사건:</b> {matter?`${matter.caseType} · ${matter.status} · ${matter.manager}`:"-"}<div className="mt-1 text-xs">수합 {done}/{rows.length||documentChecklist.length}건</div></div>{matter&&rows.length===0&&<Button onClick={create}><FilePlus2 size={15}/>체크리스트 생성</Button>}</div></Card><Card className="overflow-hidden"><div className="overflow-x-auto"><table className="admin-responsive-table w-full text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3 text-center">No</th><th className="px-4 py-3 text-left">서류명</th><th className="px-4 py-3 text-left">발급/출처</th><th className="px-4 py-3 text-left">확인사항</th><th className="px-4 py-3 text-left">상태</th><th className="px-4 py-3 text-left">수령일</th><th className="px-4 py-3 text-left">메모</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.length===0?<tr><td colSpan={7} className="px-4 py-12 text-center text-slate-400">의뢰인을 선택하고 체크리스트를 생성해주세요.</td></tr>:rows.map(r=><tr key={r.id} className="hover:bg-slate-50"><td className="px-4 py-3 text-center">{r.no}</td><td className="px-4 py-3 font-semibold">{r.title}</td><td className="px-4 py-3">{r.source}</td><td className="px-4 py-3 text-slate-500">{r.condition}</td><td className="px-4 py-3"><select className="h-8 rounded-md border border-slate-200 bg-white px-2 text-xs" value={r.status} onChange={e=>patch(r.id,{status:e.target.value as DocStatus,receivedAt:e.target.value==="수령"?today():r.receivedAt})}>{["미수령","요청","수령","보완필요","해당없음"].map(x=><option key={x}>{x}</option>)}</select></td><td className="px-4 py-3">{r.receivedAt||"-"}</td><td className="px-4 py-3"><input className="h-8 min-w-40 rounded-md border border-slate-200 px-2 text-xs" value={r.note} onChange={e=>patch(r.id,{note:e.target.value})}/></td></tr>)}</tbody></table></div></Card></>
}

function Cases(){
 const {db,update}=useAdminStore();const [expanded,setExpanded]=useState<string|null>(null);const [q,setQ]=useState("");const matters=db.matters.filter(m=>m.clientRegistered&&["수임","진행중","서류검토중","계약진행중"].includes(m.status)).filter(m=>{const c=db.clients.find(x=>x.id===m.clientId);return `${c?.name} ${c?.phone} ${m.caseType}`.toLowerCase().includes(q.toLowerCase())});function getCase(m:Matter){return db.cases.find(x=>x.matterId===m.id)}function ensure(m:Matter){const found=getCase(m);if(found)return found;const x:CaseProgress={id:nextId("case"),matterId:m.id,currentStage:"상담/수임",court:m.court,caseNumber:"",filedAt:"",nextDueAt:"",memo:"",updatedAt:new Date().toISOString()};update(d=>({...d,cases:[...d.cases,x]}));return x}function patch(id:string,p:Partial<CaseProgress>){update(d=>({...d,cases:d.cases.map(x=>x.id===id?{...x,...p,updatedAt:new Date().toISOString()}:x)}))}
 return <><PageHeader title="사건 진행" description="기본 화면은 게시판 형태로 간단히 보고, 맨 우측 펼치기 버튼을 눌렀을 때만 현재단계·법원·사건번호·기한·메모가 표시됩니다."/><Card className="overflow-hidden"><div className="border-b border-slate-100 p-4"><SearchBox value={q} onChange={setQ}/></div><div className="overflow-x-auto"><table className="admin-responsive-table w-full text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3 text-left">의뢰인</th><th className="px-4 py-3 text-left">연락처</th><th className="px-4 py-3 text-left">사건유형</th><th className="px-4 py-3 text-left">담당자</th><th className="px-4 py-3 text-left">상태</th><th className="px-4 py-3 text-left">최근수정</th><th className="px-4 py-3 text-right">상세</th></tr></thead><tbody>{matters.map(m=>{const c=db.clients.find(x=>x.id===m.clientId);const cp=getCase(m);const is=expanded===m.id;return <Fragment key={m.id}><tr className="border-b border-slate-100 hover:bg-slate-50"><td className="px-4 py-3 font-bold">{c?.name}</td><td className="px-4 py-3">{c?.phone}</td><td className="px-4 py-3">{m.caseType}</td><td className="px-4 py-3">{m.manager}</td><td className="px-4 py-3"><Badge tone={tone(m.status)}>{m.status}</Badge></td><td className="px-4 py-3 text-slate-500">{cp?.updatedAt.slice(0,10)||"미생성"}</td><td className="px-4 py-3 text-right"><button onClick={()=>{if(!cp)ensure(m);setExpanded(is?null:m.id)}} className="inline-flex size-9 items-center justify-center rounded-lg border border-slate-200 bg-white text-slate-600 hover:bg-slate-50" aria-label="상세 펼치기">{is?<ChevronUp size={17}/>:<ChevronDown size={17}/>}</button></td></tr>{is&&<tr className="border-b border-slate-200 bg-slate-50/70"><td colSpan={7} className="px-4 py-4">{(()=>{const row=getCase(m);if(!row)return <div className="py-4 text-sm text-slate-400">사건진행 정보를 생성하는 중입니다.</div>;return <div className="grid gap-3 lg:grid-cols-4"><Label text="현재단계"><Input value={row.currentStage} onChange={e=>patch(row.id,{currentStage:e.target.value})}/></Label><Label text="관할법원"><Input value={row.court} onChange={e=>patch(row.id,{court:e.target.value})}/></Label><Label text="사건번호"><Input value={row.caseNumber} onChange={e=>patch(row.id,{caseNumber:e.target.value})}/></Label><Label text="다음기한"><Input type="date" value={row.nextDueAt} onChange={e=>patch(row.id,{nextDueAt:e.target.value})}/></Label><div className="lg:col-span-4"><Label text="진행메모"><textarea className={textarea} value={row.memo} onChange={e=>patch(row.id,{memo:e.target.value})}/></Label></div></div>})()}</td></tr>}</Fragment>})}</tbody></table></div></Card></>
}

function Board(){const {db,update,addHistory}=useAdminStore();const [open,setOpen]=useState(false);const [draft,setDraft]=useState({title:"",body:"",author:"관리자",pinned:false});function save(){if(!draft.title.trim())return;const x={id:nextId("b"),createdAt:new Date().toISOString(),...draft};update(d=>({...d,board:[x,...d.board],history:[addHistory("내부 게시판","등록",x.title,"게시글 등록"),...d.history]}));setOpen(false);setDraft({title:"",body:"",author:"관리자",pinned:false})}const rows=[...db.board].sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.createdAt.localeCompare(a.createdAt));return <><PageHeader title="내부 게시판" description="팀 공지, 처리기준, 업무메모를 공유합니다." action={<Button onClick={()=>setOpen(true)}><Plus size={15}/>글쓰기</Button>}/><Card className="overflow-hidden"><div className="divide-y divide-slate-100">{rows.map((r,i)=><div key={r.id} className="grid gap-2 px-5 py-4 md:grid-cols-[70px_1fr_100px_120px]"><div>{r.pinned?<Badge tone="blue">공지</Badge>:<span className="text-xs text-slate-400">{i+1}</span>}</div><div><b className="text-sm">{r.title}</b><div className="mt-1 text-xs leading-5 text-slate-500">{r.body}</div></div><div className="text-xs text-slate-500">{r.author}</div><div className="text-xs text-slate-400">{r.createdAt.slice(0,10)}</div></div>)}</div></Card><Modal open={open} title="게시글 작성" onClose={()=>setOpen(false)}><div className="space-y-4"><Label text="제목"><Input value={draft.title} onChange={e=>setDraft(v=>({...v,title:e.target.value}))}/></Label><Label text="본문"><textarea className={textarea} value={draft.body} onChange={e=>setDraft(v=>({...v,body:e.target.value}))}/></Label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.pinned} onChange={e=>setDraft(v=>({...v,pinned:e.target.checked}))}/>공지로 고정</label></div><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setOpen(false)}>취소</Button><Button onClick={save}>저장</Button></div></Modal></>}

function Changes(){const {db}=useAdminStore();return <><PageHeader title="기간별 변동내역" description="데모에서 발생한 주요 등록·이관·상태변경·메모 이력을 최신순으로 확인합니다."/><Card className="overflow-hidden"><div className="overflow-x-auto"><table className="admin-responsive-table w-full text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-4 py-3 text-left">일시</th><th className="px-4 py-3 text-left">메뉴</th><th className="px-4 py-3 text-left">작업</th><th className="px-4 py-3 text-left">대상</th><th className="px-4 py-3 text-left">내용</th></tr></thead><tbody className="divide-y divide-slate-100">{[...db.history].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(r=><tr key={r.id}><td className="px-4 py-3 text-slate-500">{r.createdAt.slice(0,16).replace("T"," ")}</td><td className="px-4 py-3">{r.category}</td><td className="px-4 py-3"><Badge>{r.action}</Badge></td><td className="px-4 py-3 font-bold">{r.target}</td><td className="px-4 py-3 text-slate-600">{r.detail}</td></tr>)}</tbody></table></div></Card></>}

function Analytics(){const {db}=useAdminStore();const total=db.matters.length;const registered=db.matters.filter(m=>m.clientRegistered).length;const retained=db.matters.filter(m=>["수임","진행중","종결(성공)"].includes(m.status)).length;const contracts=db.contracts.reduce((s,x)=>s+x.contractAmount,0);const paid=db.payments.filter(p=>p.status==="완료").reduce((s,x)=>s+x.paidAmount,0);const statusRows=matterStatuses.map(s=>({status:s,count:db.matters.filter(m=>m.status===s).length})).filter(x=>x.count);return <><PageHeader title="데이터 집계" description="상담 DB → 의뢰인 등록 → 수임/진행 전환과 계약·입금 현황을 업무형 표로 확인합니다."/><div className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card className="p-4"><div className="text-xs text-slate-500">전체 상담 DB</div><div className="mt-2 text-2xl font-bold">{total}건</div></Card><Card className="p-4"><div className="text-xs text-slate-500">의뢰인 등록률</div><div className="mt-2 text-2xl font-bold text-blue-700">{total?((registered/total)*100).toFixed(1):"0.0"}%</div></Card><Card className="p-4"><div className="text-xs text-slate-500">수임/진행 전환</div><div className="mt-2 text-2xl font-bold text-emerald-700">{registered?((retained/registered)*100).toFixed(1):"0.0"}%</div></Card><Card className="p-4"><div className="text-xs text-slate-500">계약 / 실입금</div><div className="mt-2 font-bold">{won(contracts)} / {won(paid)}</div></Card></div><Card className="overflow-hidden"><div className="border-b border-slate-100 px-5 py-4 font-bold">상담 상태별 현황</div><div className="divide-y divide-slate-100">{statusRows.map(r=><div key={r.status} className="flex items-center justify-between px-5 py-3"><div className="flex items-center gap-2"><Badge tone={tone(r.status)}>{r.status}</Badge><span className="text-sm text-slate-500">전체 대비</span></div><div className="flex items-center gap-4"><b>{r.count}건</b><span className="w-16 text-right text-xs text-slate-400">{total?((r.count/total)*100).toFixed(1):0}%</span></div></div>)}</div></Card></>}

function Settings(){const {db,update,reset}=useAdminStore();return <><PageHeader title="기준표 / 설정" description="예상 변제계획에 사용하는 데모 기준값입니다. 실제 운영 전에는 해당 연도의 공식 기준을 확인하여 교체해야 합니다." action={<Button variant="secondary" onClick={()=>{if(confirm("데모 데이터를 초기화할까요?"))reset()}}>데모 초기화</Button>}/><Card className="overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><b>가구원 수별 기준 생활비</b><div className="mt-1 text-xs text-slate-400">기준연도 {db.settings.referenceYear} · 현재 값은 기능 테스트용 데모값</div></div><div className="divide-y divide-slate-100">{Object.entries(db.settings.livingCostByHousehold).map(([k,v])=><div key={k} className="grid items-center gap-3 px-5 py-3 sm:grid-cols-[160px_240px]"><div className="text-sm font-semibold">{k}인 가구</div><NumberInput value={v} onChange={n=>update(d=>({...d,settings:{...d.settings,livingCostByHousehold:{...d.settings.livingCostByHousehold,[k]:n}}}))}/></div>)}</div></Card></>}
